// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/cloudreve/Cloudreve/v4/ent/auditlog"
	"github.com/cloudreve/Cloudreve/v4/ent/davaccount"
	"github.com/cloudreve/Cloudreve/v4/ent/directlink"
	"github.com/cloudreve/Cloudreve/v4/ent/entity"
	"github.com/cloudreve/Cloudreve/v4/ent/externalidentity"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/fsevent"
	"github.com/cloudreve/Cloudreve/v4/ent/ftsexternaljob"
	"github.com/cloudreve/Cloudreve/v4/ent/group"
	"github.com/cloudreve/Cloudreve/v4/ent/metadata"
	"github.com/cloudreve/Cloudreve/v4/ent/node"
	"github.com/cloudreve/Cloudreve/v4/ent/oauthclient"
	"github.com/cloudreve/Cloudreve/v4/ent/oauthgrant"
	"github.com/cloudreve/Cloudreve/v4/ent/passkey"
	"github.com/cloudreve/Cloudreve/v4/ent/schema"
	"github.com/cloudreve/Cloudreve/v4/ent/setting"
	"github.com/cloudreve/Cloudreve/v4/ent/share"
	"github.com/cloudreve/Cloudreve/v4/ent/storagepolicy"
	"github.com/cloudreve/Cloudreve/v4/ent/syncthingdevice"
	"github.com/cloudreve/Cloudreve/v4/ent/task"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogMixin := schema.AuditLog{}.Mixin()
	auditlogMixinHooks0 := auditlogMixin[0].Hooks()
	auditlog.Hooks[0] = auditlogMixinHooks0[0]
	auditlogMixinInters0 := auditlogMixin[0].Interceptors()
	auditlog.Interceptors[0] = auditlogMixinInters0[0]
	auditlogMixinFields0 := auditlogMixin[0].Fields()
	_ = auditlogMixinFields0
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogMixinFields0[0].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	// auditlogDescUpdatedAt is the schema descriptor for updated_at field.
	auditlogDescUpdatedAt := auditlogMixinFields0[1].Descriptor()
	// auditlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	auditlog.DefaultUpdatedAt = auditlogDescUpdatedAt.Default.(func() time.Time)
	// auditlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	auditlog.UpdateDefaultUpdatedAt = auditlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	davaccountMixin := schema.DavAccount{}.Mixin()
	davaccountMixinHooks0 := davaccountMixin[0].Hooks()
	davaccount.Hooks[0] = davaccountMixinHooks0[0]
	davaccountMixinInters0 := davaccountMixin[0].Interceptors()
	davaccount.Interceptors[0] = davaccountMixinInters0[0]
	davaccountMixinFields0 := davaccountMixin[0].Fields()
	_ = davaccountMixinFields0
	davaccountFields := schema.DavAccount{}.Fields()
	_ = davaccountFields
	// davaccountDescCreatedAt is the schema descriptor for created_at field.
	davaccountDescCreatedAt := davaccountMixinFields0[0].Descriptor()
	// davaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	davaccount.DefaultCreatedAt = davaccountDescCreatedAt.Default.(func() time.Time)
	// davaccountDescUpdatedAt is the schema descriptor for updated_at field.
	davaccountDescUpdatedAt := davaccountMixinFields0[1].Descriptor()
	// davaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	davaccount.DefaultUpdatedAt = davaccountDescUpdatedAt.Default.(func() time.Time)
	// davaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	davaccount.UpdateDefaultUpdatedAt = davaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	directlinkMixin := schema.DirectLink{}.Mixin()
	directlinkMixinHooks0 := directlinkMixin[0].Hooks()
	directlink.Hooks[0] = directlinkMixinHooks0[0]
	directlinkMixinInters0 := directlinkMixin[0].Interceptors()
	directlink.Interceptors[0] = directlinkMixinInters0[0]
	directlinkMixinFields0 := directlinkMixin[0].Fields()
	_ = directlinkMixinFields0
	directlinkFields := schema.DirectLink{}.Fields()
	_ = directlinkFields
	// directlinkDescCreatedAt is the schema descriptor for created_at field.
	directlinkDescCreatedAt := directlinkMixinFields0[0].Descriptor()
	// directlink.DefaultCreatedAt holds the default value on creation for the created_at field.
	directlink.DefaultCreatedAt = directlinkDescCreatedAt.Default.(func() time.Time)
	// directlinkDescUpdatedAt is the schema descriptor for updated_at field.
	directlinkDescUpdatedAt := directlinkMixinFields0[1].Descriptor()
	// directlink.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	directlink.DefaultUpdatedAt = directlinkDescUpdatedAt.Default.(func() time.Time)
	// directlink.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	directlink.UpdateDefaultUpdatedAt = directlinkDescUpdatedAt.UpdateDefault.(func() time.Time)
	entityMixin := schema.Entity{}.Mixin()
	entityMixinHooks0 := entityMixin[0].Hooks()
	entity.Hooks[0] = entityMixinHooks0[0]
	entityMixinInters0 := entityMixin[0].Interceptors()
	entity.Interceptors[0] = entityMixinInters0[0]
	entityMixinFields0 := entityMixin[0].Fields()
	_ = entityMixinFields0
	entityFields := schema.Entity{}.Fields()
	_ = entityFields
	// entityDescCreatedAt is the schema descriptor for created_at field.
	entityDescCreatedAt := entityMixinFields0[0].Descriptor()
	// entity.DefaultCreatedAt holds the default value on creation for the created_at field.
	entity.DefaultCreatedAt = entityDescCreatedAt.Default.(func() time.Time)
	// entityDescUpdatedAt is the schema descriptor for updated_at field.
	entityDescUpdatedAt := entityMixinFields0[1].Descriptor()
	// entity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	entity.DefaultUpdatedAt = entityDescUpdatedAt.Default.(func() time.Time)
	// entity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entity.UpdateDefaultUpdatedAt = entityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entityDescReferenceCount is the schema descriptor for reference_count field.
	entityDescReferenceCount := entityFields[3].Descriptor()
	// entity.DefaultReferenceCount holds the default value on creation for the reference_count field.
	entity.DefaultReferenceCount = entityDescReferenceCount.Default.(int)
	externalidentityMixin := schema.ExternalIdentity{}.Mixin()
	externalidentityMixinHooks0 := externalidentityMixin[0].Hooks()
	externalidentity.Hooks[0] = externalidentityMixinHooks0[0]
	externalidentityMixinInters0 := externalidentityMixin[0].Interceptors()
	externalidentity.Interceptors[0] = externalidentityMixinInters0[0]
	externalidentityMixinFields0 := externalidentityMixin[0].Fields()
	_ = externalidentityMixinFields0
	externalidentityFields := schema.ExternalIdentity{}.Fields()
	_ = externalidentityFields
	// externalidentityDescCreatedAt is the schema descriptor for created_at field.
	externalidentityDescCreatedAt := externalidentityMixinFields0[0].Descriptor()
	// externalidentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	externalidentity.DefaultCreatedAt = externalidentityDescCreatedAt.Default.(func() time.Time)
	// externalidentityDescUpdatedAt is the schema descriptor for updated_at field.
	externalidentityDescUpdatedAt := externalidentityMixinFields0[1].Descriptor()
	// externalidentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	externalidentity.DefaultUpdatedAt = externalidentityDescUpdatedAt.Default.(func() time.Time)
	// externalidentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	externalidentity.UpdateDefaultUpdatedAt = externalidentityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// externalidentityDescProvider is the schema descriptor for provider field.
	externalidentityDescProvider := externalidentityFields[0].Descriptor()
	// externalidentity.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	externalidentity.ProviderValidator = externalidentityDescProvider.Validators[0].(func(string) error)
	// externalidentityDescIssuer is the schema descriptor for issuer field.
	externalidentityDescIssuer := externalidentityFields[1].Descriptor()
	// externalidentity.IssuerValidator is a validator for the "issuer" field. It is called by the builders before save.
	externalidentity.IssuerValidator = externalidentityDescIssuer.Validators[0].(func(string) error)
	// externalidentityDescSubject is the schema descriptor for subject field.
	externalidentityDescSubject := externalidentityFields[2].Descriptor()
	// externalidentity.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	externalidentity.SubjectValidator = externalidentityDescSubject.Validators[0].(func(string) error)
	// externalidentityDescExternalUserID is the schema descriptor for external_user_id field.
	externalidentityDescExternalUserID := externalidentityFields[3].Descriptor()
	// externalidentity.ExternalUserIDValidator is a validator for the "external_user_id" field. It is called by the builders before save.
	externalidentity.ExternalUserIDValidator = externalidentityDescExternalUserID.Validators[0].(func(string) error)
	// externalidentityDescTenantID is the schema descriptor for tenant_id field.
	externalidentityDescTenantID := externalidentityFields[4].Descriptor()
	// externalidentity.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	externalidentity.TenantIDValidator = externalidentityDescTenantID.Validators[0].(func(string) error)
	// externalidentityDescDepartmentID is the schema descriptor for department_id field.
	externalidentityDescDepartmentID := externalidentityFields[5].Descriptor()
	// externalidentity.DepartmentIDValidator is a validator for the "department_id" field. It is called by the builders before save.
	externalidentity.DepartmentIDValidator = externalidentityDescDepartmentID.Validators[0].(func(string) error)
	// externalidentityDescEmail is the schema descriptor for email field.
	externalidentityDescEmail := externalidentityFields[6].Descriptor()
	// externalidentity.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	externalidentity.EmailValidator = externalidentityDescEmail.Validators[0].(func(string) error)
	// externalidentityDescUsername is the schema descriptor for username field.
	externalidentityDescUsername := externalidentityFields[7].Descriptor()
	// externalidentity.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	externalidentity.UsernameValidator = externalidentityDescUsername.Validators[0].(func(string) error)
	// externalidentityDescNickname is the schema descriptor for nickname field.
	externalidentityDescNickname := externalidentityFields[8].Descriptor()
	// externalidentity.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	externalidentity.NicknameValidator = externalidentityDescNickname.Validators[0].(func(string) error)
	// externalidentityDescAvatar is the schema descriptor for avatar field.
	externalidentityDescAvatar := externalidentityFields[9].Descriptor()
	// externalidentity.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	externalidentity.AvatarValidator = externalidentityDescAvatar.Validators[0].(func(string) error)
	// externalidentityDescClaims is the schema descriptor for claims field.
	externalidentityDescClaims := externalidentityFields[10].Descriptor()
	// externalidentity.DefaultClaims holds the default value on creation for the claims field.
	externalidentity.DefaultClaims = externalidentityDescClaims.Default.(map[string]interface{})
	ftsexternaljobMixin := schema.FTSExternalJob{}.Mixin()
	ftsexternaljobMixinHooks0 := ftsexternaljobMixin[0].Hooks()
	ftsexternaljob.Hooks[0] = ftsexternaljobMixinHooks0[0]
	ftsexternaljobMixinInters0 := ftsexternaljobMixin[0].Interceptors()
	ftsexternaljob.Interceptors[0] = ftsexternaljobMixinInters0[0]
	ftsexternaljobMixinFields0 := ftsexternaljobMixin[0].Fields()
	_ = ftsexternaljobMixinFields0
	ftsexternaljobFields := schema.FTSExternalJob{}.Fields()
	_ = ftsexternaljobFields
	// ftsexternaljobDescCreatedAt is the schema descriptor for created_at field.
	ftsexternaljobDescCreatedAt := ftsexternaljobMixinFields0[0].Descriptor()
	// ftsexternaljob.DefaultCreatedAt holds the default value on creation for the created_at field.
	ftsexternaljob.DefaultCreatedAt = ftsexternaljobDescCreatedAt.Default.(func() time.Time)
	// ftsexternaljobDescUpdatedAt is the schema descriptor for updated_at field.
	ftsexternaljobDescUpdatedAt := ftsexternaljobMixinFields0[1].Descriptor()
	// ftsexternaljob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ftsexternaljob.DefaultUpdatedAt = ftsexternaljobDescUpdatedAt.Default.(func() time.Time)
	// ftsexternaljob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ftsexternaljob.UpdateDefaultUpdatedAt = ftsexternaljobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ftsexternaljobDescStatus is the schema descriptor for status field.
	ftsexternaljobDescStatus := ftsexternaljobFields[1].Descriptor()
	// ftsexternaljob.DefaultStatus holds the default value on creation for the status field.
	ftsexternaljob.DefaultStatus = ftsexternaljobDescStatus.Default.(string)
	// ftsexternaljobDescMode is the schema descriptor for mode field.
	ftsexternaljobDescMode := ftsexternaljobFields[6].Descriptor()
	// ftsexternaljob.DefaultMode holds the default value on creation for the mode field.
	ftsexternaljob.DefaultMode = ftsexternaljobDescMode.Default.(string)
	// ftsexternaljobDescTriggerReason is the schema descriptor for trigger_reason field.
	ftsexternaljobDescTriggerReason := ftsexternaljobFields[7].Descriptor()
	// ftsexternaljob.DefaultTriggerReason holds the default value on creation for the trigger_reason field.
	ftsexternaljob.DefaultTriggerReason = ftsexternaljobDescTriggerReason.Default.(string)
	// ftsexternaljobDescAttempt is the schema descriptor for attempt field.
	ftsexternaljobDescAttempt := ftsexternaljobFields[8].Descriptor()
	// ftsexternaljob.DefaultAttempt holds the default value on creation for the attempt field.
	ftsexternaljob.DefaultAttempt = ftsexternaljobDescAttempt.Default.(int)
	// ftsexternaljobDescRequestedAt is the schema descriptor for requested_at field.
	ftsexternaljobDescRequestedAt := ftsexternaljobFields[13].Descriptor()
	// ftsexternaljob.DefaultRequestedAt holds the default value on creation for the requested_at field.
	ftsexternaljob.DefaultRequestedAt = ftsexternaljobDescRequestedAt.Default.(func() time.Time)
	fileHooks := schema.File{}.Hooks()
	file.Hooks[0] = fileHooks[0]
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescCreatedAt is the schema descriptor for created_at field.
	fileDescCreatedAt := fileFields[0].Descriptor()
	// file.DefaultCreatedAt holds the default value on creation for the created_at field.
	file.DefaultCreatedAt = fileDescCreatedAt.Default.(func() time.Time)
	// fileDescUpdatedAt is the schema descriptor for updated_at field.
	fileDescUpdatedAt := fileFields[1].Descriptor()
	// file.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	file.DefaultUpdatedAt = fileDescUpdatedAt.Default.(func() time.Time)
	// fileDescFileExt is the schema descriptor for file_ext field.
	fileDescFileExt := fileFields[4].Descriptor()
	// file.DefaultFileExt holds the default value on creation for the file_ext field.
	file.DefaultFileExt = fileDescFileExt.Default.(string)
	// fileDescSize is the schema descriptor for size field.
	fileDescSize := fileFields[6].Descriptor()
	// file.DefaultSize holds the default value on creation for the size field.
	file.DefaultSize = fileDescSize.Default.(int64)
	// fileDescIsSymbolic is the schema descriptor for is_symbolic field.
	fileDescIsSymbolic := fileFields[9].Descriptor()
	// file.DefaultIsSymbolic holds the default value on creation for the is_symbolic field.
	file.DefaultIsSymbolic = fileDescIsSymbolic.Default.(bool)
	fseventMixin := schema.FsEvent{}.Mixin()
	fseventMixinHooks0 := fseventMixin[0].Hooks()
	fsevent.Hooks[0] = fseventMixinHooks0[0]
	fseventMixinInters0 := fseventMixin[0].Interceptors()
	fsevent.Interceptors[0] = fseventMixinInters0[0]
	fseventMixinFields0 := fseventMixin[0].Fields()
	_ = fseventMixinFields0
	fseventFields := schema.FsEvent{}.Fields()
	_ = fseventFields
	// fseventDescCreatedAt is the schema descriptor for created_at field.
	fseventDescCreatedAt := fseventMixinFields0[0].Descriptor()
	// fsevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	fsevent.DefaultCreatedAt = fseventDescCreatedAt.Default.(func() time.Time)
	// fseventDescUpdatedAt is the schema descriptor for updated_at field.
	fseventDescUpdatedAt := fseventMixinFields0[1].Descriptor()
	// fsevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	fsevent.DefaultUpdatedAt = fseventDescUpdatedAt.Default.(func() time.Time)
	// fsevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	fsevent.UpdateDefaultUpdatedAt = fseventDescUpdatedAt.UpdateDefault.(func() time.Time)
	groupMixin := schema.Group{}.Mixin()
	groupMixinHooks0 := groupMixin[0].Hooks()
	group.Hooks[0] = groupMixinHooks0[0]
	groupMixinInters0 := groupMixin[0].Interceptors()
	group.Interceptors[0] = groupMixinInters0[0]
	groupMixinFields0 := groupMixin[0].Fields()
	_ = groupMixinFields0
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupMixinFields0[0].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupMixinFields0[1].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// groupDescSettings is the schema descriptor for settings field.
	groupDescSettings := groupFields[4].Descriptor()
	// group.DefaultSettings holds the default value on creation for the settings field.
	group.DefaultSettings = groupDescSettings.Default.(*types.GroupSetting)
	metadataMixin := schema.Metadata{}.Mixin()
	metadataMixinHooks0 := metadataMixin[0].Hooks()
	metadata.Hooks[0] = metadataMixinHooks0[0]
	metadataMixinInters0 := metadataMixin[0].Interceptors()
	metadata.Interceptors[0] = metadataMixinInters0[0]
	metadataMixinFields0 := metadataMixin[0].Fields()
	_ = metadataMixinFields0
	metadataFields := schema.Metadata{}.Fields()
	_ = metadataFields
	// metadataDescCreatedAt is the schema descriptor for created_at field.
	metadataDescCreatedAt := metadataMixinFields0[0].Descriptor()
	// metadata.DefaultCreatedAt holds the default value on creation for the created_at field.
	metadata.DefaultCreatedAt = metadataDescCreatedAt.Default.(func() time.Time)
	// metadataDescUpdatedAt is the schema descriptor for updated_at field.
	metadataDescUpdatedAt := metadataMixinFields0[1].Descriptor()
	// metadata.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	metadata.DefaultUpdatedAt = metadataDescUpdatedAt.Default.(func() time.Time)
	// metadata.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	metadata.UpdateDefaultUpdatedAt = metadataDescUpdatedAt.UpdateDefault.(func() time.Time)
	// metadataDescIsPublic is the schema descriptor for is_public field.
	metadataDescIsPublic := metadataFields[3].Descriptor()
	// metadata.DefaultIsPublic holds the default value on creation for the is_public field.
	metadata.DefaultIsPublic = metadataDescIsPublic.Default.(bool)
	nodeMixin := schema.Node{}.Mixin()
	nodeMixinHooks0 := nodeMixin[0].Hooks()
	node.Hooks[0] = nodeMixinHooks0[0]
	nodeMixinInters0 := nodeMixin[0].Interceptors()
	node.Interceptors[0] = nodeMixinInters0[0]
	nodeMixinFields0 := nodeMixin[0].Fields()
	_ = nodeMixinFields0
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeMixinFields0[0].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() time.Time)
	// nodeDescUpdatedAt is the schema descriptor for updated_at field.
	nodeDescUpdatedAt := nodeMixinFields0[1].Descriptor()
	// node.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	node.DefaultUpdatedAt = nodeDescUpdatedAt.Default.(func() time.Time)
	// node.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	node.UpdateDefaultUpdatedAt = nodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// nodeDescSettings is the schema descriptor for settings field.
	nodeDescSettings := nodeFields[6].Descriptor()
	// node.DefaultSettings holds the default value on creation for the settings field.
	node.DefaultSettings = nodeDescSettings.Default.(*types.NodeSetting)
	// nodeDescWeight is the schema descriptor for weight field.
	nodeDescWeight := nodeFields[7].Descriptor()
	// node.DefaultWeight holds the default value on creation for the weight field.
	node.DefaultWeight = nodeDescWeight.Default.(int)
	oauthclientMixin := schema.OAuthClient{}.Mixin()
	oauthclientMixinHooks0 := oauthclientMixin[0].Hooks()
	oauthclient.Hooks[0] = oauthclientMixinHooks0[0]
	oauthclientMixinInters0 := oauthclientMixin[0].Interceptors()
	oauthclient.Interceptors[0] = oauthclientMixinInters0[0]
	oauthclientMixinFields0 := oauthclientMixin[0].Fields()
	_ = oauthclientMixinFields0
	oauthclientFields := schema.OAuthClient{}.Fields()
	_ = oauthclientFields
	// oauthclientDescCreatedAt is the schema descriptor for created_at field.
	oauthclientDescCreatedAt := oauthclientMixinFields0[0].Descriptor()
	// oauthclient.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthclient.DefaultCreatedAt = oauthclientDescCreatedAt.Default.(func() time.Time)
	// oauthclientDescUpdatedAt is the schema descriptor for updated_at field.
	oauthclientDescUpdatedAt := oauthclientMixinFields0[1].Descriptor()
	// oauthclient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthclient.DefaultUpdatedAt = oauthclientDescUpdatedAt.Default.(func() time.Time)
	// oauthclient.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthclient.UpdateDefaultUpdatedAt = oauthclientDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthclientDescGUID is the schema descriptor for guid field.
	oauthclientDescGUID := oauthclientFields[0].Descriptor()
	// oauthclient.GUIDValidator is a validator for the "guid" field. It is called by the builders before save.
	oauthclient.GUIDValidator = oauthclientDescGUID.Validators[0].(func(string) error)
	// oauthclientDescSecret is the schema descriptor for secret field.
	oauthclientDescSecret := oauthclientFields[1].Descriptor()
	// oauthclient.SecretValidator is a validator for the "secret" field. It is called by the builders before save.
	oauthclient.SecretValidator = oauthclientDescSecret.Validators[0].(func(string) error)
	// oauthclientDescName is the schema descriptor for name field.
	oauthclientDescName := oauthclientFields[2].Descriptor()
	// oauthclient.NameValidator is a validator for the "name" field. It is called by the builders before save.
	oauthclient.NameValidator = oauthclientDescName.Validators[0].(func(string) error)
	// oauthclientDescHomepageURL is the schema descriptor for homepage_url field.
	oauthclientDescHomepageURL := oauthclientFields[3].Descriptor()
	// oauthclient.HomepageURLValidator is a validator for the "homepage_url" field. It is called by the builders before save.
	oauthclient.HomepageURLValidator = oauthclientDescHomepageURL.Validators[0].(func(string) error)
	// oauthclientDescRedirectUris is the schema descriptor for redirect_uris field.
	oauthclientDescRedirectUris := oauthclientFields[4].Descriptor()
	// oauthclient.DefaultRedirectUris holds the default value on creation for the redirect_uris field.
	oauthclient.DefaultRedirectUris = oauthclientDescRedirectUris.Default.([]string)
	// oauthclientDescScopes is the schema descriptor for scopes field.
	oauthclientDescScopes := oauthclientFields[5].Descriptor()
	// oauthclient.DefaultScopes holds the default value on creation for the scopes field.
	oauthclient.DefaultScopes = oauthclientDescScopes.Default.([]string)
	// oauthclientDescProps is the schema descriptor for props field.
	oauthclientDescProps := oauthclientFields[6].Descriptor()
	// oauthclient.DefaultProps holds the default value on creation for the props field.
	oauthclient.DefaultProps = oauthclientDescProps.Default.(*types.OAuthClientProps)
	// oauthclientDescIsEnabled is the schema descriptor for is_enabled field.
	oauthclientDescIsEnabled := oauthclientFields[7].Descriptor()
	// oauthclient.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	oauthclient.DefaultIsEnabled = oauthclientDescIsEnabled.Default.(bool)
	oauthgrantMixin := schema.OAuthGrant{}.Mixin()
	oauthgrantMixinHooks0 := oauthgrantMixin[0].Hooks()
	oauthgrant.Hooks[0] = oauthgrantMixinHooks0[0]
	oauthgrantMixinInters0 := oauthgrantMixin[0].Interceptors()
	oauthgrant.Interceptors[0] = oauthgrantMixinInters0[0]
	oauthgrantMixinFields0 := oauthgrantMixin[0].Fields()
	_ = oauthgrantMixinFields0
	oauthgrantFields := schema.OAuthGrant{}.Fields()
	_ = oauthgrantFields
	// oauthgrantDescCreatedAt is the schema descriptor for created_at field.
	oauthgrantDescCreatedAt := oauthgrantMixinFields0[0].Descriptor()
	// oauthgrant.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthgrant.DefaultCreatedAt = oauthgrantDescCreatedAt.Default.(func() time.Time)
	// oauthgrantDescUpdatedAt is the schema descriptor for updated_at field.
	oauthgrantDescUpdatedAt := oauthgrantMixinFields0[1].Descriptor()
	// oauthgrant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthgrant.DefaultUpdatedAt = oauthgrantDescUpdatedAt.Default.(func() time.Time)
	// oauthgrant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthgrant.UpdateDefaultUpdatedAt = oauthgrantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthgrantDescScopes is the schema descriptor for scopes field.
	oauthgrantDescScopes := oauthgrantFields[2].Descriptor()
	// oauthgrant.DefaultScopes holds the default value on creation for the scopes field.
	oauthgrant.DefaultScopes = oauthgrantDescScopes.Default.([]string)
	passkeyMixin := schema.Passkey{}.Mixin()
	passkeyMixinHooks0 := passkeyMixin[0].Hooks()
	passkey.Hooks[0] = passkeyMixinHooks0[0]
	passkeyMixinInters0 := passkeyMixin[0].Interceptors()
	passkey.Interceptors[0] = passkeyMixinInters0[0]
	passkeyMixinFields0 := passkeyMixin[0].Fields()
	_ = passkeyMixinFields0
	passkeyFields := schema.Passkey{}.Fields()
	_ = passkeyFields
	// passkeyDescCreatedAt is the schema descriptor for created_at field.
	passkeyDescCreatedAt := passkeyMixinFields0[0].Descriptor()
	// passkey.DefaultCreatedAt holds the default value on creation for the created_at field.
	passkey.DefaultCreatedAt = passkeyDescCreatedAt.Default.(func() time.Time)
	// passkeyDescUpdatedAt is the schema descriptor for updated_at field.
	passkeyDescUpdatedAt := passkeyMixinFields0[1].Descriptor()
	// passkey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	passkey.DefaultUpdatedAt = passkeyDescUpdatedAt.Default.(func() time.Time)
	// passkey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	passkey.UpdateDefaultUpdatedAt = passkeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	settingMixin := schema.Setting{}.Mixin()
	settingMixinHooks0 := settingMixin[0].Hooks()
	setting.Hooks[0] = settingMixinHooks0[0]
	settingMixinInters0 := settingMixin[0].Interceptors()
	setting.Interceptors[0] = settingMixinInters0[0]
	settingMixinFields0 := settingMixin[0].Fields()
	_ = settingMixinFields0
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingMixinFields0[0].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingMixinFields0[1].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	shareMixin := schema.Share{}.Mixin()
	shareMixinHooks0 := shareMixin[0].Hooks()
	share.Hooks[0] = shareMixinHooks0[0]
	shareMixinInters0 := shareMixin[0].Interceptors()
	share.Interceptors[0] = shareMixinInters0[0]
	shareMixinFields0 := shareMixin[0].Fields()
	_ = shareMixinFields0
	shareFields := schema.Share{}.Fields()
	_ = shareFields
	// shareDescCreatedAt is the schema descriptor for created_at field.
	shareDescCreatedAt := shareMixinFields0[0].Descriptor()
	// share.DefaultCreatedAt holds the default value on creation for the created_at field.
	share.DefaultCreatedAt = shareDescCreatedAt.Default.(func() time.Time)
	// shareDescUpdatedAt is the schema descriptor for updated_at field.
	shareDescUpdatedAt := shareMixinFields0[1].Descriptor()
	// share.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	share.DefaultUpdatedAt = shareDescUpdatedAt.Default.(func() time.Time)
	// share.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	share.UpdateDefaultUpdatedAt = shareDescUpdatedAt.UpdateDefault.(func() time.Time)
	// shareDescViews is the schema descriptor for views field.
	shareDescViews := shareFields[1].Descriptor()
	// share.DefaultViews holds the default value on creation for the views field.
	share.DefaultViews = shareDescViews.Default.(int)
	// shareDescDownloads is the schema descriptor for downloads field.
	shareDescDownloads := shareFields[2].Descriptor()
	// share.DefaultDownloads holds the default value on creation for the downloads field.
	share.DefaultDownloads = shareDescDownloads.Default.(int)
	storagepolicyMixin := schema.StoragePolicy{}.Mixin()
	storagepolicyMixinHooks0 := storagepolicyMixin[0].Hooks()
	storagepolicy.Hooks[0] = storagepolicyMixinHooks0[0]
	storagepolicyMixinInters0 := storagepolicyMixin[0].Interceptors()
	storagepolicy.Interceptors[0] = storagepolicyMixinInters0[0]
	storagepolicyMixinFields0 := storagepolicyMixin[0].Fields()
	_ = storagepolicyMixinFields0
	storagepolicyFields := schema.StoragePolicy{}.Fields()
	_ = storagepolicyFields
	// storagepolicyDescCreatedAt is the schema descriptor for created_at field.
	storagepolicyDescCreatedAt := storagepolicyMixinFields0[0].Descriptor()
	// storagepolicy.DefaultCreatedAt holds the default value on creation for the created_at field.
	storagepolicy.DefaultCreatedAt = storagepolicyDescCreatedAt.Default.(func() time.Time)
	// storagepolicyDescUpdatedAt is the schema descriptor for updated_at field.
	storagepolicyDescUpdatedAt := storagepolicyMixinFields0[1].Descriptor()
	// storagepolicy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	storagepolicy.DefaultUpdatedAt = storagepolicyDescUpdatedAt.Default.(func() time.Time)
	// storagepolicy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	storagepolicy.UpdateDefaultUpdatedAt = storagepolicyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// storagepolicyDescSettings is the schema descriptor for settings field.
	storagepolicyDescSettings := storagepolicyFields[10].Descriptor()
	// storagepolicy.DefaultSettings holds the default value on creation for the settings field.
	storagepolicy.DefaultSettings = storagepolicyDescSettings.Default.(*types.PolicySetting)
	syncthingdeviceMixin := schema.SyncthingDevice{}.Mixin()
	syncthingdeviceMixinHooks0 := syncthingdeviceMixin[0].Hooks()
	syncthingdevice.Hooks[0] = syncthingdeviceMixinHooks0[0]
	syncthingdeviceMixinInters0 := syncthingdeviceMixin[0].Interceptors()
	syncthingdevice.Interceptors[0] = syncthingdeviceMixinInters0[0]
	syncthingdeviceMixinFields0 := syncthingdeviceMixin[0].Fields()
	_ = syncthingdeviceMixinFields0
	syncthingdeviceFields := schema.SyncthingDevice{}.Fields()
	_ = syncthingdeviceFields
	// syncthingdeviceDescCreatedAt is the schema descriptor for created_at field.
	syncthingdeviceDescCreatedAt := syncthingdeviceMixinFields0[0].Descriptor()
	// syncthingdevice.DefaultCreatedAt holds the default value on creation for the created_at field.
	syncthingdevice.DefaultCreatedAt = syncthingdeviceDescCreatedAt.Default.(func() time.Time)
	// syncthingdeviceDescUpdatedAt is the schema descriptor for updated_at field.
	syncthingdeviceDescUpdatedAt := syncthingdeviceMixinFields0[1].Descriptor()
	// syncthingdevice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	syncthingdevice.DefaultUpdatedAt = syncthingdeviceDescUpdatedAt.Default.(func() time.Time)
	// syncthingdevice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	syncthingdevice.UpdateDefaultUpdatedAt = syncthingdeviceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// syncthingdeviceDescDeviceID is the schema descriptor for device_id field.
	syncthingdeviceDescDeviceID := syncthingdeviceFields[1].Descriptor()
	// syncthingdevice.DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	syncthingdevice.DeviceIDValidator = syncthingdeviceDescDeviceID.Validators[0].(func(string) error)
	// syncthingdeviceDescShortID is the schema descriptor for short_id field.
	syncthingdeviceDescShortID := syncthingdeviceFields[2].Descriptor()
	// syncthingdevice.ShortIDValidator is a validator for the "short_id" field. It is called by the builders before save.
	syncthingdevice.ShortIDValidator = syncthingdeviceDescShortID.Validators[0].(func(string) error)
	// syncthingdeviceDescLastIP is the schema descriptor for last_ip field.
	syncthingdeviceDescLastIP := syncthingdeviceFields[3].Descriptor()
	// syncthingdevice.LastIPValidator is a validator for the "last_ip" field. It is called by the builders before save.
	syncthingdevice.LastIPValidator = syncthingdeviceDescLastIP.Validators[0].(func(string) error)
	// syncthingdeviceDescAPIKey is the schema descriptor for api_key field.
	syncthingdeviceDescAPIKey := syncthingdeviceFields[4].Descriptor()
	// syncthingdevice.APIKeyValidator is a validator for the "api_key" field. It is called by the builders before save.
	syncthingdevice.APIKeyValidator = syncthingdeviceDescAPIKey.Validators[0].(func(string) error)
	// syncthingdeviceDescJSONRaw is the schema descriptor for json_raw field.
	syncthingdeviceDescJSONRaw := syncthingdeviceFields[5].Descriptor()
	// syncthingdevice.DefaultJSONRaw holds the default value on creation for the json_raw field.
	syncthingdevice.DefaultJSONRaw = syncthingdeviceDescJSONRaw.Default.(map[string]interface{})
	// syncthingdeviceDescBindURI is the schema descriptor for bind_uri field.
	syncthingdeviceDescBindURI := syncthingdeviceFields[6].Descriptor()
	// syncthingdevice.BindURIValidator is a validator for the "bind_uri" field. It is called by the builders before save.
	syncthingdevice.BindURIValidator = syncthingdeviceDescBindURI.Validators[0].(func(string) error)
	// syncthingdeviceDescClientVersion is the schema descriptor for client_version field.
	syncthingdeviceDescClientVersion := syncthingdeviceFields[7].Descriptor()
	// syncthingdevice.ClientVersionValidator is a validator for the "client_version" field. It is called by the builders before save.
	syncthingdevice.ClientVersionValidator = syncthingdeviceDescClientVersion.Validators[0].(func(string) error)
	// syncthingdeviceDescPlatform is the schema descriptor for platform field.
	syncthingdeviceDescPlatform := syncthingdeviceFields[8].Descriptor()
	// syncthingdevice.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	syncthingdevice.PlatformValidator = syncthingdeviceDescPlatform.Validators[0].(func(string) error)
	// syncthingdeviceDescOnline is the schema descriptor for online field.
	syncthingdeviceDescOnline := syncthingdeviceFields[11].Descriptor()
	// syncthingdevice.DefaultOnline holds the default value on creation for the online field.
	syncthingdevice.DefaultOnline = syncthingdeviceDescOnline.Default.(bool)
	// syncthingdeviceDescIsBound is the schema descriptor for is_bound field.
	syncthingdeviceDescIsBound := syncthingdeviceFields[12].Descriptor()
	// syncthingdevice.DefaultIsBound holds the default value on creation for the is_bound field.
	syncthingdevice.DefaultIsBound = syncthingdeviceDescIsBound.Default.(bool)
	// syncthingdeviceDescCloudSyncEnabled is the schema descriptor for cloud_sync_enabled field.
	syncthingdeviceDescCloudSyncEnabled := syncthingdeviceFields[13].Descriptor()
	// syncthingdevice.DefaultCloudSyncEnabled holds the default value on creation for the cloud_sync_enabled field.
	syncthingdevice.DefaultCloudSyncEnabled = syncthingdeviceDescCloudSyncEnabled.Default.(bool)
	// syncthingdeviceDescManagementAction is the schema descriptor for management_action field.
	syncthingdeviceDescManagementAction := syncthingdeviceFields[14].Descriptor()
	// syncthingdevice.ManagementActionValidator is a validator for the "management_action" field. It is called by the builders before save.
	syncthingdevice.ManagementActionValidator = syncthingdeviceDescManagementAction.Validators[0].(func(string) error)
	// syncthingdeviceDescManagementActionID is the schema descriptor for management_action_id field.
	syncthingdeviceDescManagementActionID := syncthingdeviceFields[15].Descriptor()
	// syncthingdevice.ManagementActionIDValidator is a validator for the "management_action_id" field. It is called by the builders before save.
	syncthingdevice.ManagementActionIDValidator = syncthingdeviceDescManagementActionID.Validators[0].(func(string) error)
	// syncthingdeviceDescManagementActionPayload is the schema descriptor for management_action_payload field.
	syncthingdeviceDescManagementActionPayload := syncthingdeviceFields[16].Descriptor()
	// syncthingdevice.DefaultManagementActionPayload holds the default value on creation for the management_action_payload field.
	syncthingdevice.DefaultManagementActionPayload = syncthingdeviceDescManagementActionPayload.Default.(map[string]interface{})
	taskMixin := schema.Task{}.Mixin()
	taskMixinHooks0 := taskMixin[0].Hooks()
	task.Hooks[0] = taskMixinHooks0[0]
	taskMixinInters0 := taskMixin[0].Interceptors()
	task.Interceptors[0] = taskMixinInters0[0]
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskMixinFields0[0].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskMixinFields0[1].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinHooks0 := userMixin[0].Hooks()
	user.Hooks[0] = userMixinHooks0[0]
	userMixinInters0 := userMixin[0].Interceptors()
	user.Interceptors[0] = userMixinInters0[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescNick is the schema descriptor for nick field.
	userDescNick := userFields[2].Descriptor()
	// user.NickValidator is a validator for the "nick" field. It is called by the builders before save.
	user.NickValidator = userDescNick.Validators[0].(func(string) error)
	// userDescStorage is the schema descriptor for storage field.
	userDescStorage := userFields[5].Descriptor()
	// user.DefaultStorage holds the default value on creation for the storage field.
	user.DefaultStorage = userDescStorage.Default.(int64)
	// userDescSettings is the schema descriptor for settings field.
	userDescSettings := userFields[8].Descriptor()
	// user.DefaultSettings holds the default value on creation for the settings field.
	user.DefaultSettings = userDescSettings.Default.(*types.UserSetting)
}

const (
	Version = "v0.13.0"                                         // Version of ent codegen.
	Sum     = "h1:DclxWczaCpyiKn6ZWVcJjq1zIKtJ11iNKy+08lNYsJE=" // Sum of ent codegen.
)
