// Code generated by ent, DO NOT EDIT.

package externalidentity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldDeletedAt, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldProvider, v))
}

// Issuer applies equality check predicate on the "issuer" field. It's identical to IssuerEQ.
func Issuer(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldIssuer, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldSubject, v))
}

// ExternalUserID applies equality check predicate on the "external_user_id" field. It's identical to ExternalUserIDEQ.
func ExternalUserID(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldExternalUserID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldTenantID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldDepartmentID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldEmail, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldUsername, v))
}

// Nickname applies equality check predicate on the "nickname" field. It's identical to NicknameEQ.
func Nickname(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldNickname, v))
}

// Avatar applies equality check predicate on the "avatar" field. It's identical to AvatarEQ.
func Avatar(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldAvatar, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotNull(FieldDeletedAt))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldProvider, v))
}

// IssuerEQ applies the EQ predicate on the "issuer" field.
func IssuerEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldIssuer, v))
}

// IssuerNEQ applies the NEQ predicate on the "issuer" field.
func IssuerNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldIssuer, v))
}

// IssuerIn applies the In predicate on the "issuer" field.
func IssuerIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldIssuer, vs...))
}

// IssuerNotIn applies the NotIn predicate on the "issuer" field.
func IssuerNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldIssuer, vs...))
}

// IssuerGT applies the GT predicate on the "issuer" field.
func IssuerGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldIssuer, v))
}

// IssuerGTE applies the GTE predicate on the "issuer" field.
func IssuerGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldIssuer, v))
}

// IssuerLT applies the LT predicate on the "issuer" field.
func IssuerLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldIssuer, v))
}

// IssuerLTE applies the LTE predicate on the "issuer" field.
func IssuerLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldIssuer, v))
}

// IssuerContains applies the Contains predicate on the "issuer" field.
func IssuerContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldIssuer, v))
}

// IssuerHasPrefix applies the HasPrefix predicate on the "issuer" field.
func IssuerHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldIssuer, v))
}

// IssuerHasSuffix applies the HasSuffix predicate on the "issuer" field.
func IssuerHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldIssuer, v))
}

// IssuerEqualFold applies the EqualFold predicate on the "issuer" field.
func IssuerEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldIssuer, v))
}

// IssuerContainsFold applies the ContainsFold predicate on the "issuer" field.
func IssuerContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldIssuer, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldSubject, v))
}

// ExternalUserIDEQ applies the EQ predicate on the "external_user_id" field.
func ExternalUserIDEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldExternalUserID, v))
}

// ExternalUserIDNEQ applies the NEQ predicate on the "external_user_id" field.
func ExternalUserIDNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldExternalUserID, v))
}

// ExternalUserIDIn applies the In predicate on the "external_user_id" field.
func ExternalUserIDIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldExternalUserID, vs...))
}

// ExternalUserIDNotIn applies the NotIn predicate on the "external_user_id" field.
func ExternalUserIDNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldExternalUserID, vs...))
}

// ExternalUserIDGT applies the GT predicate on the "external_user_id" field.
func ExternalUserIDGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldExternalUserID, v))
}

// ExternalUserIDGTE applies the GTE predicate on the "external_user_id" field.
func ExternalUserIDGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldExternalUserID, v))
}

// ExternalUserIDLT applies the LT predicate on the "external_user_id" field.
func ExternalUserIDLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldExternalUserID, v))
}

// ExternalUserIDLTE applies the LTE predicate on the "external_user_id" field.
func ExternalUserIDLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldExternalUserID, v))
}

// ExternalUserIDContains applies the Contains predicate on the "external_user_id" field.
func ExternalUserIDContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldExternalUserID, v))
}

// ExternalUserIDHasPrefix applies the HasPrefix predicate on the "external_user_id" field.
func ExternalUserIDHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldExternalUserID, v))
}

// ExternalUserIDHasSuffix applies the HasSuffix predicate on the "external_user_id" field.
func ExternalUserIDHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldExternalUserID, v))
}

// ExternalUserIDIsNil applies the IsNil predicate on the "external_user_id" field.
func ExternalUserIDIsNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIsNull(FieldExternalUserID))
}

// ExternalUserIDNotNil applies the NotNil predicate on the "external_user_id" field.
func ExternalUserIDNotNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotNull(FieldExternalUserID))
}

// ExternalUserIDEqualFold applies the EqualFold predicate on the "external_user_id" field.
func ExternalUserIDEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldExternalUserID, v))
}

// ExternalUserIDContainsFold applies the ContainsFold predicate on the "external_user_id" field.
func ExternalUserIDContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldExternalUserID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotNull(FieldTenantID))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldTenantID, v))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// DepartmentIDGT applies the GT predicate on the "department_id" field.
func DepartmentIDGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldDepartmentID, v))
}

// DepartmentIDGTE applies the GTE predicate on the "department_id" field.
func DepartmentIDGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldDepartmentID, v))
}

// DepartmentIDLT applies the LT predicate on the "department_id" field.
func DepartmentIDLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldDepartmentID, v))
}

// DepartmentIDLTE applies the LTE predicate on the "department_id" field.
func DepartmentIDLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldDepartmentID, v))
}

// DepartmentIDContains applies the Contains predicate on the "department_id" field.
func DepartmentIDContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldDepartmentID, v))
}

// DepartmentIDHasPrefix applies the HasPrefix predicate on the "department_id" field.
func DepartmentIDHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldDepartmentID, v))
}

// DepartmentIDHasSuffix applies the HasSuffix predicate on the "department_id" field.
func DepartmentIDHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldDepartmentID, v))
}

// DepartmentIDIsNil applies the IsNil predicate on the "department_id" field.
func DepartmentIDIsNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIsNull(FieldDepartmentID))
}

// DepartmentIDNotNil applies the NotNil predicate on the "department_id" field.
func DepartmentIDNotNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotNull(FieldDepartmentID))
}

// DepartmentIDEqualFold applies the EqualFold predicate on the "department_id" field.
func DepartmentIDEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldDepartmentID, v))
}

// DepartmentIDContainsFold applies the ContainsFold predicate on the "department_id" field.
func DepartmentIDContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldDepartmentID, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldEmail, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldUsername, v))
}

// NicknameEQ applies the EQ predicate on the "nickname" field.
func NicknameEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldNickname, v))
}

// NicknameNEQ applies the NEQ predicate on the "nickname" field.
func NicknameNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldNickname, v))
}

// NicknameIn applies the In predicate on the "nickname" field.
func NicknameIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldNickname, vs...))
}

// NicknameNotIn applies the NotIn predicate on the "nickname" field.
func NicknameNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldNickname, vs...))
}

// NicknameGT applies the GT predicate on the "nickname" field.
func NicknameGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldNickname, v))
}

// NicknameGTE applies the GTE predicate on the "nickname" field.
func NicknameGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldNickname, v))
}

// NicknameLT applies the LT predicate on the "nickname" field.
func NicknameLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldNickname, v))
}

// NicknameLTE applies the LTE predicate on the "nickname" field.
func NicknameLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldNickname, v))
}

// NicknameContains applies the Contains predicate on the "nickname" field.
func NicknameContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldNickname, v))
}

// NicknameHasPrefix applies the HasPrefix predicate on the "nickname" field.
func NicknameHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldNickname, v))
}

// NicknameHasSuffix applies the HasSuffix predicate on the "nickname" field.
func NicknameHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldNickname, v))
}

// NicknameIsNil applies the IsNil predicate on the "nickname" field.
func NicknameIsNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIsNull(FieldNickname))
}

// NicknameNotNil applies the NotNil predicate on the "nickname" field.
func NicknameNotNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotNull(FieldNickname))
}

// NicknameEqualFold applies the EqualFold predicate on the "nickname" field.
func NicknameEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldNickname, v))
}

// NicknameContainsFold applies the ContainsFold predicate on the "nickname" field.
func NicknameContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldNickname, v))
}

// AvatarEQ applies the EQ predicate on the "avatar" field.
func AvatarEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldAvatar, v))
}

// AvatarNEQ applies the NEQ predicate on the "avatar" field.
func AvatarNEQ(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldAvatar, v))
}

// AvatarIn applies the In predicate on the "avatar" field.
func AvatarIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldAvatar, vs...))
}

// AvatarNotIn applies the NotIn predicate on the "avatar" field.
func AvatarNotIn(vs ...string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldAvatar, vs...))
}

// AvatarGT applies the GT predicate on the "avatar" field.
func AvatarGT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGT(FieldAvatar, v))
}

// AvatarGTE applies the GTE predicate on the "avatar" field.
func AvatarGTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldGTE(FieldAvatar, v))
}

// AvatarLT applies the LT predicate on the "avatar" field.
func AvatarLT(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLT(FieldAvatar, v))
}

// AvatarLTE applies the LTE predicate on the "avatar" field.
func AvatarLTE(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldLTE(FieldAvatar, v))
}

// AvatarContains applies the Contains predicate on the "avatar" field.
func AvatarContains(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContains(FieldAvatar, v))
}

// AvatarHasPrefix applies the HasPrefix predicate on the "avatar" field.
func AvatarHasPrefix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasPrefix(FieldAvatar, v))
}

// AvatarHasSuffix applies the HasSuffix predicate on the "avatar" field.
func AvatarHasSuffix(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldHasSuffix(FieldAvatar, v))
}

// AvatarIsNil applies the IsNil predicate on the "avatar" field.
func AvatarIsNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIsNull(FieldAvatar))
}

// AvatarNotNil applies the NotNil predicate on the "avatar" field.
func AvatarNotNil() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotNull(FieldAvatar))
}

// AvatarEqualFold applies the EqualFold predicate on the "avatar" field.
func AvatarEqualFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEqualFold(FieldAvatar, v))
}

// AvatarContainsFold applies the ContainsFold predicate on the "avatar" field.
func AvatarContainsFold(v string) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldContainsFold(FieldAvatar, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.FieldNotIn(FieldUserID, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ExternalIdentity {
	return predicate.ExternalIdentity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExternalIdentity) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExternalIdentity) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExternalIdentity) predicate.ExternalIdentity {
	return predicate.ExternalIdentity(sql.NotPredicates(p))
}
