// Code generated by ent, DO NOT EDIT.

package syncthingdevice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldDeletedAt, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldOwnerID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldDeviceID, v))
}

// ShortID applies equality check predicate on the "short_id" field. It's identical to ShortIDEQ.
func ShortID(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldShortID, v))
}

// LastIP applies equality check predicate on the "last_ip" field. It's identical to LastIPEQ.
func LastIP(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldLastIP, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldAPIKey, v))
}

// BindURI applies equality check predicate on the "bind_uri" field. It's identical to BindURIEQ.
func BindURI(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldBindURI, v))
}

// ClientVersion applies equality check predicate on the "client_version" field. It's identical to ClientVersionEQ.
func ClientVersion(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldClientVersion, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldPlatform, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSyncAt applies equality check predicate on the "last_sync_at" field. It's identical to LastSyncAtEQ.
func LastSyncAt(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldLastSyncAt, v))
}

// Online applies equality check predicate on the "online" field. It's identical to OnlineEQ.
func Online(v bool) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldOnline, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotNull(FieldDeletedAt))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...int) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldOwnerID, vs...))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContainsFold(FieldDeviceID, v))
}

// ShortIDEQ applies the EQ predicate on the "short_id" field.
func ShortIDEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldShortID, v))
}

// ShortIDNEQ applies the NEQ predicate on the "short_id" field.
func ShortIDNEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldShortID, v))
}

// ShortIDIn applies the In predicate on the "short_id" field.
func ShortIDIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldShortID, vs...))
}

// ShortIDNotIn applies the NotIn predicate on the "short_id" field.
func ShortIDNotIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldShortID, vs...))
}

// ShortIDGT applies the GT predicate on the "short_id" field.
func ShortIDGT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldShortID, v))
}

// ShortIDGTE applies the GTE predicate on the "short_id" field.
func ShortIDGTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldShortID, v))
}

// ShortIDLT applies the LT predicate on the "short_id" field.
func ShortIDLT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldShortID, v))
}

// ShortIDLTE applies the LTE predicate on the "short_id" field.
func ShortIDLTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldShortID, v))
}

// ShortIDContains applies the Contains predicate on the "short_id" field.
func ShortIDContains(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContains(FieldShortID, v))
}

// ShortIDHasPrefix applies the HasPrefix predicate on the "short_id" field.
func ShortIDHasPrefix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasPrefix(FieldShortID, v))
}

// ShortIDHasSuffix applies the HasSuffix predicate on the "short_id" field.
func ShortIDHasSuffix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasSuffix(FieldShortID, v))
}

// ShortIDIsNil applies the IsNil predicate on the "short_id" field.
func ShortIDIsNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIsNull(FieldShortID))
}

// ShortIDNotNil applies the NotNil predicate on the "short_id" field.
func ShortIDNotNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotNull(FieldShortID))
}

// ShortIDEqualFold applies the EqualFold predicate on the "short_id" field.
func ShortIDEqualFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEqualFold(FieldShortID, v))
}

// ShortIDContainsFold applies the ContainsFold predicate on the "short_id" field.
func ShortIDContainsFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContainsFold(FieldShortID, v))
}

// LastIPEQ applies the EQ predicate on the "last_ip" field.
func LastIPEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldLastIP, v))
}

// LastIPNEQ applies the NEQ predicate on the "last_ip" field.
func LastIPNEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldLastIP, v))
}

// LastIPIn applies the In predicate on the "last_ip" field.
func LastIPIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldLastIP, vs...))
}

// LastIPNotIn applies the NotIn predicate on the "last_ip" field.
func LastIPNotIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldLastIP, vs...))
}

// LastIPGT applies the GT predicate on the "last_ip" field.
func LastIPGT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldLastIP, v))
}

// LastIPGTE applies the GTE predicate on the "last_ip" field.
func LastIPGTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldLastIP, v))
}

// LastIPLT applies the LT predicate on the "last_ip" field.
func LastIPLT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldLastIP, v))
}

// LastIPLTE applies the LTE predicate on the "last_ip" field.
func LastIPLTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldLastIP, v))
}

// LastIPContains applies the Contains predicate on the "last_ip" field.
func LastIPContains(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContains(FieldLastIP, v))
}

// LastIPHasPrefix applies the HasPrefix predicate on the "last_ip" field.
func LastIPHasPrefix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasPrefix(FieldLastIP, v))
}

// LastIPHasSuffix applies the HasSuffix predicate on the "last_ip" field.
func LastIPHasSuffix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasSuffix(FieldLastIP, v))
}

// LastIPIsNil applies the IsNil predicate on the "last_ip" field.
func LastIPIsNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIsNull(FieldLastIP))
}

// LastIPNotNil applies the NotNil predicate on the "last_ip" field.
func LastIPNotNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotNull(FieldLastIP))
}

// LastIPEqualFold applies the EqualFold predicate on the "last_ip" field.
func LastIPEqualFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEqualFold(FieldLastIP, v))
}

// LastIPContainsFold applies the ContainsFold predicate on the "last_ip" field.
func LastIPContainsFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContainsFold(FieldLastIP, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyIsNil applies the IsNil predicate on the "api_key" field.
func APIKeyIsNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIsNull(FieldAPIKey))
}

// APIKeyNotNil applies the NotNil predicate on the "api_key" field.
func APIKeyNotNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotNull(FieldAPIKey))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContainsFold(FieldAPIKey, v))
}

// JSONRawIsNil applies the IsNil predicate on the "json_raw" field.
func JSONRawIsNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIsNull(FieldJSONRaw))
}

// JSONRawNotNil applies the NotNil predicate on the "json_raw" field.
func JSONRawNotNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotNull(FieldJSONRaw))
}

// BindURIEQ applies the EQ predicate on the "bind_uri" field.
func BindURIEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldBindURI, v))
}

// BindURINEQ applies the NEQ predicate on the "bind_uri" field.
func BindURINEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldBindURI, v))
}

// BindURIIn applies the In predicate on the "bind_uri" field.
func BindURIIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldBindURI, vs...))
}

// BindURINotIn applies the NotIn predicate on the "bind_uri" field.
func BindURINotIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldBindURI, vs...))
}

// BindURIGT applies the GT predicate on the "bind_uri" field.
func BindURIGT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldBindURI, v))
}

// BindURIGTE applies the GTE predicate on the "bind_uri" field.
func BindURIGTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldBindURI, v))
}

// BindURILT applies the LT predicate on the "bind_uri" field.
func BindURILT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldBindURI, v))
}

// BindURILTE applies the LTE predicate on the "bind_uri" field.
func BindURILTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldBindURI, v))
}

// BindURIContains applies the Contains predicate on the "bind_uri" field.
func BindURIContains(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContains(FieldBindURI, v))
}

// BindURIHasPrefix applies the HasPrefix predicate on the "bind_uri" field.
func BindURIHasPrefix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasPrefix(FieldBindURI, v))
}

// BindURIHasSuffix applies the HasSuffix predicate on the "bind_uri" field.
func BindURIHasSuffix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasSuffix(FieldBindURI, v))
}

// BindURIIsNil applies the IsNil predicate on the "bind_uri" field.
func BindURIIsNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIsNull(FieldBindURI))
}

// BindURINotNil applies the NotNil predicate on the "bind_uri" field.
func BindURINotNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotNull(FieldBindURI))
}

// BindURIEqualFold applies the EqualFold predicate on the "bind_uri" field.
func BindURIEqualFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEqualFold(FieldBindURI, v))
}

// BindURIContainsFold applies the ContainsFold predicate on the "bind_uri" field.
func BindURIContainsFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContainsFold(FieldBindURI, v))
}

// ClientVersionEQ applies the EQ predicate on the "client_version" field.
func ClientVersionEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldClientVersion, v))
}

// ClientVersionNEQ applies the NEQ predicate on the "client_version" field.
func ClientVersionNEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldClientVersion, v))
}

// ClientVersionIn applies the In predicate on the "client_version" field.
func ClientVersionIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldClientVersion, vs...))
}

// ClientVersionNotIn applies the NotIn predicate on the "client_version" field.
func ClientVersionNotIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldClientVersion, vs...))
}

// ClientVersionGT applies the GT predicate on the "client_version" field.
func ClientVersionGT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldClientVersion, v))
}

// ClientVersionGTE applies the GTE predicate on the "client_version" field.
func ClientVersionGTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldClientVersion, v))
}

// ClientVersionLT applies the LT predicate on the "client_version" field.
func ClientVersionLT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldClientVersion, v))
}

// ClientVersionLTE applies the LTE predicate on the "client_version" field.
func ClientVersionLTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldClientVersion, v))
}

// ClientVersionContains applies the Contains predicate on the "client_version" field.
func ClientVersionContains(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContains(FieldClientVersion, v))
}

// ClientVersionHasPrefix applies the HasPrefix predicate on the "client_version" field.
func ClientVersionHasPrefix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasPrefix(FieldClientVersion, v))
}

// ClientVersionHasSuffix applies the HasSuffix predicate on the "client_version" field.
func ClientVersionHasSuffix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasSuffix(FieldClientVersion, v))
}

// ClientVersionIsNil applies the IsNil predicate on the "client_version" field.
func ClientVersionIsNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIsNull(FieldClientVersion))
}

// ClientVersionNotNil applies the NotNil predicate on the "client_version" field.
func ClientVersionNotNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotNull(FieldClientVersion))
}

// ClientVersionEqualFold applies the EqualFold predicate on the "client_version" field.
func ClientVersionEqualFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEqualFold(FieldClientVersion, v))
}

// ClientVersionContainsFold applies the ContainsFold predicate on the "client_version" field.
func ClientVersionContainsFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContainsFold(FieldClientVersion, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformIsNil applies the IsNil predicate on the "platform" field.
func PlatformIsNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIsNull(FieldPlatform))
}

// PlatformNotNil applies the NotNil predicate on the "platform" field.
func PlatformNotNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotNull(FieldPlatform))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldContainsFold(FieldPlatform, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotNull(FieldLastSeenAt))
}

// LastSyncAtEQ applies the EQ predicate on the "last_sync_at" field.
func LastSyncAtEQ(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncAtNEQ applies the NEQ predicate on the "last_sync_at" field.
func LastSyncAtNEQ(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldLastSyncAt, v))
}

// LastSyncAtIn applies the In predicate on the "last_sync_at" field.
func LastSyncAtIn(vs ...time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIn(FieldLastSyncAt, vs...))
}

// LastSyncAtNotIn applies the NotIn predicate on the "last_sync_at" field.
func LastSyncAtNotIn(vs ...time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotIn(FieldLastSyncAt, vs...))
}

// LastSyncAtGT applies the GT predicate on the "last_sync_at" field.
func LastSyncAtGT(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGT(FieldLastSyncAt, v))
}

// LastSyncAtGTE applies the GTE predicate on the "last_sync_at" field.
func LastSyncAtGTE(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldGTE(FieldLastSyncAt, v))
}

// LastSyncAtLT applies the LT predicate on the "last_sync_at" field.
func LastSyncAtLT(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLT(FieldLastSyncAt, v))
}

// LastSyncAtLTE applies the LTE predicate on the "last_sync_at" field.
func LastSyncAtLTE(v time.Time) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldLTE(FieldLastSyncAt, v))
}

// LastSyncAtIsNil applies the IsNil predicate on the "last_sync_at" field.
func LastSyncAtIsNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldIsNull(FieldLastSyncAt))
}

// LastSyncAtNotNil applies the NotNil predicate on the "last_sync_at" field.
func LastSyncAtNotNil() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNotNull(FieldLastSyncAt))
}

// OnlineEQ applies the EQ predicate on the "online" field.
func OnlineEQ(v bool) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldEQ(FieldOnline, v))
}

// OnlineNEQ applies the NEQ predicate on the "online" field.
func OnlineNEQ(v bool) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.FieldNEQ(FieldOnline, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.SyncthingDevice {
	return predicate.SyncthingDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SyncthingDevice) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SyncthingDevice) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SyncthingDevice) predicate.SyncthingDevice {
	return predicate.SyncthingDevice(sql.NotPredicates(p))
}
