// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/auditlog"
	"github.com/cloudreve/Cloudreve/v4/ent/entity"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/share"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// AuditLogCreate is the builder for creating a AuditLog entity.
type AuditLogCreate struct {
	config
	mutation *AuditLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (alc *AuditLogCreate) SetCreatedAt(t time.Time) *AuditLogCreate {
	alc.mutation.SetCreatedAt(t)
	return alc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableCreatedAt(t *time.Time) *AuditLogCreate {
	if t != nil {
		alc.SetCreatedAt(*t)
	}
	return alc
}

// SetUpdatedAt sets the "updated_at" field.
func (alc *AuditLogCreate) SetUpdatedAt(t time.Time) *AuditLogCreate {
	alc.mutation.SetUpdatedAt(t)
	return alc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableUpdatedAt(t *time.Time) *AuditLogCreate {
	if t != nil {
		alc.SetUpdatedAt(*t)
	}
	return alc
}

// SetDeletedAt sets the "deleted_at" field.
func (alc *AuditLogCreate) SetDeletedAt(t time.Time) *AuditLogCreate {
	alc.mutation.SetDeletedAt(t)
	return alc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableDeletedAt(t *time.Time) *AuditLogCreate {
	if t != nil {
		alc.SetDeletedAt(*t)
	}
	return alc
}

// SetType sets the "type" field.
func (alc *AuditLogCreate) SetType(i int) *AuditLogCreate {
	alc.mutation.SetType(i)
	return alc
}

// SetCorrelationID sets the "correlation_id" field.
func (alc *AuditLogCreate) SetCorrelationID(s string) *AuditLogCreate {
	alc.mutation.SetCorrelationID(s)
	return alc
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableCorrelationID(s *string) *AuditLogCreate {
	if s != nil {
		alc.SetCorrelationID(*s)
	}
	return alc
}

// SetIP sets the "ip" field.
func (alc *AuditLogCreate) SetIP(s string) *AuditLogCreate {
	alc.mutation.SetIP(s)
	return alc
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableIP(s *string) *AuditLogCreate {
	if s != nil {
		alc.SetIP(*s)
	}
	return alc
}

// SetContent sets the "content" field.
func (alc *AuditLogCreate) SetContent(m map[string]interface{}) *AuditLogCreate {
	alc.mutation.SetContent(m)
	return alc
}

// SetUserID sets the "user_id" field.
func (alc *AuditLogCreate) SetUserID(i int) *AuditLogCreate {
	alc.mutation.SetUserID(i)
	return alc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableUserID(i *int) *AuditLogCreate {
	if i != nil {
		alc.SetUserID(*i)
	}
	return alc
}

// SetFileID sets the "file_id" field.
func (alc *AuditLogCreate) SetFileID(i int) *AuditLogCreate {
	alc.mutation.SetFileID(i)
	return alc
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableFileID(i *int) *AuditLogCreate {
	if i != nil {
		alc.SetFileID(*i)
	}
	return alc
}

// SetEntityID sets the "entity_id" field.
func (alc *AuditLogCreate) SetEntityID(i int) *AuditLogCreate {
	alc.mutation.SetEntityID(i)
	return alc
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableEntityID(i *int) *AuditLogCreate {
	if i != nil {
		alc.SetEntityID(*i)
	}
	return alc
}

// SetShareID sets the "share_id" field.
func (alc *AuditLogCreate) SetShareID(i int) *AuditLogCreate {
	alc.mutation.SetShareID(i)
	return alc
}

// SetNillableShareID sets the "share_id" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableShareID(i *int) *AuditLogCreate {
	if i != nil {
		alc.SetShareID(*i)
	}
	return alc
}

// SetUser sets the "user" edge to the User entity.
func (alc *AuditLogCreate) SetUser(u *User) *AuditLogCreate {
	return alc.SetUserID(u.ID)
}

// SetFile sets the "file" edge to the File entity.
func (alc *AuditLogCreate) SetFile(f *File) *AuditLogCreate {
	return alc.SetFileID(f.ID)
}

// SetEntity sets the "entity" edge to the Entity entity.
func (alc *AuditLogCreate) SetEntity(e *Entity) *AuditLogCreate {
	return alc.SetEntityID(e.ID)
}

// SetShare sets the "share" edge to the Share entity.
func (alc *AuditLogCreate) SetShare(s *Share) *AuditLogCreate {
	return alc.SetShareID(s.ID)
}

// Mutation returns the AuditLogMutation object of the builder.
func (alc *AuditLogCreate) Mutation() *AuditLogMutation {
	return alc.mutation
}

// Save creates the AuditLog in the database.
func (alc *AuditLogCreate) Save(ctx context.Context) (*AuditLog, error) {
	if err := alc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, alc.sqlSave, alc.mutation, alc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (alc *AuditLogCreate) SaveX(ctx context.Context) *AuditLog {
	v, err := alc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (alc *AuditLogCreate) Exec(ctx context.Context) error {
	_, err := alc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alc *AuditLogCreate) ExecX(ctx context.Context) {
	if err := alc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (alc *AuditLogCreate) defaults() error {
	if _, ok := alc.mutation.CreatedAt(); !ok {
		if auditlog.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized auditlog.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := auditlog.DefaultCreatedAt()
		alc.mutation.SetCreatedAt(v)
	}
	if _, ok := alc.mutation.UpdatedAt(); !ok {
		if auditlog.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized auditlog.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := auditlog.DefaultUpdatedAt()
		alc.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (alc *AuditLogCreate) check() error {
	if _, ok := alc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuditLog.created_at"`)}
	}
	if _, ok := alc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuditLog.updated_at"`)}
	}
	if _, ok := alc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "AuditLog.type"`)}
	}
	return nil
}

func (alc *AuditLogCreate) sqlSave(ctx context.Context) (*AuditLog, error) {
	if err := alc.check(); err != nil {
		return nil, err
	}
	_node, _spec := alc.createSpec()
	if err := sqlgraph.CreateNode(ctx, alc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	alc.mutation.id = &_node.ID
	alc.mutation.done = true
	return _node, nil
}

func (alc *AuditLogCreate) createSpec() (*AuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditLog{config: alc.config}
		_spec = sqlgraph.NewCreateSpec(auditlog.Table, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	)

	if id, ok := alc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = alc.conflict
	if value, ok := alc.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := alc.mutation.UpdatedAt(); ok {
		_spec.SetField(auditlog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := alc.mutation.DeletedAt(); ok {
		_spec.SetField(auditlog.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := alc.mutation.GetType(); ok {
		_spec.SetField(auditlog.FieldType, field.TypeInt, value)
		_node.Type = value
	}
	if value, ok := alc.mutation.CorrelationID(); ok {
		_spec.SetField(auditlog.FieldCorrelationID, field.TypeString, value)
		_node.CorrelationID = value
	}
	if value, ok := alc.mutation.IP(); ok {
		_spec.SetField(auditlog.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := alc.mutation.Content(); ok {
		_spec.SetField(auditlog.FieldContent, field.TypeJSON, value)
		_node.Content = value
	}
	if nodes := alc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.UserTable,
			Columns: []string{auditlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := alc.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.FileTable,
			Columns: []string{auditlog.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := alc.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.EntityTable,
			Columns: []string{auditlog.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EntityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := alc.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ShareTable,
			Columns: []string{auditlog.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShareID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditLog.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (alc *AuditLogCreate) OnConflict(opts ...sql.ConflictOption) *AuditLogUpsertOne {
	alc.conflict = opts
	return &AuditLogUpsertOne{
		create: alc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (alc *AuditLogCreate) OnConflictColumns(columns ...string) *AuditLogUpsertOne {
	alc.conflict = append(alc.conflict, sql.ConflictColumns(columns...))
	return &AuditLogUpsertOne{
		create: alc,
	}
}

type (
	// AuditLogUpsertOne is the builder for "upsert"-ing
	//  one AuditLog node.
	AuditLogUpsertOne struct {
		create *AuditLogCreate
	}

	// AuditLogUpsert is the "OnConflict" setter.
	AuditLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AuditLogUpsert) SetUpdatedAt(v time.Time) *AuditLogUpsert {
	u.Set(auditlog.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateUpdatedAt() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AuditLogUpsert) SetDeletedAt(v time.Time) *AuditLogUpsert {
	u.Set(auditlog.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateDeletedAt() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AuditLogUpsert) ClearDeletedAt() *AuditLogUpsert {
	u.SetNull(auditlog.FieldDeletedAt)
	return u
}

// SetType sets the "type" field.
func (u *AuditLogUpsert) SetType(v int) *AuditLogUpsert {
	u.Set(auditlog.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateType() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldType)
	return u
}

// AddType adds v to the "type" field.
func (u *AuditLogUpsert) AddType(v int) *AuditLogUpsert {
	u.Add(auditlog.FieldType, v)
	return u
}

// SetCorrelationID sets the "correlation_id" field.
func (u *AuditLogUpsert) SetCorrelationID(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldCorrelationID, v)
	return u
}

// UpdateCorrelationID sets the "correlation_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateCorrelationID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldCorrelationID)
	return u
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (u *AuditLogUpsert) ClearCorrelationID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldCorrelationID)
	return u
}

// SetIP sets the "ip" field.
func (u *AuditLogUpsert) SetIP(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateIP() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldIP)
	return u
}

// ClearIP clears the value of the "ip" field.
func (u *AuditLogUpsert) ClearIP() *AuditLogUpsert {
	u.SetNull(auditlog.FieldIP)
	return u
}

// SetContent sets the "content" field.
func (u *AuditLogUpsert) SetContent(v map[string]interface{}) *AuditLogUpsert {
	u.Set(auditlog.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateContent() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *AuditLogUpsert) ClearContent() *AuditLogUpsert {
	u.SetNull(auditlog.FieldContent)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AuditLogUpsert) SetUserID(v int) *AuditLogUpsert {
	u.Set(auditlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateUserID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *AuditLogUpsert) ClearUserID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldUserID)
	return u
}

// SetFileID sets the "file_id" field.
func (u *AuditLogUpsert) SetFileID(v int) *AuditLogUpsert {
	u.Set(auditlog.FieldFileID, v)
	return u
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateFileID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldFileID)
	return u
}

// ClearFileID clears the value of the "file_id" field.
func (u *AuditLogUpsert) ClearFileID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldFileID)
	return u
}

// SetEntityID sets the "entity_id" field.
func (u *AuditLogUpsert) SetEntityID(v int) *AuditLogUpsert {
	u.Set(auditlog.FieldEntityID, v)
	return u
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateEntityID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldEntityID)
	return u
}

// ClearEntityID clears the value of the "entity_id" field.
func (u *AuditLogUpsert) ClearEntityID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldEntityID)
	return u
}

// SetShareID sets the "share_id" field.
func (u *AuditLogUpsert) SetShareID(v int) *AuditLogUpsert {
	u.Set(auditlog.FieldShareID, v)
	return u
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateShareID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldShareID)
	return u
}

// ClearShareID clears the value of the "share_id" field.
func (u *AuditLogUpsert) ClearShareID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldShareID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuditLogUpsertOne) UpdateNewValues() *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(auditlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuditLogUpsertOne) Ignore() *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditLogUpsertOne) DoNothing() *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditLogCreate.OnConflict
// documentation for more info.
func (u *AuditLogUpsertOne) Update(set func(*AuditLogUpsert)) *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuditLogUpsertOne) SetUpdatedAt(v time.Time) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateUpdatedAt() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AuditLogUpsertOne) SetDeletedAt(v time.Time) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateDeletedAt() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AuditLogUpsertOne) ClearDeletedAt() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearDeletedAt()
	})
}

// SetType sets the "type" field.
func (u *AuditLogUpsertOne) SetType(v int) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *AuditLogUpsertOne) AddType(v int) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateType() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateType()
	})
}

// SetCorrelationID sets the "correlation_id" field.
func (u *AuditLogUpsertOne) SetCorrelationID(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetCorrelationID(v)
	})
}

// UpdateCorrelationID sets the "correlation_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateCorrelationID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateCorrelationID()
	})
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (u *AuditLogUpsertOne) ClearCorrelationID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearCorrelationID()
	})
}

// SetIP sets the "ip" field.
func (u *AuditLogUpsertOne) SetIP(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateIP() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *AuditLogUpsertOne) ClearIP() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearIP()
	})
}

// SetContent sets the "content" field.
func (u *AuditLogUpsertOne) SetContent(v map[string]interface{}) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateContent() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *AuditLogUpsertOne) ClearContent() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearContent()
	})
}

// SetUserID sets the "user_id" field.
func (u *AuditLogUpsertOne) SetUserID(v int) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateUserID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *AuditLogUpsertOne) ClearUserID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetFileID sets the "file_id" field.
func (u *AuditLogUpsertOne) SetFileID(v int) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateFileID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateFileID()
	})
}

// ClearFileID clears the value of the "file_id" field.
func (u *AuditLogUpsertOne) ClearFileID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearFileID()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *AuditLogUpsertOne) SetEntityID(v int) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateEntityID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateEntityID()
	})
}

// ClearEntityID clears the value of the "entity_id" field.
func (u *AuditLogUpsertOne) ClearEntityID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearEntityID()
	})
}

// SetShareID sets the "share_id" field.
func (u *AuditLogUpsertOne) SetShareID(v int) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetShareID(v)
	})
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateShareID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateShareID()
	})
}

// ClearShareID clears the value of the "share_id" field.
func (u *AuditLogUpsertOne) ClearShareID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearShareID()
	})
}

// Exec executes the query.
func (u *AuditLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuditLogUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuditLogUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *AuditLogCreate) SetRawID(t int) *AuditLogCreate {
	m.mutation.SetRawID(t)
	return m
}

// AuditLogCreateBulk is the builder for creating many AuditLog entities in bulk.
type AuditLogCreateBulk struct {
	config
	err      error
	builders []*AuditLogCreate
	conflict []sql.ConflictOption
}

// Save creates the AuditLog entities in the database.
func (alcb *AuditLogCreateBulk) Save(ctx context.Context) ([]*AuditLog, error) {
	if alcb.err != nil {
		return nil, alcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(alcb.builders))
	nodes := make([]*AuditLog, len(alcb.builders))
	mutators := make([]Mutator, len(alcb.builders))
	for i := range alcb.builders {
		func(i int, root context.Context) {
			builder := alcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, alcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = alcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, alcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, alcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (alcb *AuditLogCreateBulk) SaveX(ctx context.Context) []*AuditLog {
	v, err := alcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (alcb *AuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := alcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alcb *AuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := alcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (alcb *AuditLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuditLogUpsertBulk {
	alcb.conflict = opts
	return &AuditLogUpsertBulk{
		create: alcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (alcb *AuditLogCreateBulk) OnConflictColumns(columns ...string) *AuditLogUpsertBulk {
	alcb.conflict = append(alcb.conflict, sql.ConflictColumns(columns...))
	return &AuditLogUpsertBulk{
		create: alcb,
	}
}

// AuditLogUpsertBulk is the builder for "upsert"-ing
// a bulk of AuditLog nodes.
type AuditLogUpsertBulk struct {
	create *AuditLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuditLogUpsertBulk) UpdateNewValues() *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(auditlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuditLogUpsertBulk) Ignore() *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditLogUpsertBulk) DoNothing() *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditLogCreateBulk.OnConflict
// documentation for more info.
func (u *AuditLogUpsertBulk) Update(set func(*AuditLogUpsert)) *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuditLogUpsertBulk) SetUpdatedAt(v time.Time) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateUpdatedAt() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AuditLogUpsertBulk) SetDeletedAt(v time.Time) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateDeletedAt() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AuditLogUpsertBulk) ClearDeletedAt() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearDeletedAt()
	})
}

// SetType sets the "type" field.
func (u *AuditLogUpsertBulk) SetType(v int) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *AuditLogUpsertBulk) AddType(v int) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateType() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateType()
	})
}

// SetCorrelationID sets the "correlation_id" field.
func (u *AuditLogUpsertBulk) SetCorrelationID(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetCorrelationID(v)
	})
}

// UpdateCorrelationID sets the "correlation_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateCorrelationID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateCorrelationID()
	})
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (u *AuditLogUpsertBulk) ClearCorrelationID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearCorrelationID()
	})
}

// SetIP sets the "ip" field.
func (u *AuditLogUpsertBulk) SetIP(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateIP() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *AuditLogUpsertBulk) ClearIP() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearIP()
	})
}

// SetContent sets the "content" field.
func (u *AuditLogUpsertBulk) SetContent(v map[string]interface{}) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateContent() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *AuditLogUpsertBulk) ClearContent() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearContent()
	})
}

// SetUserID sets the "user_id" field.
func (u *AuditLogUpsertBulk) SetUserID(v int) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateUserID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *AuditLogUpsertBulk) ClearUserID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetFileID sets the "file_id" field.
func (u *AuditLogUpsertBulk) SetFileID(v int) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateFileID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateFileID()
	})
}

// ClearFileID clears the value of the "file_id" field.
func (u *AuditLogUpsertBulk) ClearFileID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearFileID()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *AuditLogUpsertBulk) SetEntityID(v int) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateEntityID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateEntityID()
	})
}

// ClearEntityID clears the value of the "entity_id" field.
func (u *AuditLogUpsertBulk) ClearEntityID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearEntityID()
	})
}

// SetShareID sets the "share_id" field.
func (u *AuditLogUpsertBulk) SetShareID(v int) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetShareID(v)
	})
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateShareID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateShareID()
	})
}

// ClearShareID clears the value of the "share_id" field.
func (u *AuditLogUpsertBulk) ClearShareID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearShareID()
	})
}

// Exec executes the query.
func (u *AuditLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuditLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
