// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/externalidentity"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ExternalIdentityDelete is the builder for deleting a ExternalIdentity entity.
type ExternalIdentityDelete struct {
	config
	hooks    []Hook
	mutation *ExternalIdentityMutation
}

// Where appends a list predicates to the ExternalIdentityDelete builder.
func (eid *ExternalIdentityDelete) Where(ps ...predicate.ExternalIdentity) *ExternalIdentityDelete {
	eid.mutation.Where(ps...)
	return eid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (eid *ExternalIdentityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, eid.sqlExec, eid.mutation, eid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (eid *ExternalIdentityDelete) ExecX(ctx context.Context) int {
	n, err := eid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (eid *ExternalIdentityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(externalidentity.Table, sqlgraph.NewFieldSpec(externalidentity.FieldID, field.TypeInt))
	if ps := eid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, eid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	eid.mutation.done = true
	return affected, err
}

// ExternalIdentityDeleteOne is the builder for deleting a single ExternalIdentity entity.
type ExternalIdentityDeleteOne struct {
	eid *ExternalIdentityDelete
}

// Where appends a list predicates to the ExternalIdentityDelete builder.
func (eido *ExternalIdentityDeleteOne) Where(ps ...predicate.ExternalIdentity) *ExternalIdentityDeleteOne {
	eido.eid.mutation.Where(ps...)
	return eido
}

// Exec executes the deletion query.
func (eido *ExternalIdentityDeleteOne) Exec(ctx context.Context) error {
	n, err := eido.eid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{externalidentity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eido *ExternalIdentityDeleteOne) ExecX(ctx context.Context) {
	if err := eido.Exec(ctx); err != nil {
		panic(err)
	}
}
