// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/ftsexternaljob"
)

// FTSExternalJobCreate is the builder for creating a FTSExternalJob entity.
type FTSExternalJobCreate struct {
	config
	mutation *FTSExternalJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (fejc *FTSExternalJobCreate) SetCreatedAt(t time.Time) *FTSExternalJobCreate {
	fejc.mutation.SetCreatedAt(t)
	return fejc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableCreatedAt(t *time.Time) *FTSExternalJobCreate {
	if t != nil {
		fejc.SetCreatedAt(*t)
	}
	return fejc
}

// SetUpdatedAt sets the "updated_at" field.
func (fejc *FTSExternalJobCreate) SetUpdatedAt(t time.Time) *FTSExternalJobCreate {
	fejc.mutation.SetUpdatedAt(t)
	return fejc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableUpdatedAt(t *time.Time) *FTSExternalJobCreate {
	if t != nil {
		fejc.SetUpdatedAt(*t)
	}
	return fejc
}

// SetDeletedAt sets the "deleted_at" field.
func (fejc *FTSExternalJobCreate) SetDeletedAt(t time.Time) *FTSExternalJobCreate {
	fejc.mutation.SetDeletedAt(t)
	return fejc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableDeletedAt(t *time.Time) *FTSExternalJobCreate {
	if t != nil {
		fejc.SetDeletedAt(*t)
	}
	return fejc
}

// SetRequestID sets the "request_id" field.
func (fejc *FTSExternalJobCreate) SetRequestID(s string) *FTSExternalJobCreate {
	fejc.mutation.SetRequestID(s)
	return fejc
}

// SetStatus sets the "status" field.
func (fejc *FTSExternalJobCreate) SetStatus(s string) *FTSExternalJobCreate {
	fejc.mutation.SetStatus(s)
	return fejc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableStatus(s *string) *FTSExternalJobCreate {
	if s != nil {
		fejc.SetStatus(*s)
	}
	return fejc
}

// SetFileID sets the "file_id" field.
func (fejc *FTSExternalJobCreate) SetFileID(i int) *FTSExternalJobCreate {
	fejc.mutation.SetFileID(i)
	return fejc
}

// SetOwnerID sets the "owner_id" field.
func (fejc *FTSExternalJobCreate) SetOwnerID(i int) *FTSExternalJobCreate {
	fejc.mutation.SetOwnerID(i)
	return fejc
}

// SetEntityID sets the "entity_id" field.
func (fejc *FTSExternalJobCreate) SetEntityID(i int) *FTSExternalJobCreate {
	fejc.mutation.SetEntityID(i)
	return fejc
}

// SetSnapshotToken sets the "snapshot_token" field.
func (fejc *FTSExternalJobCreate) SetSnapshotToken(s string) *FTSExternalJobCreate {
	fejc.mutation.SetSnapshotToken(s)
	return fejc
}

// SetMode sets the "mode" field.
func (fejc *FTSExternalJobCreate) SetMode(s string) *FTSExternalJobCreate {
	fejc.mutation.SetMode(s)
	return fejc
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableMode(s *string) *FTSExternalJobCreate {
	if s != nil {
		fejc.SetMode(*s)
	}
	return fejc
}

// SetTriggerReason sets the "trigger_reason" field.
func (fejc *FTSExternalJobCreate) SetTriggerReason(s string) *FTSExternalJobCreate {
	fejc.mutation.SetTriggerReason(s)
	return fejc
}

// SetNillableTriggerReason sets the "trigger_reason" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableTriggerReason(s *string) *FTSExternalJobCreate {
	if s != nil {
		fejc.SetTriggerReason(*s)
	}
	return fejc
}

// SetAttempt sets the "attempt" field.
func (fejc *FTSExternalJobCreate) SetAttempt(i int) *FTSExternalJobCreate {
	fejc.mutation.SetAttempt(i)
	return fejc
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableAttempt(i *int) *FTSExternalJobCreate {
	if i != nil {
		fejc.SetAttempt(*i)
	}
	return fejc
}

// SetResultPayload sets the "result_payload" field.
func (fejc *FTSExternalJobCreate) SetResultPayload(s string) *FTSExternalJobCreate {
	fejc.mutation.SetResultPayload(s)
	return fejc
}

// SetNillableResultPayload sets the "result_payload" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableResultPayload(s *string) *FTSExternalJobCreate {
	if s != nil {
		fejc.SetResultPayload(*s)
	}
	return fejc
}

// SetErrorPayload sets the "error_payload" field.
func (fejc *FTSExternalJobCreate) SetErrorPayload(s string) *FTSExternalJobCreate {
	fejc.mutation.SetErrorPayload(s)
	return fejc
}

// SetNillableErrorPayload sets the "error_payload" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableErrorPayload(s *string) *FTSExternalJobCreate {
	if s != nil {
		fejc.SetErrorPayload(*s)
	}
	return fejc
}

// SetManifestPath sets the "manifest_path" field.
func (fejc *FTSExternalJobCreate) SetManifestPath(s string) *FTSExternalJobCreate {
	fejc.mutation.SetManifestPath(s)
	return fejc
}

// SetNillableManifestPath sets the "manifest_path" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableManifestPath(s *string) *FTSExternalJobCreate {
	if s != nil {
		fejc.SetManifestPath(*s)
	}
	return fejc
}

// SetQualityReport sets the "quality_report" field.
func (fejc *FTSExternalJobCreate) SetQualityReport(s string) *FTSExternalJobCreate {
	fejc.mutation.SetQualityReport(s)
	return fejc
}

// SetNillableQualityReport sets the "quality_report" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableQualityReport(s *string) *FTSExternalJobCreate {
	if s != nil {
		fejc.SetQualityReport(*s)
	}
	return fejc
}

// SetRequestedAt sets the "requested_at" field.
func (fejc *FTSExternalJobCreate) SetRequestedAt(t time.Time) *FTSExternalJobCreate {
	fejc.mutation.SetRequestedAt(t)
	return fejc
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableRequestedAt(t *time.Time) *FTSExternalJobCreate {
	if t != nil {
		fejc.SetRequestedAt(*t)
	}
	return fejc
}

// SetDeadlineAt sets the "deadline_at" field.
func (fejc *FTSExternalJobCreate) SetDeadlineAt(t time.Time) *FTSExternalJobCreate {
	fejc.mutation.SetDeadlineAt(t)
	return fejc
}

// SetCompletedAt sets the "completed_at" field.
func (fejc *FTSExternalJobCreate) SetCompletedAt(t time.Time) *FTSExternalJobCreate {
	fejc.mutation.SetCompletedAt(t)
	return fejc
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (fejc *FTSExternalJobCreate) SetNillableCompletedAt(t *time.Time) *FTSExternalJobCreate {
	if t != nil {
		fejc.SetCompletedAt(*t)
	}
	return fejc
}

// Mutation returns the FTSExternalJobMutation object of the builder.
func (fejc *FTSExternalJobCreate) Mutation() *FTSExternalJobMutation {
	return fejc.mutation
}

// Save creates the FTSExternalJob in the database.
func (fejc *FTSExternalJobCreate) Save(ctx context.Context) (*FTSExternalJob, error) {
	if err := fejc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, fejc.sqlSave, fejc.mutation, fejc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fejc *FTSExternalJobCreate) SaveX(ctx context.Context) *FTSExternalJob {
	v, err := fejc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fejc *FTSExternalJobCreate) Exec(ctx context.Context) error {
	_, err := fejc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fejc *FTSExternalJobCreate) ExecX(ctx context.Context) {
	if err := fejc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fejc *FTSExternalJobCreate) defaults() error {
	if _, ok := fejc.mutation.CreatedAt(); !ok {
		if ftsexternaljob.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized ftsexternaljob.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := ftsexternaljob.DefaultCreatedAt()
		fejc.mutation.SetCreatedAt(v)
	}
	if _, ok := fejc.mutation.UpdatedAt(); !ok {
		if ftsexternaljob.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ftsexternaljob.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ftsexternaljob.DefaultUpdatedAt()
		fejc.mutation.SetUpdatedAt(v)
	}
	if _, ok := fejc.mutation.Status(); !ok {
		v := ftsexternaljob.DefaultStatus
		fejc.mutation.SetStatus(v)
	}
	if _, ok := fejc.mutation.Mode(); !ok {
		v := ftsexternaljob.DefaultMode
		fejc.mutation.SetMode(v)
	}
	if _, ok := fejc.mutation.TriggerReason(); !ok {
		v := ftsexternaljob.DefaultTriggerReason
		fejc.mutation.SetTriggerReason(v)
	}
	if _, ok := fejc.mutation.Attempt(); !ok {
		v := ftsexternaljob.DefaultAttempt
		fejc.mutation.SetAttempt(v)
	}
	if _, ok := fejc.mutation.RequestedAt(); !ok {
		if ftsexternaljob.DefaultRequestedAt == nil {
			return fmt.Errorf("ent: uninitialized ftsexternaljob.DefaultRequestedAt (forgotten import ent/runtime?)")
		}
		v := ftsexternaljob.DefaultRequestedAt()
		fejc.mutation.SetRequestedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (fejc *FTSExternalJobCreate) check() error {
	if _, ok := fejc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FTSExternalJob.created_at"`)}
	}
	if _, ok := fejc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FTSExternalJob.updated_at"`)}
	}
	if _, ok := fejc.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "FTSExternalJob.request_id"`)}
	}
	if _, ok := fejc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FTSExternalJob.status"`)}
	}
	if _, ok := fejc.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`ent: missing required field "FTSExternalJob.file_id"`)}
	}
	if _, ok := fejc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "FTSExternalJob.owner_id"`)}
	}
	if _, ok := fejc.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "FTSExternalJob.entity_id"`)}
	}
	if _, ok := fejc.mutation.SnapshotToken(); !ok {
		return &ValidationError{Name: "snapshot_token", err: errors.New(`ent: missing required field "FTSExternalJob.snapshot_token"`)}
	}
	if _, ok := fejc.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "FTSExternalJob.mode"`)}
	}
	if _, ok := fejc.mutation.TriggerReason(); !ok {
		return &ValidationError{Name: "trigger_reason", err: errors.New(`ent: missing required field "FTSExternalJob.trigger_reason"`)}
	}
	if _, ok := fejc.mutation.Attempt(); !ok {
		return &ValidationError{Name: "attempt", err: errors.New(`ent: missing required field "FTSExternalJob.attempt"`)}
	}
	if _, ok := fejc.mutation.RequestedAt(); !ok {
		return &ValidationError{Name: "requested_at", err: errors.New(`ent: missing required field "FTSExternalJob.requested_at"`)}
	}
	if _, ok := fejc.mutation.DeadlineAt(); !ok {
		return &ValidationError{Name: "deadline_at", err: errors.New(`ent: missing required field "FTSExternalJob.deadline_at"`)}
	}
	return nil
}

func (fejc *FTSExternalJobCreate) sqlSave(ctx context.Context) (*FTSExternalJob, error) {
	if err := fejc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fejc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fejc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	fejc.mutation.id = &_node.ID
	fejc.mutation.done = true
	return _node, nil
}

func (fejc *FTSExternalJobCreate) createSpec() (*FTSExternalJob, *sqlgraph.CreateSpec) {
	var (
		_node = &FTSExternalJob{config: fejc.config}
		_spec = sqlgraph.NewCreateSpec(ftsexternaljob.Table, sqlgraph.NewFieldSpec(ftsexternaljob.FieldID, field.TypeInt))
	)

	if id, ok := fejc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = fejc.conflict
	if value, ok := fejc.mutation.CreatedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := fejc.mutation.UpdatedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := fejc.mutation.DeletedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := fejc.mutation.RequestID(); ok {
		_spec.SetField(ftsexternaljob.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := fejc.mutation.Status(); ok {
		_spec.SetField(ftsexternaljob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := fejc.mutation.FileID(); ok {
		_spec.SetField(ftsexternaljob.FieldFileID, field.TypeInt, value)
		_node.FileID = value
	}
	if value, ok := fejc.mutation.OwnerID(); ok {
		_spec.SetField(ftsexternaljob.FieldOwnerID, field.TypeInt, value)
		_node.OwnerID = value
	}
	if value, ok := fejc.mutation.EntityID(); ok {
		_spec.SetField(ftsexternaljob.FieldEntityID, field.TypeInt, value)
		_node.EntityID = value
	}
	if value, ok := fejc.mutation.SnapshotToken(); ok {
		_spec.SetField(ftsexternaljob.FieldSnapshotToken, field.TypeString, value)
		_node.SnapshotToken = value
	}
	if value, ok := fejc.mutation.Mode(); ok {
		_spec.SetField(ftsexternaljob.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := fejc.mutation.TriggerReason(); ok {
		_spec.SetField(ftsexternaljob.FieldTriggerReason, field.TypeString, value)
		_node.TriggerReason = value
	}
	if value, ok := fejc.mutation.Attempt(); ok {
		_spec.SetField(ftsexternaljob.FieldAttempt, field.TypeInt, value)
		_node.Attempt = value
	}
	if value, ok := fejc.mutation.ResultPayload(); ok {
		_spec.SetField(ftsexternaljob.FieldResultPayload, field.TypeString, value)
		_node.ResultPayload = value
	}
	if value, ok := fejc.mutation.ErrorPayload(); ok {
		_spec.SetField(ftsexternaljob.FieldErrorPayload, field.TypeString, value)
		_node.ErrorPayload = value
	}
	if value, ok := fejc.mutation.ManifestPath(); ok {
		_spec.SetField(ftsexternaljob.FieldManifestPath, field.TypeString, value)
		_node.ManifestPath = value
	}
	if value, ok := fejc.mutation.QualityReport(); ok {
		_spec.SetField(ftsexternaljob.FieldQualityReport, field.TypeString, value)
		_node.QualityReport = value
	}
	if value, ok := fejc.mutation.RequestedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = value
	}
	if value, ok := fejc.mutation.DeadlineAt(); ok {
		_spec.SetField(ftsexternaljob.FieldDeadlineAt, field.TypeTime, value)
		_node.DeadlineAt = value
	}
	if value, ok := fejc.mutation.CompletedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FTSExternalJob.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FTSExternalJobUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (fejc *FTSExternalJobCreate) OnConflict(opts ...sql.ConflictOption) *FTSExternalJobUpsertOne {
	fejc.conflict = opts
	return &FTSExternalJobUpsertOne{
		create: fejc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FTSExternalJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (fejc *FTSExternalJobCreate) OnConflictColumns(columns ...string) *FTSExternalJobUpsertOne {
	fejc.conflict = append(fejc.conflict, sql.ConflictColumns(columns...))
	return &FTSExternalJobUpsertOne{
		create: fejc,
	}
}

type (
	// FTSExternalJobUpsertOne is the builder for "upsert"-ing
	//  one FTSExternalJob node.
	FTSExternalJobUpsertOne struct {
		create *FTSExternalJobCreate
	}

	// FTSExternalJobUpsert is the "OnConflict" setter.
	FTSExternalJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *FTSExternalJobUpsert) SetUpdatedAt(v time.Time) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateUpdatedAt() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FTSExternalJobUpsert) SetDeletedAt(v time.Time) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateDeletedAt() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FTSExternalJobUpsert) ClearDeletedAt() *FTSExternalJobUpsert {
	u.SetNull(ftsexternaljob.FieldDeletedAt)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *FTSExternalJobUpsert) SetRequestID(v string) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateRequestID() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldRequestID)
	return u
}

// SetStatus sets the "status" field.
func (u *FTSExternalJobUpsert) SetStatus(v string) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateStatus() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldStatus)
	return u
}

// SetFileID sets the "file_id" field.
func (u *FTSExternalJobUpsert) SetFileID(v int) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldFileID, v)
	return u
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateFileID() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldFileID)
	return u
}

// AddFileID adds v to the "file_id" field.
func (u *FTSExternalJobUpsert) AddFileID(v int) *FTSExternalJobUpsert {
	u.Add(ftsexternaljob.FieldFileID, v)
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *FTSExternalJobUpsert) SetOwnerID(v int) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldOwnerID, v)
	return u
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateOwnerID() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldOwnerID)
	return u
}

// AddOwnerID adds v to the "owner_id" field.
func (u *FTSExternalJobUpsert) AddOwnerID(v int) *FTSExternalJobUpsert {
	u.Add(ftsexternaljob.FieldOwnerID, v)
	return u
}

// SetEntityID sets the "entity_id" field.
func (u *FTSExternalJobUpsert) SetEntityID(v int) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldEntityID, v)
	return u
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateEntityID() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldEntityID)
	return u
}

// AddEntityID adds v to the "entity_id" field.
func (u *FTSExternalJobUpsert) AddEntityID(v int) *FTSExternalJobUpsert {
	u.Add(ftsexternaljob.FieldEntityID, v)
	return u
}

// SetSnapshotToken sets the "snapshot_token" field.
func (u *FTSExternalJobUpsert) SetSnapshotToken(v string) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldSnapshotToken, v)
	return u
}

// UpdateSnapshotToken sets the "snapshot_token" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateSnapshotToken() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldSnapshotToken)
	return u
}

// SetMode sets the "mode" field.
func (u *FTSExternalJobUpsert) SetMode(v string) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateMode() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldMode)
	return u
}

// SetTriggerReason sets the "trigger_reason" field.
func (u *FTSExternalJobUpsert) SetTriggerReason(v string) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldTriggerReason, v)
	return u
}

// UpdateTriggerReason sets the "trigger_reason" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateTriggerReason() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldTriggerReason)
	return u
}

// SetAttempt sets the "attempt" field.
func (u *FTSExternalJobUpsert) SetAttempt(v int) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldAttempt, v)
	return u
}

// UpdateAttempt sets the "attempt" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateAttempt() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldAttempt)
	return u
}

// AddAttempt adds v to the "attempt" field.
func (u *FTSExternalJobUpsert) AddAttempt(v int) *FTSExternalJobUpsert {
	u.Add(ftsexternaljob.FieldAttempt, v)
	return u
}

// SetResultPayload sets the "result_payload" field.
func (u *FTSExternalJobUpsert) SetResultPayload(v string) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldResultPayload, v)
	return u
}

// UpdateResultPayload sets the "result_payload" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateResultPayload() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldResultPayload)
	return u
}

// ClearResultPayload clears the value of the "result_payload" field.
func (u *FTSExternalJobUpsert) ClearResultPayload() *FTSExternalJobUpsert {
	u.SetNull(ftsexternaljob.FieldResultPayload)
	return u
}

// SetErrorPayload sets the "error_payload" field.
func (u *FTSExternalJobUpsert) SetErrorPayload(v string) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldErrorPayload, v)
	return u
}

// UpdateErrorPayload sets the "error_payload" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateErrorPayload() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldErrorPayload)
	return u
}

// ClearErrorPayload clears the value of the "error_payload" field.
func (u *FTSExternalJobUpsert) ClearErrorPayload() *FTSExternalJobUpsert {
	u.SetNull(ftsexternaljob.FieldErrorPayload)
	return u
}

// SetManifestPath sets the "manifest_path" field.
func (u *FTSExternalJobUpsert) SetManifestPath(v string) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldManifestPath, v)
	return u
}

// UpdateManifestPath sets the "manifest_path" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateManifestPath() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldManifestPath)
	return u
}

// ClearManifestPath clears the value of the "manifest_path" field.
func (u *FTSExternalJobUpsert) ClearManifestPath() *FTSExternalJobUpsert {
	u.SetNull(ftsexternaljob.FieldManifestPath)
	return u
}

// SetQualityReport sets the "quality_report" field.
func (u *FTSExternalJobUpsert) SetQualityReport(v string) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldQualityReport, v)
	return u
}

// UpdateQualityReport sets the "quality_report" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateQualityReport() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldQualityReport)
	return u
}

// ClearQualityReport clears the value of the "quality_report" field.
func (u *FTSExternalJobUpsert) ClearQualityReport() *FTSExternalJobUpsert {
	u.SetNull(ftsexternaljob.FieldQualityReport)
	return u
}

// SetRequestedAt sets the "requested_at" field.
func (u *FTSExternalJobUpsert) SetRequestedAt(v time.Time) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldRequestedAt, v)
	return u
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateRequestedAt() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldRequestedAt)
	return u
}

// SetDeadlineAt sets the "deadline_at" field.
func (u *FTSExternalJobUpsert) SetDeadlineAt(v time.Time) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldDeadlineAt, v)
	return u
}

// UpdateDeadlineAt sets the "deadline_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateDeadlineAt() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldDeadlineAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *FTSExternalJobUpsert) SetCompletedAt(v time.Time) *FTSExternalJobUpsert {
	u.Set(ftsexternaljob.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsert) UpdateCompletedAt() *FTSExternalJobUpsert {
	u.SetExcluded(ftsexternaljob.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *FTSExternalJobUpsert) ClearCompletedAt() *FTSExternalJobUpsert {
	u.SetNull(ftsexternaljob.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FTSExternalJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FTSExternalJobUpsertOne) UpdateNewValues() *FTSExternalJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ftsexternaljob.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FTSExternalJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FTSExternalJobUpsertOne) Ignore() *FTSExternalJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FTSExternalJobUpsertOne) DoNothing() *FTSExternalJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FTSExternalJobCreate.OnConflict
// documentation for more info.
func (u *FTSExternalJobUpsertOne) Update(set func(*FTSExternalJobUpsert)) *FTSExternalJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FTSExternalJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FTSExternalJobUpsertOne) SetUpdatedAt(v time.Time) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateUpdatedAt() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FTSExternalJobUpsertOne) SetDeletedAt(v time.Time) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateDeletedAt() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FTSExternalJobUpsertOne) ClearDeletedAt() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearDeletedAt()
	})
}

// SetRequestID sets the "request_id" field.
func (u *FTSExternalJobUpsertOne) SetRequestID(v string) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateRequestID() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateRequestID()
	})
}

// SetStatus sets the "status" field.
func (u *FTSExternalJobUpsertOne) SetStatus(v string) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateStatus() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateStatus()
	})
}

// SetFileID sets the "file_id" field.
func (u *FTSExternalJobUpsertOne) SetFileID(v int) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetFileID(v)
	})
}

// AddFileID adds v to the "file_id" field.
func (u *FTSExternalJobUpsertOne) AddFileID(v int) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.AddFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateFileID() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateFileID()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *FTSExternalJobUpsertOne) SetOwnerID(v int) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetOwnerID(v)
	})
}

// AddOwnerID adds v to the "owner_id" field.
func (u *FTSExternalJobUpsertOne) AddOwnerID(v int) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.AddOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateOwnerID() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateOwnerID()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *FTSExternalJobUpsertOne) SetEntityID(v int) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetEntityID(v)
	})
}

// AddEntityID adds v to the "entity_id" field.
func (u *FTSExternalJobUpsertOne) AddEntityID(v int) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.AddEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateEntityID() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateEntityID()
	})
}

// SetSnapshotToken sets the "snapshot_token" field.
func (u *FTSExternalJobUpsertOne) SetSnapshotToken(v string) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetSnapshotToken(v)
	})
}

// UpdateSnapshotToken sets the "snapshot_token" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateSnapshotToken() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateSnapshotToken()
	})
}

// SetMode sets the "mode" field.
func (u *FTSExternalJobUpsertOne) SetMode(v string) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateMode() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateMode()
	})
}

// SetTriggerReason sets the "trigger_reason" field.
func (u *FTSExternalJobUpsertOne) SetTriggerReason(v string) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetTriggerReason(v)
	})
}

// UpdateTriggerReason sets the "trigger_reason" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateTriggerReason() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateTriggerReason()
	})
}

// SetAttempt sets the "attempt" field.
func (u *FTSExternalJobUpsertOne) SetAttempt(v int) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetAttempt(v)
	})
}

// AddAttempt adds v to the "attempt" field.
func (u *FTSExternalJobUpsertOne) AddAttempt(v int) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.AddAttempt(v)
	})
}

// UpdateAttempt sets the "attempt" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateAttempt() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateAttempt()
	})
}

// SetResultPayload sets the "result_payload" field.
func (u *FTSExternalJobUpsertOne) SetResultPayload(v string) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetResultPayload(v)
	})
}

// UpdateResultPayload sets the "result_payload" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateResultPayload() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateResultPayload()
	})
}

// ClearResultPayload clears the value of the "result_payload" field.
func (u *FTSExternalJobUpsertOne) ClearResultPayload() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearResultPayload()
	})
}

// SetErrorPayload sets the "error_payload" field.
func (u *FTSExternalJobUpsertOne) SetErrorPayload(v string) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetErrorPayload(v)
	})
}

// UpdateErrorPayload sets the "error_payload" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateErrorPayload() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateErrorPayload()
	})
}

// ClearErrorPayload clears the value of the "error_payload" field.
func (u *FTSExternalJobUpsertOne) ClearErrorPayload() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearErrorPayload()
	})
}

// SetManifestPath sets the "manifest_path" field.
func (u *FTSExternalJobUpsertOne) SetManifestPath(v string) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetManifestPath(v)
	})
}

// UpdateManifestPath sets the "manifest_path" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateManifestPath() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateManifestPath()
	})
}

// ClearManifestPath clears the value of the "manifest_path" field.
func (u *FTSExternalJobUpsertOne) ClearManifestPath() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearManifestPath()
	})
}

// SetQualityReport sets the "quality_report" field.
func (u *FTSExternalJobUpsertOne) SetQualityReport(v string) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetQualityReport(v)
	})
}

// UpdateQualityReport sets the "quality_report" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateQualityReport() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateQualityReport()
	})
}

// ClearQualityReport clears the value of the "quality_report" field.
func (u *FTSExternalJobUpsertOne) ClearQualityReport() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearQualityReport()
	})
}

// SetRequestedAt sets the "requested_at" field.
func (u *FTSExternalJobUpsertOne) SetRequestedAt(v time.Time) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetRequestedAt(v)
	})
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateRequestedAt() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateRequestedAt()
	})
}

// SetDeadlineAt sets the "deadline_at" field.
func (u *FTSExternalJobUpsertOne) SetDeadlineAt(v time.Time) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetDeadlineAt(v)
	})
}

// UpdateDeadlineAt sets the "deadline_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateDeadlineAt() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateDeadlineAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *FTSExternalJobUpsertOne) SetCompletedAt(v time.Time) *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsertOne) UpdateCompletedAt() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *FTSExternalJobUpsertOne) ClearCompletedAt() *FTSExternalJobUpsertOne {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *FTSExternalJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FTSExternalJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FTSExternalJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FTSExternalJobUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FTSExternalJobUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *FTSExternalJobCreate) SetRawID(t int) *FTSExternalJobCreate {
	m.mutation.SetRawID(t)
	return m
}

// FTSExternalJobCreateBulk is the builder for creating many FTSExternalJob entities in bulk.
type FTSExternalJobCreateBulk struct {
	config
	err      error
	builders []*FTSExternalJobCreate
	conflict []sql.ConflictOption
}

// Save creates the FTSExternalJob entities in the database.
func (fejcb *FTSExternalJobCreateBulk) Save(ctx context.Context) ([]*FTSExternalJob, error) {
	if fejcb.err != nil {
		return nil, fejcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(fejcb.builders))
	nodes := make([]*FTSExternalJob, len(fejcb.builders))
	mutators := make([]Mutator, len(fejcb.builders))
	for i := range fejcb.builders {
		func(i int, root context.Context) {
			builder := fejcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FTSExternalJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fejcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = fejcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fejcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fejcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fejcb *FTSExternalJobCreateBulk) SaveX(ctx context.Context) []*FTSExternalJob {
	v, err := fejcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fejcb *FTSExternalJobCreateBulk) Exec(ctx context.Context) error {
	_, err := fejcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fejcb *FTSExternalJobCreateBulk) ExecX(ctx context.Context) {
	if err := fejcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FTSExternalJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FTSExternalJobUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (fejcb *FTSExternalJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *FTSExternalJobUpsertBulk {
	fejcb.conflict = opts
	return &FTSExternalJobUpsertBulk{
		create: fejcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FTSExternalJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (fejcb *FTSExternalJobCreateBulk) OnConflictColumns(columns ...string) *FTSExternalJobUpsertBulk {
	fejcb.conflict = append(fejcb.conflict, sql.ConflictColumns(columns...))
	return &FTSExternalJobUpsertBulk{
		create: fejcb,
	}
}

// FTSExternalJobUpsertBulk is the builder for "upsert"-ing
// a bulk of FTSExternalJob nodes.
type FTSExternalJobUpsertBulk struct {
	create *FTSExternalJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FTSExternalJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FTSExternalJobUpsertBulk) UpdateNewValues() *FTSExternalJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ftsexternaljob.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FTSExternalJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FTSExternalJobUpsertBulk) Ignore() *FTSExternalJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FTSExternalJobUpsertBulk) DoNothing() *FTSExternalJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FTSExternalJobCreateBulk.OnConflict
// documentation for more info.
func (u *FTSExternalJobUpsertBulk) Update(set func(*FTSExternalJobUpsert)) *FTSExternalJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FTSExternalJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FTSExternalJobUpsertBulk) SetUpdatedAt(v time.Time) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateUpdatedAt() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FTSExternalJobUpsertBulk) SetDeletedAt(v time.Time) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateDeletedAt() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FTSExternalJobUpsertBulk) ClearDeletedAt() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearDeletedAt()
	})
}

// SetRequestID sets the "request_id" field.
func (u *FTSExternalJobUpsertBulk) SetRequestID(v string) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateRequestID() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateRequestID()
	})
}

// SetStatus sets the "status" field.
func (u *FTSExternalJobUpsertBulk) SetStatus(v string) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateStatus() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateStatus()
	})
}

// SetFileID sets the "file_id" field.
func (u *FTSExternalJobUpsertBulk) SetFileID(v int) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetFileID(v)
	})
}

// AddFileID adds v to the "file_id" field.
func (u *FTSExternalJobUpsertBulk) AddFileID(v int) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.AddFileID(v)
	})
}

// UpdateFileID sets the "file_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateFileID() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateFileID()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *FTSExternalJobUpsertBulk) SetOwnerID(v int) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetOwnerID(v)
	})
}

// AddOwnerID adds v to the "owner_id" field.
func (u *FTSExternalJobUpsertBulk) AddOwnerID(v int) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.AddOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateOwnerID() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateOwnerID()
	})
}

// SetEntityID sets the "entity_id" field.
func (u *FTSExternalJobUpsertBulk) SetEntityID(v int) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetEntityID(v)
	})
}

// AddEntityID adds v to the "entity_id" field.
func (u *FTSExternalJobUpsertBulk) AddEntityID(v int) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.AddEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateEntityID() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateEntityID()
	})
}

// SetSnapshotToken sets the "snapshot_token" field.
func (u *FTSExternalJobUpsertBulk) SetSnapshotToken(v string) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetSnapshotToken(v)
	})
}

// UpdateSnapshotToken sets the "snapshot_token" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateSnapshotToken() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateSnapshotToken()
	})
}

// SetMode sets the "mode" field.
func (u *FTSExternalJobUpsertBulk) SetMode(v string) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateMode() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateMode()
	})
}

// SetTriggerReason sets the "trigger_reason" field.
func (u *FTSExternalJobUpsertBulk) SetTriggerReason(v string) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetTriggerReason(v)
	})
}

// UpdateTriggerReason sets the "trigger_reason" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateTriggerReason() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateTriggerReason()
	})
}

// SetAttempt sets the "attempt" field.
func (u *FTSExternalJobUpsertBulk) SetAttempt(v int) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetAttempt(v)
	})
}

// AddAttempt adds v to the "attempt" field.
func (u *FTSExternalJobUpsertBulk) AddAttempt(v int) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.AddAttempt(v)
	})
}

// UpdateAttempt sets the "attempt" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateAttempt() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateAttempt()
	})
}

// SetResultPayload sets the "result_payload" field.
func (u *FTSExternalJobUpsertBulk) SetResultPayload(v string) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetResultPayload(v)
	})
}

// UpdateResultPayload sets the "result_payload" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateResultPayload() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateResultPayload()
	})
}

// ClearResultPayload clears the value of the "result_payload" field.
func (u *FTSExternalJobUpsertBulk) ClearResultPayload() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearResultPayload()
	})
}

// SetErrorPayload sets the "error_payload" field.
func (u *FTSExternalJobUpsertBulk) SetErrorPayload(v string) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetErrorPayload(v)
	})
}

// UpdateErrorPayload sets the "error_payload" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateErrorPayload() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateErrorPayload()
	})
}

// ClearErrorPayload clears the value of the "error_payload" field.
func (u *FTSExternalJobUpsertBulk) ClearErrorPayload() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearErrorPayload()
	})
}

// SetManifestPath sets the "manifest_path" field.
func (u *FTSExternalJobUpsertBulk) SetManifestPath(v string) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetManifestPath(v)
	})
}

// UpdateManifestPath sets the "manifest_path" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateManifestPath() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateManifestPath()
	})
}

// ClearManifestPath clears the value of the "manifest_path" field.
func (u *FTSExternalJobUpsertBulk) ClearManifestPath() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearManifestPath()
	})
}

// SetQualityReport sets the "quality_report" field.
func (u *FTSExternalJobUpsertBulk) SetQualityReport(v string) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetQualityReport(v)
	})
}

// UpdateQualityReport sets the "quality_report" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateQualityReport() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateQualityReport()
	})
}

// ClearQualityReport clears the value of the "quality_report" field.
func (u *FTSExternalJobUpsertBulk) ClearQualityReport() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearQualityReport()
	})
}

// SetRequestedAt sets the "requested_at" field.
func (u *FTSExternalJobUpsertBulk) SetRequestedAt(v time.Time) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetRequestedAt(v)
	})
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateRequestedAt() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateRequestedAt()
	})
}

// SetDeadlineAt sets the "deadline_at" field.
func (u *FTSExternalJobUpsertBulk) SetDeadlineAt(v time.Time) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetDeadlineAt(v)
	})
}

// UpdateDeadlineAt sets the "deadline_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateDeadlineAt() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateDeadlineAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *FTSExternalJobUpsertBulk) SetCompletedAt(v time.Time) *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *FTSExternalJobUpsertBulk) UpdateCompletedAt() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *FTSExternalJobUpsertBulk) ClearCompletedAt() *FTSExternalJobUpsertBulk {
	return u.Update(func(s *FTSExternalJobUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *FTSExternalJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FTSExternalJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FTSExternalJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FTSExternalJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
