// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/ftsexternaljob"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// FTSExternalJobDelete is the builder for deleting a FTSExternalJob entity.
type FTSExternalJobDelete struct {
	config
	hooks    []Hook
	mutation *FTSExternalJobMutation
}

// Where appends a list predicates to the FTSExternalJobDelete builder.
func (fejd *FTSExternalJobDelete) Where(ps ...predicate.FTSExternalJob) *FTSExternalJobDelete {
	fejd.mutation.Where(ps...)
	return fejd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fejd *FTSExternalJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fejd.sqlExec, fejd.mutation, fejd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fejd *FTSExternalJobDelete) ExecX(ctx context.Context) int {
	n, err := fejd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fejd *FTSExternalJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ftsexternaljob.Table, sqlgraph.NewFieldSpec(ftsexternaljob.FieldID, field.TypeInt))
	if ps := fejd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fejd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fejd.mutation.done = true
	return affected, err
}

// FTSExternalJobDeleteOne is the builder for deleting a single FTSExternalJob entity.
type FTSExternalJobDeleteOne struct {
	fejd *FTSExternalJobDelete
}

// Where appends a list predicates to the FTSExternalJobDelete builder.
func (fejdo *FTSExternalJobDeleteOne) Where(ps ...predicate.FTSExternalJob) *FTSExternalJobDeleteOne {
	fejdo.fejd.mutation.Where(ps...)
	return fejdo
}

// Exec executes the deletion query.
func (fejdo *FTSExternalJobDeleteOne) Exec(ctx context.Context) error {
	n, err := fejdo.fejd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ftsexternaljob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fejdo *FTSExternalJobDeleteOne) ExecX(ctx context.Context) {
	if err := fejdo.Exec(ctx); err != nil {
		panic(err)
	}
}
