// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/ftsexternaljob"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// FTSExternalJobUpdate is the builder for updating FTSExternalJob entities.
type FTSExternalJobUpdate struct {
	config
	hooks    []Hook
	mutation *FTSExternalJobMutation
}

// Where appends a list predicates to the FTSExternalJobUpdate builder.
func (feju *FTSExternalJobUpdate) Where(ps ...predicate.FTSExternalJob) *FTSExternalJobUpdate {
	feju.mutation.Where(ps...)
	return feju
}

// SetUpdatedAt sets the "updated_at" field.
func (feju *FTSExternalJobUpdate) SetUpdatedAt(t time.Time) *FTSExternalJobUpdate {
	feju.mutation.SetUpdatedAt(t)
	return feju
}

// SetDeletedAt sets the "deleted_at" field.
func (feju *FTSExternalJobUpdate) SetDeletedAt(t time.Time) *FTSExternalJobUpdate {
	feju.mutation.SetDeletedAt(t)
	return feju
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableDeletedAt(t *time.Time) *FTSExternalJobUpdate {
	if t != nil {
		feju.SetDeletedAt(*t)
	}
	return feju
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (feju *FTSExternalJobUpdate) ClearDeletedAt() *FTSExternalJobUpdate {
	feju.mutation.ClearDeletedAt()
	return feju
}

// SetRequestID sets the "request_id" field.
func (feju *FTSExternalJobUpdate) SetRequestID(s string) *FTSExternalJobUpdate {
	feju.mutation.SetRequestID(s)
	return feju
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableRequestID(s *string) *FTSExternalJobUpdate {
	if s != nil {
		feju.SetRequestID(*s)
	}
	return feju
}

// SetStatus sets the "status" field.
func (feju *FTSExternalJobUpdate) SetStatus(s string) *FTSExternalJobUpdate {
	feju.mutation.SetStatus(s)
	return feju
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableStatus(s *string) *FTSExternalJobUpdate {
	if s != nil {
		feju.SetStatus(*s)
	}
	return feju
}

// SetFileID sets the "file_id" field.
func (feju *FTSExternalJobUpdate) SetFileID(i int) *FTSExternalJobUpdate {
	feju.mutation.ResetFileID()
	feju.mutation.SetFileID(i)
	return feju
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableFileID(i *int) *FTSExternalJobUpdate {
	if i != nil {
		feju.SetFileID(*i)
	}
	return feju
}

// AddFileID adds i to the "file_id" field.
func (feju *FTSExternalJobUpdate) AddFileID(i int) *FTSExternalJobUpdate {
	feju.mutation.AddFileID(i)
	return feju
}

// SetOwnerID sets the "owner_id" field.
func (feju *FTSExternalJobUpdate) SetOwnerID(i int) *FTSExternalJobUpdate {
	feju.mutation.ResetOwnerID()
	feju.mutation.SetOwnerID(i)
	return feju
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableOwnerID(i *int) *FTSExternalJobUpdate {
	if i != nil {
		feju.SetOwnerID(*i)
	}
	return feju
}

// AddOwnerID adds i to the "owner_id" field.
func (feju *FTSExternalJobUpdate) AddOwnerID(i int) *FTSExternalJobUpdate {
	feju.mutation.AddOwnerID(i)
	return feju
}

// SetEntityID sets the "entity_id" field.
func (feju *FTSExternalJobUpdate) SetEntityID(i int) *FTSExternalJobUpdate {
	feju.mutation.ResetEntityID()
	feju.mutation.SetEntityID(i)
	return feju
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableEntityID(i *int) *FTSExternalJobUpdate {
	if i != nil {
		feju.SetEntityID(*i)
	}
	return feju
}

// AddEntityID adds i to the "entity_id" field.
func (feju *FTSExternalJobUpdate) AddEntityID(i int) *FTSExternalJobUpdate {
	feju.mutation.AddEntityID(i)
	return feju
}

// SetSnapshotToken sets the "snapshot_token" field.
func (feju *FTSExternalJobUpdate) SetSnapshotToken(s string) *FTSExternalJobUpdate {
	feju.mutation.SetSnapshotToken(s)
	return feju
}

// SetNillableSnapshotToken sets the "snapshot_token" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableSnapshotToken(s *string) *FTSExternalJobUpdate {
	if s != nil {
		feju.SetSnapshotToken(*s)
	}
	return feju
}

// SetMode sets the "mode" field.
func (feju *FTSExternalJobUpdate) SetMode(s string) *FTSExternalJobUpdate {
	feju.mutation.SetMode(s)
	return feju
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableMode(s *string) *FTSExternalJobUpdate {
	if s != nil {
		feju.SetMode(*s)
	}
	return feju
}

// SetTriggerReason sets the "trigger_reason" field.
func (feju *FTSExternalJobUpdate) SetTriggerReason(s string) *FTSExternalJobUpdate {
	feju.mutation.SetTriggerReason(s)
	return feju
}

// SetNillableTriggerReason sets the "trigger_reason" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableTriggerReason(s *string) *FTSExternalJobUpdate {
	if s != nil {
		feju.SetTriggerReason(*s)
	}
	return feju
}

// SetAttempt sets the "attempt" field.
func (feju *FTSExternalJobUpdate) SetAttempt(i int) *FTSExternalJobUpdate {
	feju.mutation.ResetAttempt()
	feju.mutation.SetAttempt(i)
	return feju
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableAttempt(i *int) *FTSExternalJobUpdate {
	if i != nil {
		feju.SetAttempt(*i)
	}
	return feju
}

// AddAttempt adds i to the "attempt" field.
func (feju *FTSExternalJobUpdate) AddAttempt(i int) *FTSExternalJobUpdate {
	feju.mutation.AddAttempt(i)
	return feju
}

// SetResultPayload sets the "result_payload" field.
func (feju *FTSExternalJobUpdate) SetResultPayload(s string) *FTSExternalJobUpdate {
	feju.mutation.SetResultPayload(s)
	return feju
}

// SetNillableResultPayload sets the "result_payload" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableResultPayload(s *string) *FTSExternalJobUpdate {
	if s != nil {
		feju.SetResultPayload(*s)
	}
	return feju
}

// ClearResultPayload clears the value of the "result_payload" field.
func (feju *FTSExternalJobUpdate) ClearResultPayload() *FTSExternalJobUpdate {
	feju.mutation.ClearResultPayload()
	return feju
}

// SetErrorPayload sets the "error_payload" field.
func (feju *FTSExternalJobUpdate) SetErrorPayload(s string) *FTSExternalJobUpdate {
	feju.mutation.SetErrorPayload(s)
	return feju
}

// SetNillableErrorPayload sets the "error_payload" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableErrorPayload(s *string) *FTSExternalJobUpdate {
	if s != nil {
		feju.SetErrorPayload(*s)
	}
	return feju
}

// ClearErrorPayload clears the value of the "error_payload" field.
func (feju *FTSExternalJobUpdate) ClearErrorPayload() *FTSExternalJobUpdate {
	feju.mutation.ClearErrorPayload()
	return feju
}

// SetManifestPath sets the "manifest_path" field.
func (feju *FTSExternalJobUpdate) SetManifestPath(s string) *FTSExternalJobUpdate {
	feju.mutation.SetManifestPath(s)
	return feju
}

// SetNillableManifestPath sets the "manifest_path" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableManifestPath(s *string) *FTSExternalJobUpdate {
	if s != nil {
		feju.SetManifestPath(*s)
	}
	return feju
}

// ClearManifestPath clears the value of the "manifest_path" field.
func (feju *FTSExternalJobUpdate) ClearManifestPath() *FTSExternalJobUpdate {
	feju.mutation.ClearManifestPath()
	return feju
}

// SetQualityReport sets the "quality_report" field.
func (feju *FTSExternalJobUpdate) SetQualityReport(s string) *FTSExternalJobUpdate {
	feju.mutation.SetQualityReport(s)
	return feju
}

// SetNillableQualityReport sets the "quality_report" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableQualityReport(s *string) *FTSExternalJobUpdate {
	if s != nil {
		feju.SetQualityReport(*s)
	}
	return feju
}

// ClearQualityReport clears the value of the "quality_report" field.
func (feju *FTSExternalJobUpdate) ClearQualityReport() *FTSExternalJobUpdate {
	feju.mutation.ClearQualityReport()
	return feju
}

// SetRequestedAt sets the "requested_at" field.
func (feju *FTSExternalJobUpdate) SetRequestedAt(t time.Time) *FTSExternalJobUpdate {
	feju.mutation.SetRequestedAt(t)
	return feju
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableRequestedAt(t *time.Time) *FTSExternalJobUpdate {
	if t != nil {
		feju.SetRequestedAt(*t)
	}
	return feju
}

// SetDeadlineAt sets the "deadline_at" field.
func (feju *FTSExternalJobUpdate) SetDeadlineAt(t time.Time) *FTSExternalJobUpdate {
	feju.mutation.SetDeadlineAt(t)
	return feju
}

// SetNillableDeadlineAt sets the "deadline_at" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableDeadlineAt(t *time.Time) *FTSExternalJobUpdate {
	if t != nil {
		feju.SetDeadlineAt(*t)
	}
	return feju
}

// SetCompletedAt sets the "completed_at" field.
func (feju *FTSExternalJobUpdate) SetCompletedAt(t time.Time) *FTSExternalJobUpdate {
	feju.mutation.SetCompletedAt(t)
	return feju
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (feju *FTSExternalJobUpdate) SetNillableCompletedAt(t *time.Time) *FTSExternalJobUpdate {
	if t != nil {
		feju.SetCompletedAt(*t)
	}
	return feju
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (feju *FTSExternalJobUpdate) ClearCompletedAt() *FTSExternalJobUpdate {
	feju.mutation.ClearCompletedAt()
	return feju
}

// Mutation returns the FTSExternalJobMutation object of the builder.
func (feju *FTSExternalJobUpdate) Mutation() *FTSExternalJobMutation {
	return feju.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (feju *FTSExternalJobUpdate) Save(ctx context.Context) (int, error) {
	if err := feju.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, feju.sqlSave, feju.mutation, feju.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (feju *FTSExternalJobUpdate) SaveX(ctx context.Context) int {
	affected, err := feju.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (feju *FTSExternalJobUpdate) Exec(ctx context.Context) error {
	_, err := feju.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (feju *FTSExternalJobUpdate) ExecX(ctx context.Context) {
	if err := feju.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (feju *FTSExternalJobUpdate) defaults() error {
	if _, ok := feju.mutation.UpdatedAt(); !ok {
		if ftsexternaljob.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ftsexternaljob.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ftsexternaljob.UpdateDefaultUpdatedAt()
		feju.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (feju *FTSExternalJobUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ftsexternaljob.Table, ftsexternaljob.Columns, sqlgraph.NewFieldSpec(ftsexternaljob.FieldID, field.TypeInt))
	if ps := feju.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := feju.mutation.UpdatedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := feju.mutation.DeletedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldDeletedAt, field.TypeTime, value)
	}
	if feju.mutation.DeletedAtCleared() {
		_spec.ClearField(ftsexternaljob.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := feju.mutation.RequestID(); ok {
		_spec.SetField(ftsexternaljob.FieldRequestID, field.TypeString, value)
	}
	if value, ok := feju.mutation.Status(); ok {
		_spec.SetField(ftsexternaljob.FieldStatus, field.TypeString, value)
	}
	if value, ok := feju.mutation.FileID(); ok {
		_spec.SetField(ftsexternaljob.FieldFileID, field.TypeInt, value)
	}
	if value, ok := feju.mutation.AddedFileID(); ok {
		_spec.AddField(ftsexternaljob.FieldFileID, field.TypeInt, value)
	}
	if value, ok := feju.mutation.OwnerID(); ok {
		_spec.SetField(ftsexternaljob.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := feju.mutation.AddedOwnerID(); ok {
		_spec.AddField(ftsexternaljob.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := feju.mutation.EntityID(); ok {
		_spec.SetField(ftsexternaljob.FieldEntityID, field.TypeInt, value)
	}
	if value, ok := feju.mutation.AddedEntityID(); ok {
		_spec.AddField(ftsexternaljob.FieldEntityID, field.TypeInt, value)
	}
	if value, ok := feju.mutation.SnapshotToken(); ok {
		_spec.SetField(ftsexternaljob.FieldSnapshotToken, field.TypeString, value)
	}
	if value, ok := feju.mutation.Mode(); ok {
		_spec.SetField(ftsexternaljob.FieldMode, field.TypeString, value)
	}
	if value, ok := feju.mutation.TriggerReason(); ok {
		_spec.SetField(ftsexternaljob.FieldTriggerReason, field.TypeString, value)
	}
	if value, ok := feju.mutation.Attempt(); ok {
		_spec.SetField(ftsexternaljob.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := feju.mutation.AddedAttempt(); ok {
		_spec.AddField(ftsexternaljob.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := feju.mutation.ResultPayload(); ok {
		_spec.SetField(ftsexternaljob.FieldResultPayload, field.TypeString, value)
	}
	if feju.mutation.ResultPayloadCleared() {
		_spec.ClearField(ftsexternaljob.FieldResultPayload, field.TypeString)
	}
	if value, ok := feju.mutation.ErrorPayload(); ok {
		_spec.SetField(ftsexternaljob.FieldErrorPayload, field.TypeString, value)
	}
	if feju.mutation.ErrorPayloadCleared() {
		_spec.ClearField(ftsexternaljob.FieldErrorPayload, field.TypeString)
	}
	if value, ok := feju.mutation.ManifestPath(); ok {
		_spec.SetField(ftsexternaljob.FieldManifestPath, field.TypeString, value)
	}
	if feju.mutation.ManifestPathCleared() {
		_spec.ClearField(ftsexternaljob.FieldManifestPath, field.TypeString)
	}
	if value, ok := feju.mutation.QualityReport(); ok {
		_spec.SetField(ftsexternaljob.FieldQualityReport, field.TypeString, value)
	}
	if feju.mutation.QualityReportCleared() {
		_spec.ClearField(ftsexternaljob.FieldQualityReport, field.TypeString)
	}
	if value, ok := feju.mutation.RequestedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := feju.mutation.DeadlineAt(); ok {
		_spec.SetField(ftsexternaljob.FieldDeadlineAt, field.TypeTime, value)
	}
	if value, ok := feju.mutation.CompletedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldCompletedAt, field.TypeTime, value)
	}
	if feju.mutation.CompletedAtCleared() {
		_spec.ClearField(ftsexternaljob.FieldCompletedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, feju.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ftsexternaljob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	feju.mutation.done = true
	return n, nil
}

// FTSExternalJobUpdateOne is the builder for updating a single FTSExternalJob entity.
type FTSExternalJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FTSExternalJobMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (fejuo *FTSExternalJobUpdateOne) SetUpdatedAt(t time.Time) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetUpdatedAt(t)
	return fejuo
}

// SetDeletedAt sets the "deleted_at" field.
func (fejuo *FTSExternalJobUpdateOne) SetDeletedAt(t time.Time) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetDeletedAt(t)
	return fejuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableDeletedAt(t *time.Time) *FTSExternalJobUpdateOne {
	if t != nil {
		fejuo.SetDeletedAt(*t)
	}
	return fejuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (fejuo *FTSExternalJobUpdateOne) ClearDeletedAt() *FTSExternalJobUpdateOne {
	fejuo.mutation.ClearDeletedAt()
	return fejuo
}

// SetRequestID sets the "request_id" field.
func (fejuo *FTSExternalJobUpdateOne) SetRequestID(s string) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetRequestID(s)
	return fejuo
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableRequestID(s *string) *FTSExternalJobUpdateOne {
	if s != nil {
		fejuo.SetRequestID(*s)
	}
	return fejuo
}

// SetStatus sets the "status" field.
func (fejuo *FTSExternalJobUpdateOne) SetStatus(s string) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetStatus(s)
	return fejuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableStatus(s *string) *FTSExternalJobUpdateOne {
	if s != nil {
		fejuo.SetStatus(*s)
	}
	return fejuo
}

// SetFileID sets the "file_id" field.
func (fejuo *FTSExternalJobUpdateOne) SetFileID(i int) *FTSExternalJobUpdateOne {
	fejuo.mutation.ResetFileID()
	fejuo.mutation.SetFileID(i)
	return fejuo
}

// SetNillableFileID sets the "file_id" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableFileID(i *int) *FTSExternalJobUpdateOne {
	if i != nil {
		fejuo.SetFileID(*i)
	}
	return fejuo
}

// AddFileID adds i to the "file_id" field.
func (fejuo *FTSExternalJobUpdateOne) AddFileID(i int) *FTSExternalJobUpdateOne {
	fejuo.mutation.AddFileID(i)
	return fejuo
}

// SetOwnerID sets the "owner_id" field.
func (fejuo *FTSExternalJobUpdateOne) SetOwnerID(i int) *FTSExternalJobUpdateOne {
	fejuo.mutation.ResetOwnerID()
	fejuo.mutation.SetOwnerID(i)
	return fejuo
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableOwnerID(i *int) *FTSExternalJobUpdateOne {
	if i != nil {
		fejuo.SetOwnerID(*i)
	}
	return fejuo
}

// AddOwnerID adds i to the "owner_id" field.
func (fejuo *FTSExternalJobUpdateOne) AddOwnerID(i int) *FTSExternalJobUpdateOne {
	fejuo.mutation.AddOwnerID(i)
	return fejuo
}

// SetEntityID sets the "entity_id" field.
func (fejuo *FTSExternalJobUpdateOne) SetEntityID(i int) *FTSExternalJobUpdateOne {
	fejuo.mutation.ResetEntityID()
	fejuo.mutation.SetEntityID(i)
	return fejuo
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableEntityID(i *int) *FTSExternalJobUpdateOne {
	if i != nil {
		fejuo.SetEntityID(*i)
	}
	return fejuo
}

// AddEntityID adds i to the "entity_id" field.
func (fejuo *FTSExternalJobUpdateOne) AddEntityID(i int) *FTSExternalJobUpdateOne {
	fejuo.mutation.AddEntityID(i)
	return fejuo
}

// SetSnapshotToken sets the "snapshot_token" field.
func (fejuo *FTSExternalJobUpdateOne) SetSnapshotToken(s string) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetSnapshotToken(s)
	return fejuo
}

// SetNillableSnapshotToken sets the "snapshot_token" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableSnapshotToken(s *string) *FTSExternalJobUpdateOne {
	if s != nil {
		fejuo.SetSnapshotToken(*s)
	}
	return fejuo
}

// SetMode sets the "mode" field.
func (fejuo *FTSExternalJobUpdateOne) SetMode(s string) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetMode(s)
	return fejuo
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableMode(s *string) *FTSExternalJobUpdateOne {
	if s != nil {
		fejuo.SetMode(*s)
	}
	return fejuo
}

// SetTriggerReason sets the "trigger_reason" field.
func (fejuo *FTSExternalJobUpdateOne) SetTriggerReason(s string) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetTriggerReason(s)
	return fejuo
}

// SetNillableTriggerReason sets the "trigger_reason" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableTriggerReason(s *string) *FTSExternalJobUpdateOne {
	if s != nil {
		fejuo.SetTriggerReason(*s)
	}
	return fejuo
}

// SetAttempt sets the "attempt" field.
func (fejuo *FTSExternalJobUpdateOne) SetAttempt(i int) *FTSExternalJobUpdateOne {
	fejuo.mutation.ResetAttempt()
	fejuo.mutation.SetAttempt(i)
	return fejuo
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableAttempt(i *int) *FTSExternalJobUpdateOne {
	if i != nil {
		fejuo.SetAttempt(*i)
	}
	return fejuo
}

// AddAttempt adds i to the "attempt" field.
func (fejuo *FTSExternalJobUpdateOne) AddAttempt(i int) *FTSExternalJobUpdateOne {
	fejuo.mutation.AddAttempt(i)
	return fejuo
}

// SetResultPayload sets the "result_payload" field.
func (fejuo *FTSExternalJobUpdateOne) SetResultPayload(s string) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetResultPayload(s)
	return fejuo
}

// SetNillableResultPayload sets the "result_payload" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableResultPayload(s *string) *FTSExternalJobUpdateOne {
	if s != nil {
		fejuo.SetResultPayload(*s)
	}
	return fejuo
}

// ClearResultPayload clears the value of the "result_payload" field.
func (fejuo *FTSExternalJobUpdateOne) ClearResultPayload() *FTSExternalJobUpdateOne {
	fejuo.mutation.ClearResultPayload()
	return fejuo
}

// SetErrorPayload sets the "error_payload" field.
func (fejuo *FTSExternalJobUpdateOne) SetErrorPayload(s string) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetErrorPayload(s)
	return fejuo
}

// SetNillableErrorPayload sets the "error_payload" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableErrorPayload(s *string) *FTSExternalJobUpdateOne {
	if s != nil {
		fejuo.SetErrorPayload(*s)
	}
	return fejuo
}

// ClearErrorPayload clears the value of the "error_payload" field.
func (fejuo *FTSExternalJobUpdateOne) ClearErrorPayload() *FTSExternalJobUpdateOne {
	fejuo.mutation.ClearErrorPayload()
	return fejuo
}

// SetManifestPath sets the "manifest_path" field.
func (fejuo *FTSExternalJobUpdateOne) SetManifestPath(s string) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetManifestPath(s)
	return fejuo
}

// SetNillableManifestPath sets the "manifest_path" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableManifestPath(s *string) *FTSExternalJobUpdateOne {
	if s != nil {
		fejuo.SetManifestPath(*s)
	}
	return fejuo
}

// ClearManifestPath clears the value of the "manifest_path" field.
func (fejuo *FTSExternalJobUpdateOne) ClearManifestPath() *FTSExternalJobUpdateOne {
	fejuo.mutation.ClearManifestPath()
	return fejuo
}

// SetQualityReport sets the "quality_report" field.
func (fejuo *FTSExternalJobUpdateOne) SetQualityReport(s string) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetQualityReport(s)
	return fejuo
}

// SetNillableQualityReport sets the "quality_report" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableQualityReport(s *string) *FTSExternalJobUpdateOne {
	if s != nil {
		fejuo.SetQualityReport(*s)
	}
	return fejuo
}

// ClearQualityReport clears the value of the "quality_report" field.
func (fejuo *FTSExternalJobUpdateOne) ClearQualityReport() *FTSExternalJobUpdateOne {
	fejuo.mutation.ClearQualityReport()
	return fejuo
}

// SetRequestedAt sets the "requested_at" field.
func (fejuo *FTSExternalJobUpdateOne) SetRequestedAt(t time.Time) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetRequestedAt(t)
	return fejuo
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableRequestedAt(t *time.Time) *FTSExternalJobUpdateOne {
	if t != nil {
		fejuo.SetRequestedAt(*t)
	}
	return fejuo
}

// SetDeadlineAt sets the "deadline_at" field.
func (fejuo *FTSExternalJobUpdateOne) SetDeadlineAt(t time.Time) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetDeadlineAt(t)
	return fejuo
}

// SetNillableDeadlineAt sets the "deadline_at" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableDeadlineAt(t *time.Time) *FTSExternalJobUpdateOne {
	if t != nil {
		fejuo.SetDeadlineAt(*t)
	}
	return fejuo
}

// SetCompletedAt sets the "completed_at" field.
func (fejuo *FTSExternalJobUpdateOne) SetCompletedAt(t time.Time) *FTSExternalJobUpdateOne {
	fejuo.mutation.SetCompletedAt(t)
	return fejuo
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (fejuo *FTSExternalJobUpdateOne) SetNillableCompletedAt(t *time.Time) *FTSExternalJobUpdateOne {
	if t != nil {
		fejuo.SetCompletedAt(*t)
	}
	return fejuo
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (fejuo *FTSExternalJobUpdateOne) ClearCompletedAt() *FTSExternalJobUpdateOne {
	fejuo.mutation.ClearCompletedAt()
	return fejuo
}

// Mutation returns the FTSExternalJobMutation object of the builder.
func (fejuo *FTSExternalJobUpdateOne) Mutation() *FTSExternalJobMutation {
	return fejuo.mutation
}

// Where appends a list predicates to the FTSExternalJobUpdate builder.
func (fejuo *FTSExternalJobUpdateOne) Where(ps ...predicate.FTSExternalJob) *FTSExternalJobUpdateOne {
	fejuo.mutation.Where(ps...)
	return fejuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fejuo *FTSExternalJobUpdateOne) Select(field string, fields ...string) *FTSExternalJobUpdateOne {
	fejuo.fields = append([]string{field}, fields...)
	return fejuo
}

// Save executes the query and returns the updated FTSExternalJob entity.
func (fejuo *FTSExternalJobUpdateOne) Save(ctx context.Context) (*FTSExternalJob, error) {
	if err := fejuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, fejuo.sqlSave, fejuo.mutation, fejuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fejuo *FTSExternalJobUpdateOne) SaveX(ctx context.Context) *FTSExternalJob {
	node, err := fejuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fejuo *FTSExternalJobUpdateOne) Exec(ctx context.Context) error {
	_, err := fejuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fejuo *FTSExternalJobUpdateOne) ExecX(ctx context.Context) {
	if err := fejuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fejuo *FTSExternalJobUpdateOne) defaults() error {
	if _, ok := fejuo.mutation.UpdatedAt(); !ok {
		if ftsexternaljob.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ftsexternaljob.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ftsexternaljob.UpdateDefaultUpdatedAt()
		fejuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (fejuo *FTSExternalJobUpdateOne) sqlSave(ctx context.Context) (_node *FTSExternalJob, err error) {
	_spec := sqlgraph.NewUpdateSpec(ftsexternaljob.Table, ftsexternaljob.Columns, sqlgraph.NewFieldSpec(ftsexternaljob.FieldID, field.TypeInt))
	id, ok := fejuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FTSExternalJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fejuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ftsexternaljob.FieldID)
		for _, f := range fields {
			if !ftsexternaljob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ftsexternaljob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fejuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fejuo.mutation.UpdatedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := fejuo.mutation.DeletedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldDeletedAt, field.TypeTime, value)
	}
	if fejuo.mutation.DeletedAtCleared() {
		_spec.ClearField(ftsexternaljob.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := fejuo.mutation.RequestID(); ok {
		_spec.SetField(ftsexternaljob.FieldRequestID, field.TypeString, value)
	}
	if value, ok := fejuo.mutation.Status(); ok {
		_spec.SetField(ftsexternaljob.FieldStatus, field.TypeString, value)
	}
	if value, ok := fejuo.mutation.FileID(); ok {
		_spec.SetField(ftsexternaljob.FieldFileID, field.TypeInt, value)
	}
	if value, ok := fejuo.mutation.AddedFileID(); ok {
		_spec.AddField(ftsexternaljob.FieldFileID, field.TypeInt, value)
	}
	if value, ok := fejuo.mutation.OwnerID(); ok {
		_spec.SetField(ftsexternaljob.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := fejuo.mutation.AddedOwnerID(); ok {
		_spec.AddField(ftsexternaljob.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := fejuo.mutation.EntityID(); ok {
		_spec.SetField(ftsexternaljob.FieldEntityID, field.TypeInt, value)
	}
	if value, ok := fejuo.mutation.AddedEntityID(); ok {
		_spec.AddField(ftsexternaljob.FieldEntityID, field.TypeInt, value)
	}
	if value, ok := fejuo.mutation.SnapshotToken(); ok {
		_spec.SetField(ftsexternaljob.FieldSnapshotToken, field.TypeString, value)
	}
	if value, ok := fejuo.mutation.Mode(); ok {
		_spec.SetField(ftsexternaljob.FieldMode, field.TypeString, value)
	}
	if value, ok := fejuo.mutation.TriggerReason(); ok {
		_spec.SetField(ftsexternaljob.FieldTriggerReason, field.TypeString, value)
	}
	if value, ok := fejuo.mutation.Attempt(); ok {
		_spec.SetField(ftsexternaljob.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := fejuo.mutation.AddedAttempt(); ok {
		_spec.AddField(ftsexternaljob.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := fejuo.mutation.ResultPayload(); ok {
		_spec.SetField(ftsexternaljob.FieldResultPayload, field.TypeString, value)
	}
	if fejuo.mutation.ResultPayloadCleared() {
		_spec.ClearField(ftsexternaljob.FieldResultPayload, field.TypeString)
	}
	if value, ok := fejuo.mutation.ErrorPayload(); ok {
		_spec.SetField(ftsexternaljob.FieldErrorPayload, field.TypeString, value)
	}
	if fejuo.mutation.ErrorPayloadCleared() {
		_spec.ClearField(ftsexternaljob.FieldErrorPayload, field.TypeString)
	}
	if value, ok := fejuo.mutation.ManifestPath(); ok {
		_spec.SetField(ftsexternaljob.FieldManifestPath, field.TypeString, value)
	}
	if fejuo.mutation.ManifestPathCleared() {
		_spec.ClearField(ftsexternaljob.FieldManifestPath, field.TypeString)
	}
	if value, ok := fejuo.mutation.QualityReport(); ok {
		_spec.SetField(ftsexternaljob.FieldQualityReport, field.TypeString, value)
	}
	if fejuo.mutation.QualityReportCleared() {
		_spec.ClearField(ftsexternaljob.FieldQualityReport, field.TypeString)
	}
	if value, ok := fejuo.mutation.RequestedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := fejuo.mutation.DeadlineAt(); ok {
		_spec.SetField(ftsexternaljob.FieldDeadlineAt, field.TypeTime, value)
	}
	if value, ok := fejuo.mutation.CompletedAt(); ok {
		_spec.SetField(ftsexternaljob.FieldCompletedAt, field.TypeTime, value)
	}
	if fejuo.mutation.CompletedAtCleared() {
		_spec.ClearField(ftsexternaljob.FieldCompletedAt, field.TypeTime)
	}
	_node = &FTSExternalJob{config: fejuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fejuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ftsexternaljob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fejuo.mutation.done = true
	return _node, nil
}
