// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/ftsexternaljob"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// FTSExternalJobQuery is the builder for querying FTSExternalJob entities.
type FTSExternalJobQuery struct {
	config
	ctx        *QueryContext
	order      []ftsexternaljob.OrderOption
	inters     []Interceptor
	predicates []predicate.FTSExternalJob
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FTSExternalJobQuery builder.
func (fejq *FTSExternalJobQuery) Where(ps ...predicate.FTSExternalJob) *FTSExternalJobQuery {
	fejq.predicates = append(fejq.predicates, ps...)
	return fejq
}

// Limit the number of records to be returned by this query.
func (fejq *FTSExternalJobQuery) Limit(limit int) *FTSExternalJobQuery {
	fejq.ctx.Limit = &limit
	return fejq
}

// Offset to start from.
func (fejq *FTSExternalJobQuery) Offset(offset int) *FTSExternalJobQuery {
	fejq.ctx.Offset = &offset
	return fejq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fejq *FTSExternalJobQuery) Unique(unique bool) *FTSExternalJobQuery {
	fejq.ctx.Unique = &unique
	return fejq
}

// Order specifies how the records should be ordered.
func (fejq *FTSExternalJobQuery) Order(o ...ftsexternaljob.OrderOption) *FTSExternalJobQuery {
	fejq.order = append(fejq.order, o...)
	return fejq
}

// First returns the first FTSExternalJob entity from the query.
// Returns a *NotFoundError when no FTSExternalJob was found.
func (fejq *FTSExternalJobQuery) First(ctx context.Context) (*FTSExternalJob, error) {
	nodes, err := fejq.Limit(1).All(setContextOp(ctx, fejq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ftsexternaljob.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fejq *FTSExternalJobQuery) FirstX(ctx context.Context) *FTSExternalJob {
	node, err := fejq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FTSExternalJob ID from the query.
// Returns a *NotFoundError when no FTSExternalJob ID was found.
func (fejq *FTSExternalJobQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fejq.Limit(1).IDs(setContextOp(ctx, fejq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ftsexternaljob.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fejq *FTSExternalJobQuery) FirstIDX(ctx context.Context) int {
	id, err := fejq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FTSExternalJob entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FTSExternalJob entity is found.
// Returns a *NotFoundError when no FTSExternalJob entities are found.
func (fejq *FTSExternalJobQuery) Only(ctx context.Context) (*FTSExternalJob, error) {
	nodes, err := fejq.Limit(2).All(setContextOp(ctx, fejq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ftsexternaljob.Label}
	default:
		return nil, &NotSingularError{ftsexternaljob.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fejq *FTSExternalJobQuery) OnlyX(ctx context.Context) *FTSExternalJob {
	node, err := fejq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FTSExternalJob ID in the query.
// Returns a *NotSingularError when more than one FTSExternalJob ID is found.
// Returns a *NotFoundError when no entities are found.
func (fejq *FTSExternalJobQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fejq.Limit(2).IDs(setContextOp(ctx, fejq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ftsexternaljob.Label}
	default:
		err = &NotSingularError{ftsexternaljob.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fejq *FTSExternalJobQuery) OnlyIDX(ctx context.Context) int {
	id, err := fejq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FTSExternalJobs.
func (fejq *FTSExternalJobQuery) All(ctx context.Context) ([]*FTSExternalJob, error) {
	ctx = setContextOp(ctx, fejq.ctx, "All")
	if err := fejq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FTSExternalJob, *FTSExternalJobQuery]()
	return withInterceptors[[]*FTSExternalJob](ctx, fejq, qr, fejq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fejq *FTSExternalJobQuery) AllX(ctx context.Context) []*FTSExternalJob {
	nodes, err := fejq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FTSExternalJob IDs.
func (fejq *FTSExternalJobQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fejq.ctx.Unique == nil && fejq.path != nil {
		fejq.Unique(true)
	}
	ctx = setContextOp(ctx, fejq.ctx, "IDs")
	if err = fejq.Select(ftsexternaljob.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fejq *FTSExternalJobQuery) IDsX(ctx context.Context) []int {
	ids, err := fejq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fejq *FTSExternalJobQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fejq.ctx, "Count")
	if err := fejq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fejq, querierCount[*FTSExternalJobQuery](), fejq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fejq *FTSExternalJobQuery) CountX(ctx context.Context) int {
	count, err := fejq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fejq *FTSExternalJobQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fejq.ctx, "Exist")
	switch _, err := fejq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fejq *FTSExternalJobQuery) ExistX(ctx context.Context) bool {
	exist, err := fejq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FTSExternalJobQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fejq *FTSExternalJobQuery) Clone() *FTSExternalJobQuery {
	if fejq == nil {
		return nil
	}
	return &FTSExternalJobQuery{
		config:     fejq.config,
		ctx:        fejq.ctx.Clone(),
		order:      append([]ftsexternaljob.OrderOption{}, fejq.order...),
		inters:     append([]Interceptor{}, fejq.inters...),
		predicates: append([]predicate.FTSExternalJob{}, fejq.predicates...),
		// clone intermediate query.
		sql:  fejq.sql.Clone(),
		path: fejq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FTSExternalJob.Query().
//		GroupBy(ftsexternaljob.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fejq *FTSExternalJobQuery) GroupBy(field string, fields ...string) *FTSExternalJobGroupBy {
	fejq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FTSExternalJobGroupBy{build: fejq}
	grbuild.flds = &fejq.ctx.Fields
	grbuild.label = ftsexternaljob.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.FTSExternalJob.Query().
//		Select(ftsexternaljob.FieldCreatedAt).
//		Scan(ctx, &v)
func (fejq *FTSExternalJobQuery) Select(fields ...string) *FTSExternalJobSelect {
	fejq.ctx.Fields = append(fejq.ctx.Fields, fields...)
	sbuild := &FTSExternalJobSelect{FTSExternalJobQuery: fejq}
	sbuild.label = ftsexternaljob.Label
	sbuild.flds, sbuild.scan = &fejq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FTSExternalJobSelect configured with the given aggregations.
func (fejq *FTSExternalJobQuery) Aggregate(fns ...AggregateFunc) *FTSExternalJobSelect {
	return fejq.Select().Aggregate(fns...)
}

func (fejq *FTSExternalJobQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fejq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fejq); err != nil {
				return err
			}
		}
	}
	for _, f := range fejq.ctx.Fields {
		if !ftsexternaljob.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fejq.path != nil {
		prev, err := fejq.path(ctx)
		if err != nil {
			return err
		}
		fejq.sql = prev
	}
	return nil
}

func (fejq *FTSExternalJobQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FTSExternalJob, error) {
	var (
		nodes = []*FTSExternalJob{}
		_spec = fejq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FTSExternalJob).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FTSExternalJob{config: fejq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fejq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (fejq *FTSExternalJobQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fejq.querySpec()
	_spec.Node.Columns = fejq.ctx.Fields
	if len(fejq.ctx.Fields) > 0 {
		_spec.Unique = fejq.ctx.Unique != nil && *fejq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fejq.driver, _spec)
}

func (fejq *FTSExternalJobQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ftsexternaljob.Table, ftsexternaljob.Columns, sqlgraph.NewFieldSpec(ftsexternaljob.FieldID, field.TypeInt))
	_spec.From = fejq.sql
	if unique := fejq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fejq.path != nil {
		_spec.Unique = true
	}
	if fields := fejq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ftsexternaljob.FieldID)
		for i := range fields {
			if fields[i] != ftsexternaljob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fejq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fejq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fejq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fejq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fejq *FTSExternalJobQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fejq.driver.Dialect())
	t1 := builder.Table(ftsexternaljob.Table)
	columns := fejq.ctx.Fields
	if len(columns) == 0 {
		columns = ftsexternaljob.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fejq.sql != nil {
		selector = fejq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fejq.ctx.Unique != nil && *fejq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fejq.predicates {
		p(selector)
	}
	for _, p := range fejq.order {
		p(selector)
	}
	if offset := fejq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fejq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FTSExternalJobGroupBy is the group-by builder for FTSExternalJob entities.
type FTSExternalJobGroupBy struct {
	selector
	build *FTSExternalJobQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fejgb *FTSExternalJobGroupBy) Aggregate(fns ...AggregateFunc) *FTSExternalJobGroupBy {
	fejgb.fns = append(fejgb.fns, fns...)
	return fejgb
}

// Scan applies the selector query and scans the result into the given value.
func (fejgb *FTSExternalJobGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fejgb.build.ctx, "GroupBy")
	if err := fejgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FTSExternalJobQuery, *FTSExternalJobGroupBy](ctx, fejgb.build, fejgb, fejgb.build.inters, v)
}

func (fejgb *FTSExternalJobGroupBy) sqlScan(ctx context.Context, root *FTSExternalJobQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fejgb.fns))
	for _, fn := range fejgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fejgb.flds)+len(fejgb.fns))
		for _, f := range *fejgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fejgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fejgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FTSExternalJobSelect is the builder for selecting fields of FTSExternalJob entities.
type FTSExternalJobSelect struct {
	*FTSExternalJobQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fejs *FTSExternalJobSelect) Aggregate(fns ...AggregateFunc) *FTSExternalJobSelect {
	fejs.fns = append(fejs.fns, fns...)
	return fejs
}

// Scan applies the selector query and scans the result into the given value.
func (fejs *FTSExternalJobSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fejs.ctx, "Select")
	if err := fejs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FTSExternalJobQuery, *FTSExternalJobSelect](ctx, fejs.FTSExternalJobQuery, fejs, fejs.inters, v)
}

func (fejs *FTSExternalJobSelect) sqlScan(ctx context.Context, root *FTSExternalJobQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fejs.fns))
	for _, fn := range fejs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fejs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fejs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
