// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/ftsexternaljob"
)

// FTSExternalJob is the model entity for the FTSExternalJob schema.
type FTSExternalJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// FileID holds the value of the "file_id" field.
	FileID int `json:"file_id,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID int `json:"owner_id,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID int `json:"entity_id,omitempty"`
	// SnapshotToken holds the value of the "snapshot_token" field.
	SnapshotToken string `json:"snapshot_token,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// TriggerReason holds the value of the "trigger_reason" field.
	TriggerReason string `json:"trigger_reason,omitempty"`
	// Attempt holds the value of the "attempt" field.
	Attempt int `json:"attempt,omitempty"`
	// ResultPayload holds the value of the "result_payload" field.
	ResultPayload string `json:"result_payload,omitempty"`
	// ErrorPayload holds the value of the "error_payload" field.
	ErrorPayload string `json:"error_payload,omitempty"`
	// ManifestPath holds the value of the "manifest_path" field.
	ManifestPath string `json:"manifest_path,omitempty"`
	// QualityReport holds the value of the "quality_report" field.
	QualityReport string `json:"quality_report,omitempty"`
	// RequestedAt holds the value of the "requested_at" field.
	RequestedAt time.Time `json:"requested_at,omitempty"`
	// DeadlineAt holds the value of the "deadline_at" field.
	DeadlineAt time.Time `json:"deadline_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FTSExternalJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ftsexternaljob.FieldID, ftsexternaljob.FieldFileID, ftsexternaljob.FieldOwnerID, ftsexternaljob.FieldEntityID, ftsexternaljob.FieldAttempt:
			values[i] = new(sql.NullInt64)
		case ftsexternaljob.FieldRequestID, ftsexternaljob.FieldStatus, ftsexternaljob.FieldSnapshotToken, ftsexternaljob.FieldMode, ftsexternaljob.FieldTriggerReason, ftsexternaljob.FieldResultPayload, ftsexternaljob.FieldErrorPayload, ftsexternaljob.FieldManifestPath, ftsexternaljob.FieldQualityReport:
			values[i] = new(sql.NullString)
		case ftsexternaljob.FieldCreatedAt, ftsexternaljob.FieldUpdatedAt, ftsexternaljob.FieldDeletedAt, ftsexternaljob.FieldRequestedAt, ftsexternaljob.FieldDeadlineAt, ftsexternaljob.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FTSExternalJob fields.
func (fej *FTSExternalJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ftsexternaljob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			fej.ID = int(value.Int64)
		case ftsexternaljob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				fej.CreatedAt = value.Time
			}
		case ftsexternaljob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				fej.UpdatedAt = value.Time
			}
		case ftsexternaljob.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				fej.DeletedAt = new(time.Time)
				*fej.DeletedAt = value.Time
			}
		case ftsexternaljob.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				fej.RequestID = value.String
			}
		case ftsexternaljob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				fej.Status = value.String
			}
		case ftsexternaljob.FieldFileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_id", values[i])
			} else if value.Valid {
				fej.FileID = int(value.Int64)
			}
		case ftsexternaljob.FieldOwnerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				fej.OwnerID = int(value.Int64)
			}
		case ftsexternaljob.FieldEntityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value.Valid {
				fej.EntityID = int(value.Int64)
			}
		case ftsexternaljob.FieldSnapshotToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_token", values[i])
			} else if value.Valid {
				fej.SnapshotToken = value.String
			}
		case ftsexternaljob.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				fej.Mode = value.String
			}
		case ftsexternaljob.FieldTriggerReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_reason", values[i])
			} else if value.Valid {
				fej.TriggerReason = value.String
			}
		case ftsexternaljob.FieldAttempt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt", values[i])
			} else if value.Valid {
				fej.Attempt = int(value.Int64)
			}
		case ftsexternaljob.FieldResultPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_payload", values[i])
			} else if value.Valid {
				fej.ResultPayload = value.String
			}
		case ftsexternaljob.FieldErrorPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_payload", values[i])
			} else if value.Valid {
				fej.ErrorPayload = value.String
			}
		case ftsexternaljob.FieldManifestPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manifest_path", values[i])
			} else if value.Valid {
				fej.ManifestPath = value.String
			}
		case ftsexternaljob.FieldQualityReport:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality_report", values[i])
			} else if value.Valid {
				fej.QualityReport = value.String
			}
		case ftsexternaljob.FieldRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field requested_at", values[i])
			} else if value.Valid {
				fej.RequestedAt = value.Time
			}
		case ftsexternaljob.FieldDeadlineAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deadline_at", values[i])
			} else if value.Valid {
				fej.DeadlineAt = value.Time
			}
		case ftsexternaljob.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				fej.CompletedAt = new(time.Time)
				*fej.CompletedAt = value.Time
			}
		default:
			fej.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FTSExternalJob.
// This includes values selected through modifiers, order, etc.
func (fej *FTSExternalJob) Value(name string) (ent.Value, error) {
	return fej.selectValues.Get(name)
}

// Update returns a builder for updating this FTSExternalJob.
// Note that you need to call FTSExternalJob.Unwrap() before calling this method if this FTSExternalJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (fej *FTSExternalJob) Update() *FTSExternalJobUpdateOne {
	return NewFTSExternalJobClient(fej.config).UpdateOne(fej)
}

// Unwrap unwraps the FTSExternalJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (fej *FTSExternalJob) Unwrap() *FTSExternalJob {
	_tx, ok := fej.config.driver.(*txDriver)
	if !ok {
		panic("ent: FTSExternalJob is not a transactional entity")
	}
	fej.config.driver = _tx.drv
	return fej
}

// String implements the fmt.Stringer.
func (fej *FTSExternalJob) String() string {
	var builder strings.Builder
	builder.WriteString("FTSExternalJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", fej.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fej.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fej.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := fej.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(fej.RequestID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fej.Status)
	builder.WriteString(", ")
	builder.WriteString("file_id=")
	builder.WriteString(fmt.Sprintf("%v", fej.FileID))
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", fej.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(fmt.Sprintf("%v", fej.EntityID))
	builder.WriteString(", ")
	builder.WriteString("snapshot_token=")
	builder.WriteString(fej.SnapshotToken)
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(fej.Mode)
	builder.WriteString(", ")
	builder.WriteString("trigger_reason=")
	builder.WriteString(fej.TriggerReason)
	builder.WriteString(", ")
	builder.WriteString("attempt=")
	builder.WriteString(fmt.Sprintf("%v", fej.Attempt))
	builder.WriteString(", ")
	builder.WriteString("result_payload=")
	builder.WriteString(fej.ResultPayload)
	builder.WriteString(", ")
	builder.WriteString("error_payload=")
	builder.WriteString(fej.ErrorPayload)
	builder.WriteString(", ")
	builder.WriteString("manifest_path=")
	builder.WriteString(fej.ManifestPath)
	builder.WriteString(", ")
	builder.WriteString("quality_report=")
	builder.WriteString(fej.QualityReport)
	builder.WriteString(", ")
	builder.WriteString("requested_at=")
	builder.WriteString(fej.RequestedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deadline_at=")
	builder.WriteString(fej.DeadlineAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := fej.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// FTSExternalJobs is a parsable slice of FTSExternalJob.
type FTSExternalJobs []*FTSExternalJob
