// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/syncthingdevice"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SyncthingDevice is the model entity for the SyncthingDevice schema.
type SyncthingDevice struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID int `json:"owner_id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID string `json:"device_id,omitempty"`
	// ShortID holds the value of the "short_id" field.
	ShortID string `json:"short_id,omitempty"`
	// LastIP holds the value of the "last_ip" field.
	LastIP string `json:"last_ip,omitempty"`
	// APIKey holds the value of the "api_key" field.
	APIKey string `json:"-"`
	// JSONRaw holds the value of the "json_raw" field.
	JSONRaw map[string]interface{} `json:"json_raw,omitempty"`
	// BindURI holds the value of the "bind_uri" field.
	BindURI string `json:"bind_uri,omitempty"`
	// ClientVersion holds the value of the "client_version" field.
	ClientVersion string `json:"client_version,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`
	// LastSyncAt holds the value of the "last_sync_at" field.
	LastSyncAt *time.Time `json:"last_sync_at,omitempty"`
	// Online holds the value of the "online" field.
	Online bool `json:"online,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SyncthingDeviceQuery when eager-loading is set.
	Edges        SyncthingDeviceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SyncthingDeviceEdges holds the relations/edges for other nodes in the graph.
type SyncthingDeviceEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SyncthingDeviceEdges) OwnerOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SyncthingDevice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case syncthingdevice.FieldJSONRaw:
			values[i] = new([]byte)
		case syncthingdevice.FieldOnline:
			values[i] = new(sql.NullBool)
		case syncthingdevice.FieldID, syncthingdevice.FieldOwnerID:
			values[i] = new(sql.NullInt64)
		case syncthingdevice.FieldDeviceID, syncthingdevice.FieldShortID, syncthingdevice.FieldLastIP, syncthingdevice.FieldAPIKey, syncthingdevice.FieldBindURI, syncthingdevice.FieldClientVersion, syncthingdevice.FieldPlatform:
			values[i] = new(sql.NullString)
		case syncthingdevice.FieldCreatedAt, syncthingdevice.FieldUpdatedAt, syncthingdevice.FieldDeletedAt, syncthingdevice.FieldLastSeenAt, syncthingdevice.FieldLastSyncAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SyncthingDevice fields.
func (sd *SyncthingDevice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case syncthingdevice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sd.ID = int(value.Int64)
		case syncthingdevice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sd.CreatedAt = value.Time
			}
		case syncthingdevice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sd.UpdatedAt = value.Time
			}
		case syncthingdevice.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				sd.DeletedAt = new(time.Time)
				*sd.DeletedAt = value.Time
			}
		case syncthingdevice.FieldOwnerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				sd.OwnerID = int(value.Int64)
			}
		case syncthingdevice.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				sd.DeviceID = value.String
			}
		case syncthingdevice.FieldShortID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field short_id", values[i])
			} else if value.Valid {
				sd.ShortID = value.String
			}
		case syncthingdevice.FieldLastIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_ip", values[i])
			} else if value.Valid {
				sd.LastIP = value.String
			}
		case syncthingdevice.FieldAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key", values[i])
			} else if value.Valid {
				sd.APIKey = value.String
			}
		case syncthingdevice.FieldJSONRaw:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field json_raw", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &sd.JSONRaw); err != nil {
					return fmt.Errorf("unmarshal field json_raw: %w", err)
				}
			}
		case syncthingdevice.FieldBindURI:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bind_uri", values[i])
			} else if value.Valid {
				sd.BindURI = value.String
			}
		case syncthingdevice.FieldClientVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_version", values[i])
			} else if value.Valid {
				sd.ClientVersion = value.String
			}
		case syncthingdevice.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				sd.Platform = value.String
			}
		case syncthingdevice.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				sd.LastSeenAt = new(time.Time)
				*sd.LastSeenAt = value.Time
			}
		case syncthingdevice.FieldLastSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_at", values[i])
			} else if value.Valid {
				sd.LastSyncAt = new(time.Time)
				*sd.LastSyncAt = value.Time
			}
		case syncthingdevice.FieldOnline:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field online", values[i])
			} else if value.Valid {
				sd.Online = value.Bool
			}
		default:
			sd.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SyncthingDevice.
// This includes values selected through modifiers, order, etc.
func (sd *SyncthingDevice) Value(name string) (ent.Value, error) {
	return sd.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the SyncthingDevice entity.
func (sd *SyncthingDevice) QueryOwner() *UserQuery {
	return NewSyncthingDeviceClient(sd.config).QueryOwner(sd)
}

// Update returns a builder for updating this SyncthingDevice.
// Note that you need to call SyncthingDevice.Unwrap() before calling this method if this SyncthingDevice
// was returned from a transaction, and the transaction was committed or rolled back.
func (sd *SyncthingDevice) Update() *SyncthingDeviceUpdateOne {
	return NewSyncthingDeviceClient(sd.config).UpdateOne(sd)
}

// Unwrap unwraps the SyncthingDevice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sd *SyncthingDevice) Unwrap() *SyncthingDevice {
	_tx, ok := sd.config.driver.(*txDriver)
	if !ok {
		panic("ent: SyncthingDevice is not a transactional entity")
	}
	sd.config.driver = _tx.drv
	return sd
}

// String implements the fmt.Stringer.
func (sd *SyncthingDevice) String() string {
	var builder strings.Builder
	builder.WriteString("SyncthingDevice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sd.ID))
	builder.WriteString("created_at=")
	builder.WriteString(sd.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(sd.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := sd.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", sd.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(sd.DeviceID)
	builder.WriteString(", ")
	builder.WriteString("short_id=")
	builder.WriteString(sd.ShortID)
	builder.WriteString(", ")
	builder.WriteString("last_ip=")
	builder.WriteString(sd.LastIP)
	builder.WriteString(", ")
	builder.WriteString("api_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("json_raw=")
	builder.WriteString(fmt.Sprintf("%v", sd.JSONRaw))
	builder.WriteString(", ")
	builder.WriteString("bind_uri=")
	builder.WriteString(sd.BindURI)
	builder.WriteString(", ")
	builder.WriteString("client_version=")
	builder.WriteString(sd.ClientVersion)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(sd.Platform)
	builder.WriteString(", ")
	if v := sd.LastSeenAt; v != nil {
		builder.WriteString("last_seen_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := sd.LastSyncAt; v != nil {
		builder.WriteString("last_sync_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("online=")
	builder.WriteString(fmt.Sprintf("%v", sd.Online))
	builder.WriteByte(')')
	return builder.String()
}

// SetOwner manually set the edge as loaded state.
func (e *SyncthingDevice) SetOwner(v *User) {
	e.Edges.Owner = v
	e.Edges.loadedTypes[0] = true
}

// SyncthingDevices is a parsable slice of SyncthingDevice.
type SyncthingDevices []*SyncthingDevice
