// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/syncthingdevice"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SyncthingDeviceCreate is the builder for creating a SyncthingDevice entity.
type SyncthingDeviceCreate struct {
	config
	mutation *SyncthingDeviceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (sdc *SyncthingDeviceCreate) SetCreatedAt(t time.Time) *SyncthingDeviceCreate {
	sdc.mutation.SetCreatedAt(t)
	return sdc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillableCreatedAt(t *time.Time) *SyncthingDeviceCreate {
	if t != nil {
		sdc.SetCreatedAt(*t)
	}
	return sdc
}

// SetUpdatedAt sets the "updated_at" field.
func (sdc *SyncthingDeviceCreate) SetUpdatedAt(t time.Time) *SyncthingDeviceCreate {
	sdc.mutation.SetUpdatedAt(t)
	return sdc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillableUpdatedAt(t *time.Time) *SyncthingDeviceCreate {
	if t != nil {
		sdc.SetUpdatedAt(*t)
	}
	return sdc
}

// SetDeletedAt sets the "deleted_at" field.
func (sdc *SyncthingDeviceCreate) SetDeletedAt(t time.Time) *SyncthingDeviceCreate {
	sdc.mutation.SetDeletedAt(t)
	return sdc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillableDeletedAt(t *time.Time) *SyncthingDeviceCreate {
	if t != nil {
		sdc.SetDeletedAt(*t)
	}
	return sdc
}

// SetOwnerID sets the "owner_id" field.
func (sdc *SyncthingDeviceCreate) SetOwnerID(i int) *SyncthingDeviceCreate {
	sdc.mutation.SetOwnerID(i)
	return sdc
}

// SetDeviceID sets the "device_id" field.
func (sdc *SyncthingDeviceCreate) SetDeviceID(s string) *SyncthingDeviceCreate {
	sdc.mutation.SetDeviceID(s)
	return sdc
}

// SetShortID sets the "short_id" field.
func (sdc *SyncthingDeviceCreate) SetShortID(s string) *SyncthingDeviceCreate {
	sdc.mutation.SetShortID(s)
	return sdc
}

// SetNillableShortID sets the "short_id" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillableShortID(s *string) *SyncthingDeviceCreate {
	if s != nil {
		sdc.SetShortID(*s)
	}
	return sdc
}

// SetLastIP sets the "last_ip" field.
func (sdc *SyncthingDeviceCreate) SetLastIP(s string) *SyncthingDeviceCreate {
	sdc.mutation.SetLastIP(s)
	return sdc
}

// SetNillableLastIP sets the "last_ip" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillableLastIP(s *string) *SyncthingDeviceCreate {
	if s != nil {
		sdc.SetLastIP(*s)
	}
	return sdc
}

// SetAPIKey sets the "api_key" field.
func (sdc *SyncthingDeviceCreate) SetAPIKey(s string) *SyncthingDeviceCreate {
	sdc.mutation.SetAPIKey(s)
	return sdc
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillableAPIKey(s *string) *SyncthingDeviceCreate {
	if s != nil {
		sdc.SetAPIKey(*s)
	}
	return sdc
}

// SetJSONRaw sets the "json_raw" field.
func (sdc *SyncthingDeviceCreate) SetJSONRaw(m map[string]interface{}) *SyncthingDeviceCreate {
	sdc.mutation.SetJSONRaw(m)
	return sdc
}

// SetBindURI sets the "bind_uri" field.
func (sdc *SyncthingDeviceCreate) SetBindURI(s string) *SyncthingDeviceCreate {
	sdc.mutation.SetBindURI(s)
	return sdc
}

// SetNillableBindURI sets the "bind_uri" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillableBindURI(s *string) *SyncthingDeviceCreate {
	if s != nil {
		sdc.SetBindURI(*s)
	}
	return sdc
}

// SetClientVersion sets the "client_version" field.
func (sdc *SyncthingDeviceCreate) SetClientVersion(s string) *SyncthingDeviceCreate {
	sdc.mutation.SetClientVersion(s)
	return sdc
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillableClientVersion(s *string) *SyncthingDeviceCreate {
	if s != nil {
		sdc.SetClientVersion(*s)
	}
	return sdc
}

// SetPlatform sets the "platform" field.
func (sdc *SyncthingDeviceCreate) SetPlatform(s string) *SyncthingDeviceCreate {
	sdc.mutation.SetPlatform(s)
	return sdc
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillablePlatform(s *string) *SyncthingDeviceCreate {
	if s != nil {
		sdc.SetPlatform(*s)
	}
	return sdc
}

// SetLastSeenAt sets the "last_seen_at" field.
func (sdc *SyncthingDeviceCreate) SetLastSeenAt(t time.Time) *SyncthingDeviceCreate {
	sdc.mutation.SetLastSeenAt(t)
	return sdc
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillableLastSeenAt(t *time.Time) *SyncthingDeviceCreate {
	if t != nil {
		sdc.SetLastSeenAt(*t)
	}
	return sdc
}

// SetLastSyncAt sets the "last_sync_at" field.
func (sdc *SyncthingDeviceCreate) SetLastSyncAt(t time.Time) *SyncthingDeviceCreate {
	sdc.mutation.SetLastSyncAt(t)
	return sdc
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillableLastSyncAt(t *time.Time) *SyncthingDeviceCreate {
	if t != nil {
		sdc.SetLastSyncAt(*t)
	}
	return sdc
}

// SetOnline sets the "online" field.
func (sdc *SyncthingDeviceCreate) SetOnline(b bool) *SyncthingDeviceCreate {
	sdc.mutation.SetOnline(b)
	return sdc
}

// SetNillableOnline sets the "online" field if the given value is not nil.
func (sdc *SyncthingDeviceCreate) SetNillableOnline(b *bool) *SyncthingDeviceCreate {
	if b != nil {
		sdc.SetOnline(*b)
	}
	return sdc
}

// SetOwner sets the "owner" edge to the User entity.
func (sdc *SyncthingDeviceCreate) SetOwner(u *User) *SyncthingDeviceCreate {
	return sdc.SetOwnerID(u.ID)
}

// Mutation returns the SyncthingDeviceMutation object of the builder.
func (sdc *SyncthingDeviceCreate) Mutation() *SyncthingDeviceMutation {
	return sdc.mutation
}

// Save creates the SyncthingDevice in the database.
func (sdc *SyncthingDeviceCreate) Save(ctx context.Context) (*SyncthingDevice, error) {
	if err := sdc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, sdc.sqlSave, sdc.mutation, sdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sdc *SyncthingDeviceCreate) SaveX(ctx context.Context) *SyncthingDevice {
	v, err := sdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sdc *SyncthingDeviceCreate) Exec(ctx context.Context) error {
	_, err := sdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sdc *SyncthingDeviceCreate) ExecX(ctx context.Context) {
	if err := sdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sdc *SyncthingDeviceCreate) defaults() error {
	if _, ok := sdc.mutation.CreatedAt(); !ok {
		if syncthingdevice.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized syncthingdevice.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := syncthingdevice.DefaultCreatedAt()
		sdc.mutation.SetCreatedAt(v)
	}
	if _, ok := sdc.mutation.UpdatedAt(); !ok {
		if syncthingdevice.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized syncthingdevice.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := syncthingdevice.DefaultUpdatedAt()
		sdc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sdc.mutation.JSONRaw(); !ok {
		v := syncthingdevice.DefaultJSONRaw
		sdc.mutation.SetJSONRaw(v)
	}
	if _, ok := sdc.mutation.Online(); !ok {
		v := syncthingdevice.DefaultOnline
		sdc.mutation.SetOnline(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (sdc *SyncthingDeviceCreate) check() error {
	if _, ok := sdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SyncthingDevice.created_at"`)}
	}
	if _, ok := sdc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SyncthingDevice.updated_at"`)}
	}
	if _, ok := sdc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "SyncthingDevice.owner_id"`)}
	}
	if _, ok := sdc.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "SyncthingDevice.device_id"`)}
	}
	if v, ok := sdc.mutation.DeviceID(); ok {
		if err := syncthingdevice.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.device_id": %w`, err)}
		}
	}
	if v, ok := sdc.mutation.ShortID(); ok {
		if err := syncthingdevice.ShortIDValidator(v); err != nil {
			return &ValidationError{Name: "short_id", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.short_id": %w`, err)}
		}
	}
	if v, ok := sdc.mutation.LastIP(); ok {
		if err := syncthingdevice.LastIPValidator(v); err != nil {
			return &ValidationError{Name: "last_ip", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.last_ip": %w`, err)}
		}
	}
	if v, ok := sdc.mutation.APIKey(); ok {
		if err := syncthingdevice.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.api_key": %w`, err)}
		}
	}
	if v, ok := sdc.mutation.BindURI(); ok {
		if err := syncthingdevice.BindURIValidator(v); err != nil {
			return &ValidationError{Name: "bind_uri", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.bind_uri": %w`, err)}
		}
	}
	if v, ok := sdc.mutation.ClientVersion(); ok {
		if err := syncthingdevice.ClientVersionValidator(v); err != nil {
			return &ValidationError{Name: "client_version", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.client_version": %w`, err)}
		}
	}
	if v, ok := sdc.mutation.Platform(); ok {
		if err := syncthingdevice.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.platform": %w`, err)}
		}
	}
	if _, ok := sdc.mutation.Online(); !ok {
		return &ValidationError{Name: "online", err: errors.New(`ent: missing required field "SyncthingDevice.online"`)}
	}
	if _, ok := sdc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "SyncthingDevice.owner"`)}
	}
	return nil
}

func (sdc *SyncthingDeviceCreate) sqlSave(ctx context.Context) (*SyncthingDevice, error) {
	if err := sdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sdc.mutation.id = &_node.ID
	sdc.mutation.done = true
	return _node, nil
}

func (sdc *SyncthingDeviceCreate) createSpec() (*SyncthingDevice, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncthingDevice{config: sdc.config}
		_spec = sqlgraph.NewCreateSpec(syncthingdevice.Table, sqlgraph.NewFieldSpec(syncthingdevice.FieldID, field.TypeInt))
	)

	if id, ok := sdc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = sdc.conflict
	if value, ok := sdc.mutation.CreatedAt(); ok {
		_spec.SetField(syncthingdevice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sdc.mutation.UpdatedAt(); ok {
		_spec.SetField(syncthingdevice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sdc.mutation.DeletedAt(); ok {
		_spec.SetField(syncthingdevice.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := sdc.mutation.DeviceID(); ok {
		_spec.SetField(syncthingdevice.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := sdc.mutation.ShortID(); ok {
		_spec.SetField(syncthingdevice.FieldShortID, field.TypeString, value)
		_node.ShortID = value
	}
	if value, ok := sdc.mutation.LastIP(); ok {
		_spec.SetField(syncthingdevice.FieldLastIP, field.TypeString, value)
		_node.LastIP = value
	}
	if value, ok := sdc.mutation.APIKey(); ok {
		_spec.SetField(syncthingdevice.FieldAPIKey, field.TypeString, value)
		_node.APIKey = value
	}
	if value, ok := sdc.mutation.JSONRaw(); ok {
		_spec.SetField(syncthingdevice.FieldJSONRaw, field.TypeJSON, value)
		_node.JSONRaw = value
	}
	if value, ok := sdc.mutation.BindURI(); ok {
		_spec.SetField(syncthingdevice.FieldBindURI, field.TypeString, value)
		_node.BindURI = value
	}
	if value, ok := sdc.mutation.ClientVersion(); ok {
		_spec.SetField(syncthingdevice.FieldClientVersion, field.TypeString, value)
		_node.ClientVersion = value
	}
	if value, ok := sdc.mutation.Platform(); ok {
		_spec.SetField(syncthingdevice.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := sdc.mutation.LastSeenAt(); ok {
		_spec.SetField(syncthingdevice.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = &value
	}
	if value, ok := sdc.mutation.LastSyncAt(); ok {
		_spec.SetField(syncthingdevice.FieldLastSyncAt, field.TypeTime, value)
		_node.LastSyncAt = &value
	}
	if value, ok := sdc.mutation.Online(); ok {
		_spec.SetField(syncthingdevice.FieldOnline, field.TypeBool, value)
		_node.Online = value
	}
	if nodes := sdc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncthingdevice.OwnerTable,
			Columns: []string{syncthingdevice.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SyncthingDevice.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SyncthingDeviceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (sdc *SyncthingDeviceCreate) OnConflict(opts ...sql.ConflictOption) *SyncthingDeviceUpsertOne {
	sdc.conflict = opts
	return &SyncthingDeviceUpsertOne{
		create: sdc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SyncthingDevice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sdc *SyncthingDeviceCreate) OnConflictColumns(columns ...string) *SyncthingDeviceUpsertOne {
	sdc.conflict = append(sdc.conflict, sql.ConflictColumns(columns...))
	return &SyncthingDeviceUpsertOne{
		create: sdc,
	}
}

type (
	// SyncthingDeviceUpsertOne is the builder for "upsert"-ing
	//  one SyncthingDevice node.
	SyncthingDeviceUpsertOne struct {
		create *SyncthingDeviceCreate
	}

	// SyncthingDeviceUpsert is the "OnConflict" setter.
	SyncthingDeviceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SyncthingDeviceUpsert) SetUpdatedAt(v time.Time) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateUpdatedAt() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SyncthingDeviceUpsert) SetDeletedAt(v time.Time) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateDeletedAt() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SyncthingDeviceUpsert) ClearDeletedAt() *SyncthingDeviceUpsert {
	u.SetNull(syncthingdevice.FieldDeletedAt)
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *SyncthingDeviceUpsert) SetOwnerID(v int) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldOwnerID, v)
	return u
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateOwnerID() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldOwnerID)
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *SyncthingDeviceUpsert) SetDeviceID(v string) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateDeviceID() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldDeviceID)
	return u
}

// SetShortID sets the "short_id" field.
func (u *SyncthingDeviceUpsert) SetShortID(v string) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldShortID, v)
	return u
}

// UpdateShortID sets the "short_id" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateShortID() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldShortID)
	return u
}

// ClearShortID clears the value of the "short_id" field.
func (u *SyncthingDeviceUpsert) ClearShortID() *SyncthingDeviceUpsert {
	u.SetNull(syncthingdevice.FieldShortID)
	return u
}

// SetLastIP sets the "last_ip" field.
func (u *SyncthingDeviceUpsert) SetLastIP(v string) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldLastIP, v)
	return u
}

// UpdateLastIP sets the "last_ip" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateLastIP() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldLastIP)
	return u
}

// ClearLastIP clears the value of the "last_ip" field.
func (u *SyncthingDeviceUpsert) ClearLastIP() *SyncthingDeviceUpsert {
	u.SetNull(syncthingdevice.FieldLastIP)
	return u
}

// SetAPIKey sets the "api_key" field.
func (u *SyncthingDeviceUpsert) SetAPIKey(v string) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldAPIKey, v)
	return u
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateAPIKey() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldAPIKey)
	return u
}

// ClearAPIKey clears the value of the "api_key" field.
func (u *SyncthingDeviceUpsert) ClearAPIKey() *SyncthingDeviceUpsert {
	u.SetNull(syncthingdevice.FieldAPIKey)
	return u
}

// SetJSONRaw sets the "json_raw" field.
func (u *SyncthingDeviceUpsert) SetJSONRaw(v map[string]interface{}) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldJSONRaw, v)
	return u
}

// UpdateJSONRaw sets the "json_raw" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateJSONRaw() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldJSONRaw)
	return u
}

// ClearJSONRaw clears the value of the "json_raw" field.
func (u *SyncthingDeviceUpsert) ClearJSONRaw() *SyncthingDeviceUpsert {
	u.SetNull(syncthingdevice.FieldJSONRaw)
	return u
}

// SetBindURI sets the "bind_uri" field.
func (u *SyncthingDeviceUpsert) SetBindURI(v string) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldBindURI, v)
	return u
}

// UpdateBindURI sets the "bind_uri" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateBindURI() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldBindURI)
	return u
}

// ClearBindURI clears the value of the "bind_uri" field.
func (u *SyncthingDeviceUpsert) ClearBindURI() *SyncthingDeviceUpsert {
	u.SetNull(syncthingdevice.FieldBindURI)
	return u
}

// SetClientVersion sets the "client_version" field.
func (u *SyncthingDeviceUpsert) SetClientVersion(v string) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldClientVersion, v)
	return u
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateClientVersion() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldClientVersion)
	return u
}

// ClearClientVersion clears the value of the "client_version" field.
func (u *SyncthingDeviceUpsert) ClearClientVersion() *SyncthingDeviceUpsert {
	u.SetNull(syncthingdevice.FieldClientVersion)
	return u
}

// SetPlatform sets the "platform" field.
func (u *SyncthingDeviceUpsert) SetPlatform(v string) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdatePlatform() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldPlatform)
	return u
}

// ClearPlatform clears the value of the "platform" field.
func (u *SyncthingDeviceUpsert) ClearPlatform() *SyncthingDeviceUpsert {
	u.SetNull(syncthingdevice.FieldPlatform)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *SyncthingDeviceUpsert) SetLastSeenAt(v time.Time) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateLastSeenAt() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldLastSeenAt)
	return u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *SyncthingDeviceUpsert) ClearLastSeenAt() *SyncthingDeviceUpsert {
	u.SetNull(syncthingdevice.FieldLastSeenAt)
	return u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *SyncthingDeviceUpsert) SetLastSyncAt(v time.Time) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldLastSyncAt, v)
	return u
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateLastSyncAt() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldLastSyncAt)
	return u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *SyncthingDeviceUpsert) ClearLastSyncAt() *SyncthingDeviceUpsert {
	u.SetNull(syncthingdevice.FieldLastSyncAt)
	return u
}

// SetOnline sets the "online" field.
func (u *SyncthingDeviceUpsert) SetOnline(v bool) *SyncthingDeviceUpsert {
	u.Set(syncthingdevice.FieldOnline, v)
	return u
}

// UpdateOnline sets the "online" field to the value that was provided on create.
func (u *SyncthingDeviceUpsert) UpdateOnline() *SyncthingDeviceUpsert {
	u.SetExcluded(syncthingdevice.FieldOnline)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SyncthingDevice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SyncthingDeviceUpsertOne) UpdateNewValues() *SyncthingDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(syncthingdevice.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SyncthingDevice.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SyncthingDeviceUpsertOne) Ignore() *SyncthingDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SyncthingDeviceUpsertOne) DoNothing() *SyncthingDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SyncthingDeviceCreate.OnConflict
// documentation for more info.
func (u *SyncthingDeviceUpsertOne) Update(set func(*SyncthingDeviceUpsert)) *SyncthingDeviceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SyncthingDeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SyncthingDeviceUpsertOne) SetUpdatedAt(v time.Time) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateUpdatedAt() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SyncthingDeviceUpsertOne) SetDeletedAt(v time.Time) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateDeletedAt() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SyncthingDeviceUpsertOne) ClearDeletedAt() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *SyncthingDeviceUpsertOne) SetOwnerID(v int) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateOwnerID() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateOwnerID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *SyncthingDeviceUpsertOne) SetDeviceID(v string) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateDeviceID() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateDeviceID()
	})
}

// SetShortID sets the "short_id" field.
func (u *SyncthingDeviceUpsertOne) SetShortID(v string) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetShortID(v)
	})
}

// UpdateShortID sets the "short_id" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateShortID() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateShortID()
	})
}

// ClearShortID clears the value of the "short_id" field.
func (u *SyncthingDeviceUpsertOne) ClearShortID() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearShortID()
	})
}

// SetLastIP sets the "last_ip" field.
func (u *SyncthingDeviceUpsertOne) SetLastIP(v string) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetLastIP(v)
	})
}

// UpdateLastIP sets the "last_ip" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateLastIP() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateLastIP()
	})
}

// ClearLastIP clears the value of the "last_ip" field.
func (u *SyncthingDeviceUpsertOne) ClearLastIP() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearLastIP()
	})
}

// SetAPIKey sets the "api_key" field.
func (u *SyncthingDeviceUpsertOne) SetAPIKey(v string) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetAPIKey(v)
	})
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateAPIKey() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateAPIKey()
	})
}

// ClearAPIKey clears the value of the "api_key" field.
func (u *SyncthingDeviceUpsertOne) ClearAPIKey() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearAPIKey()
	})
}

// SetJSONRaw sets the "json_raw" field.
func (u *SyncthingDeviceUpsertOne) SetJSONRaw(v map[string]interface{}) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetJSONRaw(v)
	})
}

// UpdateJSONRaw sets the "json_raw" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateJSONRaw() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateJSONRaw()
	})
}

// ClearJSONRaw clears the value of the "json_raw" field.
func (u *SyncthingDeviceUpsertOne) ClearJSONRaw() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearJSONRaw()
	})
}

// SetBindURI sets the "bind_uri" field.
func (u *SyncthingDeviceUpsertOne) SetBindURI(v string) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetBindURI(v)
	})
}

// UpdateBindURI sets the "bind_uri" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateBindURI() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateBindURI()
	})
}

// ClearBindURI clears the value of the "bind_uri" field.
func (u *SyncthingDeviceUpsertOne) ClearBindURI() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearBindURI()
	})
}

// SetClientVersion sets the "client_version" field.
func (u *SyncthingDeviceUpsertOne) SetClientVersion(v string) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetClientVersion(v)
	})
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateClientVersion() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateClientVersion()
	})
}

// ClearClientVersion clears the value of the "client_version" field.
func (u *SyncthingDeviceUpsertOne) ClearClientVersion() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearClientVersion()
	})
}

// SetPlatform sets the "platform" field.
func (u *SyncthingDeviceUpsertOne) SetPlatform(v string) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdatePlatform() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdatePlatform()
	})
}

// ClearPlatform clears the value of the "platform" field.
func (u *SyncthingDeviceUpsertOne) ClearPlatform() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearPlatform()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *SyncthingDeviceUpsertOne) SetLastSeenAt(v time.Time) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateLastSeenAt() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *SyncthingDeviceUpsertOne) ClearLastSeenAt() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *SyncthingDeviceUpsertOne) SetLastSyncAt(v time.Time) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateLastSyncAt() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *SyncthingDeviceUpsertOne) ClearLastSyncAt() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearLastSyncAt()
	})
}

// SetOnline sets the "online" field.
func (u *SyncthingDeviceUpsertOne) SetOnline(v bool) *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetOnline(v)
	})
}

// UpdateOnline sets the "online" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertOne) UpdateOnline() *SyncthingDeviceUpsertOne {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateOnline()
	})
}

// Exec executes the query.
func (u *SyncthingDeviceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SyncthingDeviceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SyncthingDeviceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SyncthingDeviceUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SyncthingDeviceUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *SyncthingDeviceCreate) SetRawID(t int) *SyncthingDeviceCreate {
	m.mutation.SetRawID(t)
	return m
}

// SyncthingDeviceCreateBulk is the builder for creating many SyncthingDevice entities in bulk.
type SyncthingDeviceCreateBulk struct {
	config
	err      error
	builders []*SyncthingDeviceCreate
	conflict []sql.ConflictOption
}

// Save creates the SyncthingDevice entities in the database.
func (sdcb *SyncthingDeviceCreateBulk) Save(ctx context.Context) ([]*SyncthingDevice, error) {
	if sdcb.err != nil {
		return nil, sdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sdcb.builders))
	nodes := make([]*SyncthingDevice, len(sdcb.builders))
	mutators := make([]Mutator, len(sdcb.builders))
	for i := range sdcb.builders {
		func(i int, root context.Context) {
			builder := sdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncthingDeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = sdcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sdcb *SyncthingDeviceCreateBulk) SaveX(ctx context.Context) []*SyncthingDevice {
	v, err := sdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sdcb *SyncthingDeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := sdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sdcb *SyncthingDeviceCreateBulk) ExecX(ctx context.Context) {
	if err := sdcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SyncthingDevice.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SyncthingDeviceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (sdcb *SyncthingDeviceCreateBulk) OnConflict(opts ...sql.ConflictOption) *SyncthingDeviceUpsertBulk {
	sdcb.conflict = opts
	return &SyncthingDeviceUpsertBulk{
		create: sdcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SyncthingDevice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sdcb *SyncthingDeviceCreateBulk) OnConflictColumns(columns ...string) *SyncthingDeviceUpsertBulk {
	sdcb.conflict = append(sdcb.conflict, sql.ConflictColumns(columns...))
	return &SyncthingDeviceUpsertBulk{
		create: sdcb,
	}
}

// SyncthingDeviceUpsertBulk is the builder for "upsert"-ing
// a bulk of SyncthingDevice nodes.
type SyncthingDeviceUpsertBulk struct {
	create *SyncthingDeviceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SyncthingDevice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SyncthingDeviceUpsertBulk) UpdateNewValues() *SyncthingDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(syncthingdevice.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SyncthingDevice.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SyncthingDeviceUpsertBulk) Ignore() *SyncthingDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SyncthingDeviceUpsertBulk) DoNothing() *SyncthingDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SyncthingDeviceCreateBulk.OnConflict
// documentation for more info.
func (u *SyncthingDeviceUpsertBulk) Update(set func(*SyncthingDeviceUpsert)) *SyncthingDeviceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SyncthingDeviceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SyncthingDeviceUpsertBulk) SetUpdatedAt(v time.Time) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateUpdatedAt() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SyncthingDeviceUpsertBulk) SetDeletedAt(v time.Time) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateDeletedAt() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SyncthingDeviceUpsertBulk) ClearDeletedAt() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *SyncthingDeviceUpsertBulk) SetOwnerID(v int) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateOwnerID() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateOwnerID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *SyncthingDeviceUpsertBulk) SetDeviceID(v string) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateDeviceID() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateDeviceID()
	})
}

// SetShortID sets the "short_id" field.
func (u *SyncthingDeviceUpsertBulk) SetShortID(v string) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetShortID(v)
	})
}

// UpdateShortID sets the "short_id" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateShortID() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateShortID()
	})
}

// ClearShortID clears the value of the "short_id" field.
func (u *SyncthingDeviceUpsertBulk) ClearShortID() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearShortID()
	})
}

// SetLastIP sets the "last_ip" field.
func (u *SyncthingDeviceUpsertBulk) SetLastIP(v string) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetLastIP(v)
	})
}

// UpdateLastIP sets the "last_ip" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateLastIP() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateLastIP()
	})
}

// ClearLastIP clears the value of the "last_ip" field.
func (u *SyncthingDeviceUpsertBulk) ClearLastIP() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearLastIP()
	})
}

// SetAPIKey sets the "api_key" field.
func (u *SyncthingDeviceUpsertBulk) SetAPIKey(v string) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetAPIKey(v)
	})
}

// UpdateAPIKey sets the "api_key" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateAPIKey() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateAPIKey()
	})
}

// ClearAPIKey clears the value of the "api_key" field.
func (u *SyncthingDeviceUpsertBulk) ClearAPIKey() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearAPIKey()
	})
}

// SetJSONRaw sets the "json_raw" field.
func (u *SyncthingDeviceUpsertBulk) SetJSONRaw(v map[string]interface{}) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetJSONRaw(v)
	})
}

// UpdateJSONRaw sets the "json_raw" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateJSONRaw() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateJSONRaw()
	})
}

// ClearJSONRaw clears the value of the "json_raw" field.
func (u *SyncthingDeviceUpsertBulk) ClearJSONRaw() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearJSONRaw()
	})
}

// SetBindURI sets the "bind_uri" field.
func (u *SyncthingDeviceUpsertBulk) SetBindURI(v string) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetBindURI(v)
	})
}

// UpdateBindURI sets the "bind_uri" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateBindURI() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateBindURI()
	})
}

// ClearBindURI clears the value of the "bind_uri" field.
func (u *SyncthingDeviceUpsertBulk) ClearBindURI() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearBindURI()
	})
}

// SetClientVersion sets the "client_version" field.
func (u *SyncthingDeviceUpsertBulk) SetClientVersion(v string) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetClientVersion(v)
	})
}

// UpdateClientVersion sets the "client_version" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateClientVersion() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateClientVersion()
	})
}

// ClearClientVersion clears the value of the "client_version" field.
func (u *SyncthingDeviceUpsertBulk) ClearClientVersion() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearClientVersion()
	})
}

// SetPlatform sets the "platform" field.
func (u *SyncthingDeviceUpsertBulk) SetPlatform(v string) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdatePlatform() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdatePlatform()
	})
}

// ClearPlatform clears the value of the "platform" field.
func (u *SyncthingDeviceUpsertBulk) ClearPlatform() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearPlatform()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *SyncthingDeviceUpsertBulk) SetLastSeenAt(v time.Time) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateLastSeenAt() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *SyncthingDeviceUpsertBulk) ClearLastSeenAt() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *SyncthingDeviceUpsertBulk) SetLastSyncAt(v time.Time) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateLastSyncAt() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *SyncthingDeviceUpsertBulk) ClearLastSyncAt() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.ClearLastSyncAt()
	})
}

// SetOnline sets the "online" field.
func (u *SyncthingDeviceUpsertBulk) SetOnline(v bool) *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.SetOnline(v)
	})
}

// UpdateOnline sets the "online" field to the value that was provided on create.
func (u *SyncthingDeviceUpsertBulk) UpdateOnline() *SyncthingDeviceUpsertBulk {
	return u.Update(func(s *SyncthingDeviceUpsert) {
		s.UpdateOnline()
	})
}

// Exec executes the query.
func (u *SyncthingDeviceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SyncthingDeviceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SyncthingDeviceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SyncthingDeviceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
