// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/syncthingdevice"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SyncthingDeviceUpdate is the builder for updating SyncthingDevice entities.
type SyncthingDeviceUpdate struct {
	config
	hooks    []Hook
	mutation *SyncthingDeviceMutation
}

// Where appends a list predicates to the SyncthingDeviceUpdate builder.
func (sdu *SyncthingDeviceUpdate) Where(ps ...predicate.SyncthingDevice) *SyncthingDeviceUpdate {
	sdu.mutation.Where(ps...)
	return sdu
}

// SetUpdatedAt sets the "updated_at" field.
func (sdu *SyncthingDeviceUpdate) SetUpdatedAt(t time.Time) *SyncthingDeviceUpdate {
	sdu.mutation.SetUpdatedAt(t)
	return sdu
}

// SetDeletedAt sets the "deleted_at" field.
func (sdu *SyncthingDeviceUpdate) SetDeletedAt(t time.Time) *SyncthingDeviceUpdate {
	sdu.mutation.SetDeletedAt(t)
	return sdu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillableDeletedAt(t *time.Time) *SyncthingDeviceUpdate {
	if t != nil {
		sdu.SetDeletedAt(*t)
	}
	return sdu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (sdu *SyncthingDeviceUpdate) ClearDeletedAt() *SyncthingDeviceUpdate {
	sdu.mutation.ClearDeletedAt()
	return sdu
}

// SetOwnerID sets the "owner_id" field.
func (sdu *SyncthingDeviceUpdate) SetOwnerID(i int) *SyncthingDeviceUpdate {
	sdu.mutation.SetOwnerID(i)
	return sdu
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillableOwnerID(i *int) *SyncthingDeviceUpdate {
	if i != nil {
		sdu.SetOwnerID(*i)
	}
	return sdu
}

// SetDeviceID sets the "device_id" field.
func (sdu *SyncthingDeviceUpdate) SetDeviceID(s string) *SyncthingDeviceUpdate {
	sdu.mutation.SetDeviceID(s)
	return sdu
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillableDeviceID(s *string) *SyncthingDeviceUpdate {
	if s != nil {
		sdu.SetDeviceID(*s)
	}
	return sdu
}

// SetShortID sets the "short_id" field.
func (sdu *SyncthingDeviceUpdate) SetShortID(s string) *SyncthingDeviceUpdate {
	sdu.mutation.SetShortID(s)
	return sdu
}

// SetNillableShortID sets the "short_id" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillableShortID(s *string) *SyncthingDeviceUpdate {
	if s != nil {
		sdu.SetShortID(*s)
	}
	return sdu
}

// ClearShortID clears the value of the "short_id" field.
func (sdu *SyncthingDeviceUpdate) ClearShortID() *SyncthingDeviceUpdate {
	sdu.mutation.ClearShortID()
	return sdu
}

// SetLastIP sets the "last_ip" field.
func (sdu *SyncthingDeviceUpdate) SetLastIP(s string) *SyncthingDeviceUpdate {
	sdu.mutation.SetLastIP(s)
	return sdu
}

// SetNillableLastIP sets the "last_ip" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillableLastIP(s *string) *SyncthingDeviceUpdate {
	if s != nil {
		sdu.SetLastIP(*s)
	}
	return sdu
}

// ClearLastIP clears the value of the "last_ip" field.
func (sdu *SyncthingDeviceUpdate) ClearLastIP() *SyncthingDeviceUpdate {
	sdu.mutation.ClearLastIP()
	return sdu
}

// SetAPIKey sets the "api_key" field.
func (sdu *SyncthingDeviceUpdate) SetAPIKey(s string) *SyncthingDeviceUpdate {
	sdu.mutation.SetAPIKey(s)
	return sdu
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillableAPIKey(s *string) *SyncthingDeviceUpdate {
	if s != nil {
		sdu.SetAPIKey(*s)
	}
	return sdu
}

// ClearAPIKey clears the value of the "api_key" field.
func (sdu *SyncthingDeviceUpdate) ClearAPIKey() *SyncthingDeviceUpdate {
	sdu.mutation.ClearAPIKey()
	return sdu
}

// SetJSONRaw sets the "json_raw" field.
func (sdu *SyncthingDeviceUpdate) SetJSONRaw(m map[string]interface{}) *SyncthingDeviceUpdate {
	sdu.mutation.SetJSONRaw(m)
	return sdu
}

// ClearJSONRaw clears the value of the "json_raw" field.
func (sdu *SyncthingDeviceUpdate) ClearJSONRaw() *SyncthingDeviceUpdate {
	sdu.mutation.ClearJSONRaw()
	return sdu
}

// SetBindURI sets the "bind_uri" field.
func (sdu *SyncthingDeviceUpdate) SetBindURI(s string) *SyncthingDeviceUpdate {
	sdu.mutation.SetBindURI(s)
	return sdu
}

// SetNillableBindURI sets the "bind_uri" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillableBindURI(s *string) *SyncthingDeviceUpdate {
	if s != nil {
		sdu.SetBindURI(*s)
	}
	return sdu
}

// ClearBindURI clears the value of the "bind_uri" field.
func (sdu *SyncthingDeviceUpdate) ClearBindURI() *SyncthingDeviceUpdate {
	sdu.mutation.ClearBindURI()
	return sdu
}

// SetClientVersion sets the "client_version" field.
func (sdu *SyncthingDeviceUpdate) SetClientVersion(s string) *SyncthingDeviceUpdate {
	sdu.mutation.SetClientVersion(s)
	return sdu
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillableClientVersion(s *string) *SyncthingDeviceUpdate {
	if s != nil {
		sdu.SetClientVersion(*s)
	}
	return sdu
}

// ClearClientVersion clears the value of the "client_version" field.
func (sdu *SyncthingDeviceUpdate) ClearClientVersion() *SyncthingDeviceUpdate {
	sdu.mutation.ClearClientVersion()
	return sdu
}

// SetPlatform sets the "platform" field.
func (sdu *SyncthingDeviceUpdate) SetPlatform(s string) *SyncthingDeviceUpdate {
	sdu.mutation.SetPlatform(s)
	return sdu
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillablePlatform(s *string) *SyncthingDeviceUpdate {
	if s != nil {
		sdu.SetPlatform(*s)
	}
	return sdu
}

// ClearPlatform clears the value of the "platform" field.
func (sdu *SyncthingDeviceUpdate) ClearPlatform() *SyncthingDeviceUpdate {
	sdu.mutation.ClearPlatform()
	return sdu
}

// SetLastSeenAt sets the "last_seen_at" field.
func (sdu *SyncthingDeviceUpdate) SetLastSeenAt(t time.Time) *SyncthingDeviceUpdate {
	sdu.mutation.SetLastSeenAt(t)
	return sdu
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillableLastSeenAt(t *time.Time) *SyncthingDeviceUpdate {
	if t != nil {
		sdu.SetLastSeenAt(*t)
	}
	return sdu
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (sdu *SyncthingDeviceUpdate) ClearLastSeenAt() *SyncthingDeviceUpdate {
	sdu.mutation.ClearLastSeenAt()
	return sdu
}

// SetLastSyncAt sets the "last_sync_at" field.
func (sdu *SyncthingDeviceUpdate) SetLastSyncAt(t time.Time) *SyncthingDeviceUpdate {
	sdu.mutation.SetLastSyncAt(t)
	return sdu
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillableLastSyncAt(t *time.Time) *SyncthingDeviceUpdate {
	if t != nil {
		sdu.SetLastSyncAt(*t)
	}
	return sdu
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (sdu *SyncthingDeviceUpdate) ClearLastSyncAt() *SyncthingDeviceUpdate {
	sdu.mutation.ClearLastSyncAt()
	return sdu
}

// SetOnline sets the "online" field.
func (sdu *SyncthingDeviceUpdate) SetOnline(b bool) *SyncthingDeviceUpdate {
	sdu.mutation.SetOnline(b)
	return sdu
}

// SetNillableOnline sets the "online" field if the given value is not nil.
func (sdu *SyncthingDeviceUpdate) SetNillableOnline(b *bool) *SyncthingDeviceUpdate {
	if b != nil {
		sdu.SetOnline(*b)
	}
	return sdu
}

// SetOwner sets the "owner" edge to the User entity.
func (sdu *SyncthingDeviceUpdate) SetOwner(u *User) *SyncthingDeviceUpdate {
	return sdu.SetOwnerID(u.ID)
}

// Mutation returns the SyncthingDeviceMutation object of the builder.
func (sdu *SyncthingDeviceUpdate) Mutation() *SyncthingDeviceMutation {
	return sdu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (sdu *SyncthingDeviceUpdate) ClearOwner() *SyncthingDeviceUpdate {
	sdu.mutation.ClearOwner()
	return sdu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sdu *SyncthingDeviceUpdate) Save(ctx context.Context) (int, error) {
	if err := sdu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, sdu.sqlSave, sdu.mutation, sdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sdu *SyncthingDeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := sdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sdu *SyncthingDeviceUpdate) Exec(ctx context.Context) error {
	_, err := sdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sdu *SyncthingDeviceUpdate) ExecX(ctx context.Context) {
	if err := sdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sdu *SyncthingDeviceUpdate) defaults() error {
	if _, ok := sdu.mutation.UpdatedAt(); !ok {
		if syncthingdevice.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized syncthingdevice.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := syncthingdevice.UpdateDefaultUpdatedAt()
		sdu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (sdu *SyncthingDeviceUpdate) check() error {
	if v, ok := sdu.mutation.DeviceID(); ok {
		if err := syncthingdevice.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.device_id": %w`, err)}
		}
	}
	if v, ok := sdu.mutation.ShortID(); ok {
		if err := syncthingdevice.ShortIDValidator(v); err != nil {
			return &ValidationError{Name: "short_id", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.short_id": %w`, err)}
		}
	}
	if v, ok := sdu.mutation.LastIP(); ok {
		if err := syncthingdevice.LastIPValidator(v); err != nil {
			return &ValidationError{Name: "last_ip", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.last_ip": %w`, err)}
		}
	}
	if v, ok := sdu.mutation.APIKey(); ok {
		if err := syncthingdevice.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.api_key": %w`, err)}
		}
	}
	if v, ok := sdu.mutation.BindURI(); ok {
		if err := syncthingdevice.BindURIValidator(v); err != nil {
			return &ValidationError{Name: "bind_uri", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.bind_uri": %w`, err)}
		}
	}
	if v, ok := sdu.mutation.ClientVersion(); ok {
		if err := syncthingdevice.ClientVersionValidator(v); err != nil {
			return &ValidationError{Name: "client_version", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.client_version": %w`, err)}
		}
	}
	if v, ok := sdu.mutation.Platform(); ok {
		if err := syncthingdevice.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.platform": %w`, err)}
		}
	}
	if _, ok := sdu.mutation.OwnerID(); sdu.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "SyncthingDevice.owner"`)
	}
	return nil
}

func (sdu *SyncthingDeviceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := sdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncthingdevice.Table, syncthingdevice.Columns, sqlgraph.NewFieldSpec(syncthingdevice.FieldID, field.TypeInt))
	if ps := sdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sdu.mutation.UpdatedAt(); ok {
		_spec.SetField(syncthingdevice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sdu.mutation.DeletedAt(); ok {
		_spec.SetField(syncthingdevice.FieldDeletedAt, field.TypeTime, value)
	}
	if sdu.mutation.DeletedAtCleared() {
		_spec.ClearField(syncthingdevice.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := sdu.mutation.DeviceID(); ok {
		_spec.SetField(syncthingdevice.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := sdu.mutation.ShortID(); ok {
		_spec.SetField(syncthingdevice.FieldShortID, field.TypeString, value)
	}
	if sdu.mutation.ShortIDCleared() {
		_spec.ClearField(syncthingdevice.FieldShortID, field.TypeString)
	}
	if value, ok := sdu.mutation.LastIP(); ok {
		_spec.SetField(syncthingdevice.FieldLastIP, field.TypeString, value)
	}
	if sdu.mutation.LastIPCleared() {
		_spec.ClearField(syncthingdevice.FieldLastIP, field.TypeString)
	}
	if value, ok := sdu.mutation.APIKey(); ok {
		_spec.SetField(syncthingdevice.FieldAPIKey, field.TypeString, value)
	}
	if sdu.mutation.APIKeyCleared() {
		_spec.ClearField(syncthingdevice.FieldAPIKey, field.TypeString)
	}
	if value, ok := sdu.mutation.JSONRaw(); ok {
		_spec.SetField(syncthingdevice.FieldJSONRaw, field.TypeJSON, value)
	}
	if sdu.mutation.JSONRawCleared() {
		_spec.ClearField(syncthingdevice.FieldJSONRaw, field.TypeJSON)
	}
	if value, ok := sdu.mutation.BindURI(); ok {
		_spec.SetField(syncthingdevice.FieldBindURI, field.TypeString, value)
	}
	if sdu.mutation.BindURICleared() {
		_spec.ClearField(syncthingdevice.FieldBindURI, field.TypeString)
	}
	if value, ok := sdu.mutation.ClientVersion(); ok {
		_spec.SetField(syncthingdevice.FieldClientVersion, field.TypeString, value)
	}
	if sdu.mutation.ClientVersionCleared() {
		_spec.ClearField(syncthingdevice.FieldClientVersion, field.TypeString)
	}
	if value, ok := sdu.mutation.Platform(); ok {
		_spec.SetField(syncthingdevice.FieldPlatform, field.TypeString, value)
	}
	if sdu.mutation.PlatformCleared() {
		_spec.ClearField(syncthingdevice.FieldPlatform, field.TypeString)
	}
	if value, ok := sdu.mutation.LastSeenAt(); ok {
		_spec.SetField(syncthingdevice.FieldLastSeenAt, field.TypeTime, value)
	}
	if sdu.mutation.LastSeenAtCleared() {
		_spec.ClearField(syncthingdevice.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := sdu.mutation.LastSyncAt(); ok {
		_spec.SetField(syncthingdevice.FieldLastSyncAt, field.TypeTime, value)
	}
	if sdu.mutation.LastSyncAtCleared() {
		_spec.ClearField(syncthingdevice.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := sdu.mutation.Online(); ok {
		_spec.SetField(syncthingdevice.FieldOnline, field.TypeBool, value)
	}
	if sdu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncthingdevice.OwnerTable,
			Columns: []string{syncthingdevice.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sdu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncthingdevice.OwnerTable,
			Columns: []string{syncthingdevice.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncthingdevice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sdu.mutation.done = true
	return n, nil
}

// SyncthingDeviceUpdateOne is the builder for updating a single SyncthingDevice entity.
type SyncthingDeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncthingDeviceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (sduo *SyncthingDeviceUpdateOne) SetUpdatedAt(t time.Time) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetUpdatedAt(t)
	return sduo
}

// SetDeletedAt sets the "deleted_at" field.
func (sduo *SyncthingDeviceUpdateOne) SetDeletedAt(t time.Time) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetDeletedAt(t)
	return sduo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillableDeletedAt(t *time.Time) *SyncthingDeviceUpdateOne {
	if t != nil {
		sduo.SetDeletedAt(*t)
	}
	return sduo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (sduo *SyncthingDeviceUpdateOne) ClearDeletedAt() *SyncthingDeviceUpdateOne {
	sduo.mutation.ClearDeletedAt()
	return sduo
}

// SetOwnerID sets the "owner_id" field.
func (sduo *SyncthingDeviceUpdateOne) SetOwnerID(i int) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetOwnerID(i)
	return sduo
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillableOwnerID(i *int) *SyncthingDeviceUpdateOne {
	if i != nil {
		sduo.SetOwnerID(*i)
	}
	return sduo
}

// SetDeviceID sets the "device_id" field.
func (sduo *SyncthingDeviceUpdateOne) SetDeviceID(s string) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetDeviceID(s)
	return sduo
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillableDeviceID(s *string) *SyncthingDeviceUpdateOne {
	if s != nil {
		sduo.SetDeviceID(*s)
	}
	return sduo
}

// SetShortID sets the "short_id" field.
func (sduo *SyncthingDeviceUpdateOne) SetShortID(s string) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetShortID(s)
	return sduo
}

// SetNillableShortID sets the "short_id" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillableShortID(s *string) *SyncthingDeviceUpdateOne {
	if s != nil {
		sduo.SetShortID(*s)
	}
	return sduo
}

// ClearShortID clears the value of the "short_id" field.
func (sduo *SyncthingDeviceUpdateOne) ClearShortID() *SyncthingDeviceUpdateOne {
	sduo.mutation.ClearShortID()
	return sduo
}

// SetLastIP sets the "last_ip" field.
func (sduo *SyncthingDeviceUpdateOne) SetLastIP(s string) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetLastIP(s)
	return sduo
}

// SetNillableLastIP sets the "last_ip" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillableLastIP(s *string) *SyncthingDeviceUpdateOne {
	if s != nil {
		sduo.SetLastIP(*s)
	}
	return sduo
}

// ClearLastIP clears the value of the "last_ip" field.
func (sduo *SyncthingDeviceUpdateOne) ClearLastIP() *SyncthingDeviceUpdateOne {
	sduo.mutation.ClearLastIP()
	return sduo
}

// SetAPIKey sets the "api_key" field.
func (sduo *SyncthingDeviceUpdateOne) SetAPIKey(s string) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetAPIKey(s)
	return sduo
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillableAPIKey(s *string) *SyncthingDeviceUpdateOne {
	if s != nil {
		sduo.SetAPIKey(*s)
	}
	return sduo
}

// ClearAPIKey clears the value of the "api_key" field.
func (sduo *SyncthingDeviceUpdateOne) ClearAPIKey() *SyncthingDeviceUpdateOne {
	sduo.mutation.ClearAPIKey()
	return sduo
}

// SetJSONRaw sets the "json_raw" field.
func (sduo *SyncthingDeviceUpdateOne) SetJSONRaw(m map[string]interface{}) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetJSONRaw(m)
	return sduo
}

// ClearJSONRaw clears the value of the "json_raw" field.
func (sduo *SyncthingDeviceUpdateOne) ClearJSONRaw() *SyncthingDeviceUpdateOne {
	sduo.mutation.ClearJSONRaw()
	return sduo
}

// SetBindURI sets the "bind_uri" field.
func (sduo *SyncthingDeviceUpdateOne) SetBindURI(s string) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetBindURI(s)
	return sduo
}

// SetNillableBindURI sets the "bind_uri" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillableBindURI(s *string) *SyncthingDeviceUpdateOne {
	if s != nil {
		sduo.SetBindURI(*s)
	}
	return sduo
}

// ClearBindURI clears the value of the "bind_uri" field.
func (sduo *SyncthingDeviceUpdateOne) ClearBindURI() *SyncthingDeviceUpdateOne {
	sduo.mutation.ClearBindURI()
	return sduo
}

// SetClientVersion sets the "client_version" field.
func (sduo *SyncthingDeviceUpdateOne) SetClientVersion(s string) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetClientVersion(s)
	return sduo
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillableClientVersion(s *string) *SyncthingDeviceUpdateOne {
	if s != nil {
		sduo.SetClientVersion(*s)
	}
	return sduo
}

// ClearClientVersion clears the value of the "client_version" field.
func (sduo *SyncthingDeviceUpdateOne) ClearClientVersion() *SyncthingDeviceUpdateOne {
	sduo.mutation.ClearClientVersion()
	return sduo
}

// SetPlatform sets the "platform" field.
func (sduo *SyncthingDeviceUpdateOne) SetPlatform(s string) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetPlatform(s)
	return sduo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillablePlatform(s *string) *SyncthingDeviceUpdateOne {
	if s != nil {
		sduo.SetPlatform(*s)
	}
	return sduo
}

// ClearPlatform clears the value of the "platform" field.
func (sduo *SyncthingDeviceUpdateOne) ClearPlatform() *SyncthingDeviceUpdateOne {
	sduo.mutation.ClearPlatform()
	return sduo
}

// SetLastSeenAt sets the "last_seen_at" field.
func (sduo *SyncthingDeviceUpdateOne) SetLastSeenAt(t time.Time) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetLastSeenAt(t)
	return sduo
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillableLastSeenAt(t *time.Time) *SyncthingDeviceUpdateOne {
	if t != nil {
		sduo.SetLastSeenAt(*t)
	}
	return sduo
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (sduo *SyncthingDeviceUpdateOne) ClearLastSeenAt() *SyncthingDeviceUpdateOne {
	sduo.mutation.ClearLastSeenAt()
	return sduo
}

// SetLastSyncAt sets the "last_sync_at" field.
func (sduo *SyncthingDeviceUpdateOne) SetLastSyncAt(t time.Time) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetLastSyncAt(t)
	return sduo
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillableLastSyncAt(t *time.Time) *SyncthingDeviceUpdateOne {
	if t != nil {
		sduo.SetLastSyncAt(*t)
	}
	return sduo
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (sduo *SyncthingDeviceUpdateOne) ClearLastSyncAt() *SyncthingDeviceUpdateOne {
	sduo.mutation.ClearLastSyncAt()
	return sduo
}

// SetOnline sets the "online" field.
func (sduo *SyncthingDeviceUpdateOne) SetOnline(b bool) *SyncthingDeviceUpdateOne {
	sduo.mutation.SetOnline(b)
	return sduo
}

// SetNillableOnline sets the "online" field if the given value is not nil.
func (sduo *SyncthingDeviceUpdateOne) SetNillableOnline(b *bool) *SyncthingDeviceUpdateOne {
	if b != nil {
		sduo.SetOnline(*b)
	}
	return sduo
}

// SetOwner sets the "owner" edge to the User entity.
func (sduo *SyncthingDeviceUpdateOne) SetOwner(u *User) *SyncthingDeviceUpdateOne {
	return sduo.SetOwnerID(u.ID)
}

// Mutation returns the SyncthingDeviceMutation object of the builder.
func (sduo *SyncthingDeviceUpdateOne) Mutation() *SyncthingDeviceMutation {
	return sduo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (sduo *SyncthingDeviceUpdateOne) ClearOwner() *SyncthingDeviceUpdateOne {
	sduo.mutation.ClearOwner()
	return sduo
}

// Where appends a list predicates to the SyncthingDeviceUpdate builder.
func (sduo *SyncthingDeviceUpdateOne) Where(ps ...predicate.SyncthingDevice) *SyncthingDeviceUpdateOne {
	sduo.mutation.Where(ps...)
	return sduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sduo *SyncthingDeviceUpdateOne) Select(field string, fields ...string) *SyncthingDeviceUpdateOne {
	sduo.fields = append([]string{field}, fields...)
	return sduo
}

// Save executes the query and returns the updated SyncthingDevice entity.
func (sduo *SyncthingDeviceUpdateOne) Save(ctx context.Context) (*SyncthingDevice, error) {
	if err := sduo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, sduo.sqlSave, sduo.mutation, sduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sduo *SyncthingDeviceUpdateOne) SaveX(ctx context.Context) *SyncthingDevice {
	node, err := sduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sduo *SyncthingDeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := sduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sduo *SyncthingDeviceUpdateOne) ExecX(ctx context.Context) {
	if err := sduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sduo *SyncthingDeviceUpdateOne) defaults() error {
	if _, ok := sduo.mutation.UpdatedAt(); !ok {
		if syncthingdevice.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized syncthingdevice.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := syncthingdevice.UpdateDefaultUpdatedAt()
		sduo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (sduo *SyncthingDeviceUpdateOne) check() error {
	if v, ok := sduo.mutation.DeviceID(); ok {
		if err := syncthingdevice.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.device_id": %w`, err)}
		}
	}
	if v, ok := sduo.mutation.ShortID(); ok {
		if err := syncthingdevice.ShortIDValidator(v); err != nil {
			return &ValidationError{Name: "short_id", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.short_id": %w`, err)}
		}
	}
	if v, ok := sduo.mutation.LastIP(); ok {
		if err := syncthingdevice.LastIPValidator(v); err != nil {
			return &ValidationError{Name: "last_ip", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.last_ip": %w`, err)}
		}
	}
	if v, ok := sduo.mutation.APIKey(); ok {
		if err := syncthingdevice.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.api_key": %w`, err)}
		}
	}
	if v, ok := sduo.mutation.BindURI(); ok {
		if err := syncthingdevice.BindURIValidator(v); err != nil {
			return &ValidationError{Name: "bind_uri", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.bind_uri": %w`, err)}
		}
	}
	if v, ok := sduo.mutation.ClientVersion(); ok {
		if err := syncthingdevice.ClientVersionValidator(v); err != nil {
			return &ValidationError{Name: "client_version", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.client_version": %w`, err)}
		}
	}
	if v, ok := sduo.mutation.Platform(); ok {
		if err := syncthingdevice.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SyncthingDevice.platform": %w`, err)}
		}
	}
	if _, ok := sduo.mutation.OwnerID(); sduo.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "SyncthingDevice.owner"`)
	}
	return nil
}

func (sduo *SyncthingDeviceUpdateOne) sqlSave(ctx context.Context) (_node *SyncthingDevice, err error) {
	if err := sduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncthingdevice.Table, syncthingdevice.Columns, sqlgraph.NewFieldSpec(syncthingdevice.FieldID, field.TypeInt))
	id, ok := sduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncthingDevice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncthingdevice.FieldID)
		for _, f := range fields {
			if !syncthingdevice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != syncthingdevice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sduo.mutation.UpdatedAt(); ok {
		_spec.SetField(syncthingdevice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sduo.mutation.DeletedAt(); ok {
		_spec.SetField(syncthingdevice.FieldDeletedAt, field.TypeTime, value)
	}
	if sduo.mutation.DeletedAtCleared() {
		_spec.ClearField(syncthingdevice.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := sduo.mutation.DeviceID(); ok {
		_spec.SetField(syncthingdevice.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := sduo.mutation.ShortID(); ok {
		_spec.SetField(syncthingdevice.FieldShortID, field.TypeString, value)
	}
	if sduo.mutation.ShortIDCleared() {
		_spec.ClearField(syncthingdevice.FieldShortID, field.TypeString)
	}
	if value, ok := sduo.mutation.LastIP(); ok {
		_spec.SetField(syncthingdevice.FieldLastIP, field.TypeString, value)
	}
	if sduo.mutation.LastIPCleared() {
		_spec.ClearField(syncthingdevice.FieldLastIP, field.TypeString)
	}
	if value, ok := sduo.mutation.APIKey(); ok {
		_spec.SetField(syncthingdevice.FieldAPIKey, field.TypeString, value)
	}
	if sduo.mutation.APIKeyCleared() {
		_spec.ClearField(syncthingdevice.FieldAPIKey, field.TypeString)
	}
	if value, ok := sduo.mutation.JSONRaw(); ok {
		_spec.SetField(syncthingdevice.FieldJSONRaw, field.TypeJSON, value)
	}
	if sduo.mutation.JSONRawCleared() {
		_spec.ClearField(syncthingdevice.FieldJSONRaw, field.TypeJSON)
	}
	if value, ok := sduo.mutation.BindURI(); ok {
		_spec.SetField(syncthingdevice.FieldBindURI, field.TypeString, value)
	}
	if sduo.mutation.BindURICleared() {
		_spec.ClearField(syncthingdevice.FieldBindURI, field.TypeString)
	}
	if value, ok := sduo.mutation.ClientVersion(); ok {
		_spec.SetField(syncthingdevice.FieldClientVersion, field.TypeString, value)
	}
	if sduo.mutation.ClientVersionCleared() {
		_spec.ClearField(syncthingdevice.FieldClientVersion, field.TypeString)
	}
	if value, ok := sduo.mutation.Platform(); ok {
		_spec.SetField(syncthingdevice.FieldPlatform, field.TypeString, value)
	}
	if sduo.mutation.PlatformCleared() {
		_spec.ClearField(syncthingdevice.FieldPlatform, field.TypeString)
	}
	if value, ok := sduo.mutation.LastSeenAt(); ok {
		_spec.SetField(syncthingdevice.FieldLastSeenAt, field.TypeTime, value)
	}
	if sduo.mutation.LastSeenAtCleared() {
		_spec.ClearField(syncthingdevice.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := sduo.mutation.LastSyncAt(); ok {
		_spec.SetField(syncthingdevice.FieldLastSyncAt, field.TypeTime, value)
	}
	if sduo.mutation.LastSyncAtCleared() {
		_spec.ClearField(syncthingdevice.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := sduo.mutation.Online(); ok {
		_spec.SetField(syncthingdevice.FieldOnline, field.TypeBool, value)
	}
	if sduo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncthingdevice.OwnerTable,
			Columns: []string{syncthingdevice.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sduo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncthingdevice.OwnerTable,
			Columns: []string{syncthingdevice.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SyncthingDevice{config: sduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncthingdevice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sduo.mutation.done = true
	return _node, nil
}
