// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/syncthingdevice"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// SyncthingDeviceQuery is the builder for querying SyncthingDevice entities.
type SyncthingDeviceQuery struct {
	config
	ctx        *QueryContext
	order      []syncthingdevice.OrderOption
	inters     []Interceptor
	predicates []predicate.SyncthingDevice
	withOwner  *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SyncthingDeviceQuery builder.
func (sdq *SyncthingDeviceQuery) Where(ps ...predicate.SyncthingDevice) *SyncthingDeviceQuery {
	sdq.predicates = append(sdq.predicates, ps...)
	return sdq
}

// Limit the number of records to be returned by this query.
func (sdq *SyncthingDeviceQuery) Limit(limit int) *SyncthingDeviceQuery {
	sdq.ctx.Limit = &limit
	return sdq
}

// Offset to start from.
func (sdq *SyncthingDeviceQuery) Offset(offset int) *SyncthingDeviceQuery {
	sdq.ctx.Offset = &offset
	return sdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sdq *SyncthingDeviceQuery) Unique(unique bool) *SyncthingDeviceQuery {
	sdq.ctx.Unique = &unique
	return sdq
}

// Order specifies how the records should be ordered.
func (sdq *SyncthingDeviceQuery) Order(o ...syncthingdevice.OrderOption) *SyncthingDeviceQuery {
	sdq.order = append(sdq.order, o...)
	return sdq
}

// QueryOwner chains the current query on the "owner" edge.
func (sdq *SyncthingDeviceQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: sdq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(syncthingdevice.Table, syncthingdevice.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, syncthingdevice.OwnerTable, syncthingdevice.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(sdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SyncthingDevice entity from the query.
// Returns a *NotFoundError when no SyncthingDevice was found.
func (sdq *SyncthingDeviceQuery) First(ctx context.Context) (*SyncthingDevice, error) {
	nodes, err := sdq.Limit(1).All(setContextOp(ctx, sdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{syncthingdevice.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sdq *SyncthingDeviceQuery) FirstX(ctx context.Context) *SyncthingDevice {
	node, err := sdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SyncthingDevice ID from the query.
// Returns a *NotFoundError when no SyncthingDevice ID was found.
func (sdq *SyncthingDeviceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sdq.Limit(1).IDs(setContextOp(ctx, sdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{syncthingdevice.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sdq *SyncthingDeviceQuery) FirstIDX(ctx context.Context) int {
	id, err := sdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SyncthingDevice entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SyncthingDevice entity is found.
// Returns a *NotFoundError when no SyncthingDevice entities are found.
func (sdq *SyncthingDeviceQuery) Only(ctx context.Context) (*SyncthingDevice, error) {
	nodes, err := sdq.Limit(2).All(setContextOp(ctx, sdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{syncthingdevice.Label}
	default:
		return nil, &NotSingularError{syncthingdevice.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sdq *SyncthingDeviceQuery) OnlyX(ctx context.Context) *SyncthingDevice {
	node, err := sdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SyncthingDevice ID in the query.
// Returns a *NotSingularError when more than one SyncthingDevice ID is found.
// Returns a *NotFoundError when no entities are found.
func (sdq *SyncthingDeviceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sdq.Limit(2).IDs(setContextOp(ctx, sdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{syncthingdevice.Label}
	default:
		err = &NotSingularError{syncthingdevice.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sdq *SyncthingDeviceQuery) OnlyIDX(ctx context.Context) int {
	id, err := sdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SyncthingDevices.
func (sdq *SyncthingDeviceQuery) All(ctx context.Context) ([]*SyncthingDevice, error) {
	ctx = setContextOp(ctx, sdq.ctx, "All")
	if err := sdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SyncthingDevice, *SyncthingDeviceQuery]()
	return withInterceptors[[]*SyncthingDevice](ctx, sdq, qr, sdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sdq *SyncthingDeviceQuery) AllX(ctx context.Context) []*SyncthingDevice {
	nodes, err := sdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SyncthingDevice IDs.
func (sdq *SyncthingDeviceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sdq.ctx.Unique == nil && sdq.path != nil {
		sdq.Unique(true)
	}
	ctx = setContextOp(ctx, sdq.ctx, "IDs")
	if err = sdq.Select(syncthingdevice.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sdq *SyncthingDeviceQuery) IDsX(ctx context.Context) []int {
	ids, err := sdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sdq *SyncthingDeviceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sdq.ctx, "Count")
	if err := sdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sdq, querierCount[*SyncthingDeviceQuery](), sdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sdq *SyncthingDeviceQuery) CountX(ctx context.Context) int {
	count, err := sdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sdq *SyncthingDeviceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sdq.ctx, "Exist")
	switch _, err := sdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sdq *SyncthingDeviceQuery) ExistX(ctx context.Context) bool {
	exist, err := sdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SyncthingDeviceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sdq *SyncthingDeviceQuery) Clone() *SyncthingDeviceQuery {
	if sdq == nil {
		return nil
	}
	return &SyncthingDeviceQuery{
		config:     sdq.config,
		ctx:        sdq.ctx.Clone(),
		order:      append([]syncthingdevice.OrderOption{}, sdq.order...),
		inters:     append([]Interceptor{}, sdq.inters...),
		predicates: append([]predicate.SyncthingDevice{}, sdq.predicates...),
		withOwner:  sdq.withOwner.Clone(),
		// clone intermediate query.
		sql:  sdq.sql.Clone(),
		path: sdq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (sdq *SyncthingDeviceQuery) WithOwner(opts ...func(*UserQuery)) *SyncthingDeviceQuery {
	query := (&UserClient{config: sdq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sdq.withOwner = query
	return sdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SyncthingDevice.Query().
//		GroupBy(syncthingdevice.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sdq *SyncthingDeviceQuery) GroupBy(field string, fields ...string) *SyncthingDeviceGroupBy {
	sdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SyncthingDeviceGroupBy{build: sdq}
	grbuild.flds = &sdq.ctx.Fields
	grbuild.label = syncthingdevice.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SyncthingDevice.Query().
//		Select(syncthingdevice.FieldCreatedAt).
//		Scan(ctx, &v)
func (sdq *SyncthingDeviceQuery) Select(fields ...string) *SyncthingDeviceSelect {
	sdq.ctx.Fields = append(sdq.ctx.Fields, fields...)
	sbuild := &SyncthingDeviceSelect{SyncthingDeviceQuery: sdq}
	sbuild.label = syncthingdevice.Label
	sbuild.flds, sbuild.scan = &sdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SyncthingDeviceSelect configured with the given aggregations.
func (sdq *SyncthingDeviceQuery) Aggregate(fns ...AggregateFunc) *SyncthingDeviceSelect {
	return sdq.Select().Aggregate(fns...)
}

func (sdq *SyncthingDeviceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sdq); err != nil {
				return err
			}
		}
	}
	for _, f := range sdq.ctx.Fields {
		if !syncthingdevice.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sdq.path != nil {
		prev, err := sdq.path(ctx)
		if err != nil {
			return err
		}
		sdq.sql = prev
	}
	return nil
}

func (sdq *SyncthingDeviceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SyncthingDevice, error) {
	var (
		nodes       = []*SyncthingDevice{}
		_spec       = sdq.querySpec()
		loadedTypes = [1]bool{
			sdq.withOwner != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SyncthingDevice).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SyncthingDevice{config: sdq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sdq.withOwner; query != nil {
		if err := sdq.loadOwner(ctx, query, nodes, nil,
			func(n *SyncthingDevice, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sdq *SyncthingDeviceQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*SyncthingDevice, init func(*SyncthingDevice), assign func(*SyncthingDevice, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SyncthingDevice)
	for i := range nodes {
		fk := nodes[i].OwnerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "owner_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sdq *SyncthingDeviceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sdq.querySpec()
	_spec.Node.Columns = sdq.ctx.Fields
	if len(sdq.ctx.Fields) > 0 {
		_spec.Unique = sdq.ctx.Unique != nil && *sdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sdq.driver, _spec)
}

func (sdq *SyncthingDeviceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(syncthingdevice.Table, syncthingdevice.Columns, sqlgraph.NewFieldSpec(syncthingdevice.FieldID, field.TypeInt))
	_spec.From = sdq.sql
	if unique := sdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sdq.path != nil {
		_spec.Unique = true
	}
	if fields := sdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncthingdevice.FieldID)
		for i := range fields {
			if fields[i] != syncthingdevice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if sdq.withOwner != nil {
			_spec.Node.AddColumnOnce(syncthingdevice.FieldOwnerID)
		}
	}
	if ps := sdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sdq *SyncthingDeviceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sdq.driver.Dialect())
	t1 := builder.Table(syncthingdevice.Table)
	columns := sdq.ctx.Fields
	if len(columns) == 0 {
		columns = syncthingdevice.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sdq.sql != nil {
		selector = sdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sdq.ctx.Unique != nil && *sdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sdq.predicates {
		p(selector)
	}
	for _, p := range sdq.order {
		p(selector)
	}
	if offset := sdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SyncthingDeviceGroupBy is the group-by builder for SyncthingDevice entities.
type SyncthingDeviceGroupBy struct {
	selector
	build *SyncthingDeviceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sdgb *SyncthingDeviceGroupBy) Aggregate(fns ...AggregateFunc) *SyncthingDeviceGroupBy {
	sdgb.fns = append(sdgb.fns, fns...)
	return sdgb
}

// Scan applies the selector query and scans the result into the given value.
func (sdgb *SyncthingDeviceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sdgb.build.ctx, "GroupBy")
	if err := sdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SyncthingDeviceQuery, *SyncthingDeviceGroupBy](ctx, sdgb.build, sdgb, sdgb.build.inters, v)
}

func (sdgb *SyncthingDeviceGroupBy) sqlScan(ctx context.Context, root *SyncthingDeviceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sdgb.fns))
	for _, fn := range sdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sdgb.flds)+len(sdgb.fns))
		for _, f := range *sdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SyncthingDeviceSelect is the builder for selecting fields of SyncthingDevice entities.
type SyncthingDeviceSelect struct {
	*SyncthingDeviceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sds *SyncthingDeviceSelect) Aggregate(fns ...AggregateFunc) *SyncthingDeviceSelect {
	sds.fns = append(sds.fns, fns...)
	return sds
}

// Scan applies the selector query and scans the result into the given value.
func (sds *SyncthingDeviceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sds.ctx, "Select")
	if err := sds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SyncthingDeviceQuery, *SyncthingDeviceSelect](ctx, sds.SyncthingDeviceQuery, sds, sds.inters, v)
}

func (sds *SyncthingDeviceSelect) sqlScan(ctx context.Context, root *SyncthingDeviceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sds.fns))
	for _, fn := range sds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
