// Code generated by ent, DO NOT EDIT.

package ftsexternaljob

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the ftsexternaljob type in the database.
	Label = "fts_external_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFileID holds the string denoting the file_id field in the database.
	FieldFileID = "file_id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldSnapshotToken holds the string denoting the snapshot_token field in the database.
	FieldSnapshotToken = "snapshot_token"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldTriggerReason holds the string denoting the trigger_reason field in the database.
	FieldTriggerReason = "trigger_reason"
	// FieldAttempt holds the string denoting the attempt field in the database.
	FieldAttempt = "attempt"
	// FieldResultPayload holds the string denoting the result_payload field in the database.
	FieldResultPayload = "result_payload"
	// FieldErrorPayload holds the string denoting the error_payload field in the database.
	FieldErrorPayload = "error_payload"
	// FieldManifestPath holds the string denoting the manifest_path field in the database.
	FieldManifestPath = "manifest_path"
	// FieldQualityReport holds the string denoting the quality_report field in the database.
	FieldQualityReport = "quality_report"
	// FieldRequestedAt holds the string denoting the requested_at field in the database.
	FieldRequestedAt = "requested_at"
	// FieldDeadlineAt holds the string denoting the deadline_at field in the database.
	FieldDeadlineAt = "deadline_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// Table holds the table name of the ftsexternaljob in the database.
	Table = "fts_external_jobs"
)

// Columns holds all SQL columns for ftsexternaljob fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldRequestID,
	FieldStatus,
	FieldFileID,
	FieldOwnerID,
	FieldEntityID,
	FieldSnapshotToken,
	FieldMode,
	FieldTriggerReason,
	FieldAttempt,
	FieldResultPayload,
	FieldErrorPayload,
	FieldManifestPath,
	FieldQualityReport,
	FieldRequestedAt,
	FieldDeadlineAt,
	FieldCompletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/cloudreve/Cloudreve/v4/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultMode holds the default value on creation for the "mode" field.
	DefaultMode string
	// DefaultTriggerReason holds the default value on creation for the "trigger_reason" field.
	DefaultTriggerReason string
	// DefaultAttempt holds the default value on creation for the "attempt" field.
	DefaultAttempt int
	// DefaultRequestedAt holds the default value on creation for the "requested_at" field.
	DefaultRequestedAt func() time.Time
)

// OrderOption defines the ordering options for the FTSExternalJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFileID orders the results by the file_id field.
func ByFileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileID, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// BySnapshotToken orders the results by the snapshot_token field.
func BySnapshotToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotToken, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByTriggerReason orders the results by the trigger_reason field.
func ByTriggerReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerReason, opts...).ToFunc()
}

// ByAttempt orders the results by the attempt field.
func ByAttempt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempt, opts...).ToFunc()
}

// ByResultPayload orders the results by the result_payload field.
func ByResultPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultPayload, opts...).ToFunc()
}

// ByErrorPayload orders the results by the error_payload field.
func ByErrorPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorPayload, opts...).ToFunc()
}

// ByManifestPath orders the results by the manifest_path field.
func ByManifestPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManifestPath, opts...).ToFunc()
}

// ByQualityReport orders the results by the quality_report field.
func ByQualityReport(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQualityReport, opts...).ToFunc()
}

// ByRequestedAt orders the results by the requested_at field.
func ByRequestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedAt, opts...).ToFunc()
}

// ByDeadlineAt orders the results by the deadline_at field.
func ByDeadlineAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeadlineAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}
